kata-containers/runtime

.gitmodules
this importing resolves #9 together with CC import
Signed-off-by: Wang Xu <gnawux@gmail.com>
=> import runV runtime as a submodule

.ci/lib.sh, .ci/static-checks.sh, .travis.yml
Run the central static check script to enable `checkcommits`.
Fixes #8.
=> CI: Enable checkcommits

cli/Makefile
Now that the only build project is Kata, remove the remaining code to
support other projects and simplify.
Fixes #76.
=> build: Simplify CLI makefile

.travis.yml
So that we can test in personal travis setup.
Fixes: #104
Signed-off-by: Peng Tao <bergwolf@gmail.com>
=> CI: add go_import_path

Makefile
They only exist to remove the generated file `cli/generated.go` but the
removal is unnecessary because:
1. it is ignored in .gitignore
2. it get rebuilt every time when we run `make`
Fixes: #108
=> Makefile: remove git hooks

README.md
Add in details to the `README`.
Fixes #111.
=> docs: Improve the README

virtcontainers/container.go, virtcontainers/kata_agent.go
This pull request ensures that when a container creation fails, any mount or hotplug action performed during this creation phase will be undone to leave the system in the state it was before.
Fixes #135
=> virtcontainers: Properly rollback mounts and hotplugs when container creation failed

virtcontainers/container.go, virtcontainers/kata_agent.go
The rollback does not work as expected because the error has to be
checked from the defer itself.
Fixes #178
=> virtcontainers: Fix container creation rollback

Gopkg.lock, cli/main.go, cli/spec.go, cli/spec_test.go, vendor/github.com/opencontainers/runc/libcontainer/seccomp/config.go, vendor/github.com/opencontainers/runc/libcontainer/seccomp/seccomp_linux.go, vendor/github.com/opencontainers/runc/libcontainer/seccomp/seccomp_unsupported.go, vendor/github.com/opencontainers/runc/libcontainer/specconv/example.go, vendor/github.com/opencontainers/runc/libcontainer/specconv/spec_linux.go, vendor/github.com/seccomp/libseccomp-golang/LICENSE, vendor/github.com/seccomp/libseccomp-golang/seccomp.go, vendor/github.com/seccomp/libseccomp-golang/seccomp_internal.go
Add spec command that  that generates a basic config.json for kata.
fixes #188
=> cli: implement spec command

versions.yaml
Add latest release from cri-containerd.
Fixes: #239
=> versions: Add cri-containerd to versions file.

README.md
=> Update the README.md so showing that containerd is supported

cli/kata-check.go, cli/kata-check_amd64.go, cli/kata-check_arm64.go, cli/kata-check_ppc64le.go, cli/kata-check_test.go, cli/kata-env_test.go, cli/utils.go, cli/utils_test.go, virtcontainers/qemu_arm64.go
Fix ARM64 build which silently broken (as we still don't have an ARM CI).
Fixes #349.
=> arch/arm64: Fix ARM64 build

README.md
=> docs: Update README with Power Support

.travis.yml
=> CI: Enable Travis-CI for linux-ppc64le

README.md
Fixes: #391
Replace invalid urls with new legal ones.
Signed-off-by: Zhang Wei <zhangwei555@huawei.com>
Carry https://github.com/kata-containers/runtime/pull/392
=> docs: fix invalid urls

Makefile, data/completions/bash/kata-runtime
Add kata command line bash completion
Fixes #110
=> subsystem: cli

.ci/lib.sh
The script now has new options.
Add options to make CI work.
Fixes: #438
=> ci: Fix static checks call.

virtcontainers/device/drivers/vfio.go, virtcontainers/kata_agent_test.go, virtcontainers/shim_test.go, virtcontainers/types.go
virtcontainer : sconstification of constifiable vars
Fixes #142
Signed-off-by: zhangjie <zhangjie0619@yeah.net>
=> virtcontainer : sconstification of constifiable vars

cli/kata-check_ppc64le.go
SMT must be turned off on Power8 for KVM to work. Put
this as a check for kata-runtime kata-check.
Fixes: #397
=> cli: kata-check if SMT is off on POWER8 systems

virtcontainers/network_test.go
=> network: Add test for VhostUserEndpoint Attach()

versions.yaml
Some test were CI test were failing due to a race condition.
Update cri-o repository to have a stable CI.
Fixes: #435
=> versions: Update cri-o to fix race condition test.

Makefile
=> makefile: update PREFIX to remove redundant slash

cli/config.go
=> cli: Make message of using initrd OR rootfs clearer

virtcontainers/qemu_arm64.go
QEMU supports GICv2, GICv3 and host parameters for guest gic-version. The "host" parameter will let QEMU detect GIC version by itself. This parameter will work properly when host GIC version is GICv2 or GICv3. But the detection will failed when host GIC is GICv4 or higher:
"Unable to determine GIC version supported by host"
In this case, we have to detect the host GIC version manually and force QEMU to use GICv3 when host GIC is GICv4 or higher.
Fixes: #614
Signed-off-by: Wei Chen <wei.chen@arm.com>
=> qemu/arm64: Detect host GIC version to configure guest GIC

versions.yaml
Update kernel version to 4.14.67
Fixes: #698
=> versions: update kernel version 4.14.67

Gopkg.lock, Gopkg.toml, vendor/github.com/intel/govmm/qemu/image.go, vendor/github.com/intel/govmm/qemu/qemu.go, vendor/github.com/intel/govmm/qemu/qmp.go, virtcontainers/qemu.go
backport from commit-id: f841e89d in master branch to stable-1.1 branch
govmm has ExecuteBlockdevAdd() function and ExecuteBlockdevDel() function
doesn't compatible with qemu 2.8,because blockdev-add and x-blockdev-del usages
are different between qemu 2.7 and qemu 2.8
shortlog:
ce070d1 govmm: modify govmm to be compatible with qemu 2.8
0286ff9 qemu/qmp: support hotplug a nic whose qdisc is mq
8515ae4 qmp: Remind users that you must first call ExecuteQMPCapabilities()
21504d3 qemu/qmp: Add netdev_add with chardev support
ed34f61 Add some negative test cases for qmp.go
17cacc7 Add negative test cases for qemu.go
2706a07 qemu: Use the supplied context.Context for launching
e46092e qemu: Do not try and generate invalid RTC parameters
fcaf61d qemu/qmp: add vfio mediated device support
4461c45 …
=> vendor: update govmm to be compatible with qemu 2.8 to stable 1.1 branch

virtcontainers/network.go, virtcontainers/sandbox.go
Support to hotplug vhost and physical endpoints by AddInterface API
Fixes #758
=> virtcontainers: support vhost and physical endpoints in AddInterface

virtcontainers/network.go
These were skipped.
Fixes #842
=> network: Marshal BridgedMacvlanEndpoint and MacvtapEndpoint

Makefile, cli/kata-check.go, cli/kata-check_ppc64le.go, cli/kata-env_test.go, cli/list_test.go, cli/main.go, cli/main_test.go, cli/oci.go, cli/utils.go, cli/utils_test.go, pkg/katautils/config-settings.go, pkg/katautils/config.go, pkg/katautils/config_test.go, pkg/katautils/logger.go, pkg/katautils/logger_test.go, pkg/katautils/utils.go, pkg/katautils/utils_test.go
Since to refactor the cli codes will be a big task, and I will try
to split it into several PRs.
This is the first PR for refactor the config related codes.
=> cli: refactor the config into a separated package

virtcontainers/physical_endpoint.go
close socket after use ethtool.NewEthtool()
Fixes: #919 
=> virtcontainers: fix not close socket with ethtool

cli/console.go
The function ioctl can lead to a big endian bug.
Issue already solved in containerd/console:
https://github.com/containerd/console/pull/20/commits/dbd69c59b81ec72258da35a335605e4b3ea17e6a
Fixes: #921
=> cli: Fix console for big endian architecture

virtcontainers/api.go
When our runtime is asked for the container status, we also handle
the scenario where the container is stopped if the shim process for
that container on the host has terminated.
In the current implementation, we retrieve the container status
before stopping the container, causing a wrong status to be returned.
The wait for the original go-routine's completion was done in a defer
within the caller of statusContainers(), resulting in the
statusContainer()'s values to return the pre-stopped value.
This bug is first observed when updating to docker v18.09/containerd
v1.2.0. With the current implementation, containerd-shim receives the
TaskExit when it detects kata-shim is terminating. When checking the
container state, however, it does not get the expected "stopped" value.
The following …
=> virtcontainers: Return the appropriate container status

Gopkg.lock, Gopkg.toml, vendor/github.com/intel/govmm/CONTRIBUTORS.md, vendor/github.com/intel/govmm/qemu/qmp.go
Shortlog:
97fc343 contributors: add my name
c891f5f qmp: Add nvdimm support
Fixes #991
=> vendor: Update govmm vendoring

versions.yaml
Include info such as commit number,tag number, etc for building
nvdimm-supported qemu on aarch64 from source code.
Fixes: #974
=> versions: refactor configuration of qemu in version.yaml

Makefile
Most of the projects, they can be built with "make".  After that,
"sudo make install" can install the application.
It is not work for kata-runtime because kata-runtime's make must work
with golang in the environment that default sudo cannot supply it.
But "make install" doesn't need golang.
So add "GOPATH not set" to handle the issue.
Fixes: #1008
=> make: Add "GOPATH not set"

containerd-shim-v2/service.go
containerd would like to get the shim's socket
address from shimv2's stdout, thus it's better
to discard the log's output in stdio before shimv2 init
it's logger and add a hook to log into syslog at the same time.
Fixes: #1035
Signed-off-by: Fupan Li <lifupan@gmail.com>
=> shimv2: discard log before shim init log output

containerd-shim-v2/service.go
Support multi wait on one container/exec process.
Fixes: #1131
=> shimv2: multi wait support for wait service

containerd-shim-v2/service.go
Because the runtime v2 runs as a RPC server, the caller will at some
point use the Shutdown() API to shut down the server. Because this
will cause the server to exit, the caller cannot expect any valid
answer when calling this. That's why we cannot afford stopping and
deleting the sandbox from this function.
Instead, we move sandbox.Stop() and sandbox.Delete() to a more
appropriate API, the Delete() one.
Fixes #1150
=> runtime-v2: Make sure Shutdown() only shuts the server down

virtcontainers/qemu.go
The error message does not provide the max memory that is exceeded.
Fix it for better error information.
Fixes: #1120
=> vc: qemu: fix error message on hotplug.

cli/factory.go
Fixes: #1163 
Signed-off-by: Wei Li <liwei@anbutu.com>
=> factory: do not destroy vm factory when checking status

containerd-shim-v2/service.go
The Runtime v2 supports an async event model. In order for the an upstream
caller (such as Docker) to get these events in the correct order a Runtime
v2 shim MUST implement some events.
For much more info, please see:
https://github.com/containerd/containerd/blob/master/runtime/v2/README.md#events
Fixes:#1204
=> shimv2: Send async task events to containerd/cri

versions.yaml
Update Clear Linux rootfs to latest.
=> versions: use clear linux latest rootfs.

versions.yaml
Update kernel to get latest fixes.
Fixes #1269
=> versions: Update kernel to 4.14.102

virtcontainers/qemu_s390x.go
Changed capital letter of VirtioSerialCCW to avoid golint complain
Fixes : #1327
=> s390x: fix golint complain

versions.yaml
Latest release fixes entropy issue.
Fixes: #1251.
Fixes: #987.
=> versions: update nemu to latest release

virtcontainers/sandbox.go, virtcontainers/sandbox_test.go
Make cpu and memory calculation in a different function this help to reduce
the function complexity and easy  unit test.
Fixes: #1296
=> virtcontainers: move resource calculation to its own function

virtcontainers/qemu_s390x_test.go
There are 2 small fixes to make the testsuite running on s390x
=> s390x: 2 small test fixes

versions.yaml
Update kernel to latest version.
Fixes: #1288
=> versions: kernel: update to 4.19.28

virtcontainers/device/drivers/block.go, virtcontainers/device/drivers/generic.go, virtcontainers/device/drivers/generic_test.go, virtcontainers/device/drivers/vfio.go, virtcontainers/device/drivers/vhost_user_blk.go, virtcontainers/device/drivers/vhost_user_net.go, virtcontainers/device/drivers/vhost_user_scsi.go
Fixes #1392
Improve code readability of function `device.bumpAttachCount`
=> refactor: improve readability of `bumpAttachCount`

virtcontainers/fc.go
Disable ACPI to fix ACPI BIOS error in the guest kernel
fixes #1454
cc @mcastelino 
=> virtcontainers: firecracker: disable ACPI

README.md
update architecture.md link, since it has moved to within the
design/ directory.
Fixes: #1462
Signed-off-by: Gabi Beyer <Gabrielle.n.beyer@intel.com>
=> doc: update architecture.md link

.ci/lib.sh
Use TRAVIS branch to checkout test repository
=> ci: travis

Gopkg.lock, Gopkg.toml, vendor/github.com/intel/govmm/qemu/qemu.go, vendor/github.com/intel/govmm/qemu/qmp.go
Bring QMP fixes and vhost-user support
Shortlog:
694a7b1 qemu/qmp: re-implement mainLoop
5712b11 qemu/qmp: fix readLoop() reuse scanner.Bytes() underlying array problem
3c84b1d govmm: add VhostUserFS vhost-user device type
fixes #1497
=> vendor: update govmm

cli/kata-check_s390x_test.go, virtcontainers/qemu_s390x.go
Fix lint complains in the s390x files
Fixes: #1453
=> s390x: fix golangci-lint complains

cli/factory.go, pkg/katautils/config.go, pkg/katautils/create.go, virtcontainers/factory/factory.go
Make VMCache and VM templating can work together.
Fixes: #1376
=> factory: Make VMCache and VM templating can work together

virtcontainers/qemu_s390x.go
Fix gofmt complain for virtcontainers/qemu_s390x.go
Fixes: #1553
=> s390x: fix gofmt complain

virtcontainers/container.go, virtcontainers/sandbox_test.go, virtcontainers/types/container.go
=> vc: remove BlockIndex from container state

cli/config/configuration-qemu.toml.in, cli/factory.go, cli/factory_test.go, pkg/katautils/config-settings.go, pkg/katautils/config.go, pkg/katautils/config_test.go, pkg/katautils/create.go, virtcontainers/factory/factory.go, virtcontainers/factory/factory_test.go, virtcontainers/factory/template/template.go, virtcontainers/factory/template/template_test.go, virtcontainers/pkg/oci/utils.go
Add new factory option template_path that specifies the path of template.
Fixes: #1549
=> factory: Add new factory option template_path

README.md, virtcontainers/documentation/Developers.md, virtcontainers/documentation/api/1.0/api.md
Fix various issues with the markdown files in this repo.
Fixes: #1564.
=> Fix markdown

virtcontainers/container.go, virtcontainers/kata_agent.go, virtcontainers/persist.go, virtcontainers/persist/api/container.go, virtcontainers/persist/api/sandbox.go
Fixes #803
Merge more container storage files with `persist.json` including:
* devices.json
* mounts.json
* process.json
=> persist: merge more files with `persist.json`

virtcontainers/kata_agent.go
We should not let shim read guest console socket if agent
debug console is set. Otherwise when we connect to it with
socat, it reads nothing since all output is read by the shim.
Fixes: #1700
=> agent: fix agent debug console

README.md, pkg/README.md, pkg/katautils/README.md, pkg/signals/README.md, virtcontainers/README.md
Add a few minimal documents to allow all the documentation in this repository to be navigated from the top-level README.
Fixes #1681.
=> Add missing docs

README.md, pkg/katatestutils/README.md, virtcontainers/README.md, virtcontainers/documentation/api/1.0/api.md, virtcontainers/experimental/README.md
Correct typos and formatting issues.
Fixes: #1734.
=> docs: Fix spelling and formatting

arch/amd64-options.mk, versions.yaml
Update qemu version to 4.0.0.
fixes #1743
=> versions: update qemu version to 4.0.0

pkg/katatestutils/README.md, virtcontainers/README.md, virtcontainers/documentation/Developers.md, virtcontainers/documentation/api/1.0/api.md, virtcontainers/experimental/README.md, virtcontainers/persist/plugin/README.md
Correct spelling mistakes and formatting issues.
Fixes: #1792.
=> docs: Fix typos and formatting

versions.yaml
=> versions update kernel to 4.19.52

cli/kata-check.go, cli/kata-check_arm64.go
Auger Eric's latest patches about [ARM virt: Initial RAM expansion and extended memory map](https://patchwork.kernel.org/cover/10835377/) paves the way to device memory, which is the foundation for NVDIMM and memory hotplug.
This new feature on qemu kinds of depends on host kernel's new feature
on [dynamic IPA range](https://lwn.net/Articles/750176/).
The availability of this feature is advertised by a new kvm cap `KVM_CAP_ARM_VM_IPA_SIZE`. When supported, this capability returns the maximum IPA shift supported by the host. 
The supported IPA size on a host could be different from the system's PARange indicated
by the CPUs (e.g, kernel limit on the PA size).
This is how my local arm64 machine shows:
```
INFO[0000] kvm extension is supported                    arch=arm64 …
```
=> kata-check: add kvm extension check on aarch64

.travis.yml
This will install correct dependencies for running
static checks.
Fixes: #1844.
=> CI: Run .ci/setup.sh from tests repo

README.md
Update broken Clear Linux stateless URL.
Fixes: #1846.
=> docs: Fix broken URL

Makefile, cli/config/configuration-acrn.toml.in, cli/config/configuration-fc.toml.in, cli/config/configuration-nemu.toml.in, cli/config/configuration-qemu.toml.in, virtcontainers/acrn_arch_base.go
We plan to get rid of this feature in the future.
Fixes: #1950
=> network: Deprecate bridged networking mode.

virtcontainers/monitor.go
enlarge watch buffer, or no one consume monitor watcher if shim.Wait and shim.watchSandbox
simultaneously receive signal
goroutine 60 [semacquire, 641 minutes]:
sync.runtime_SemacquireMutex(0xc00037a144, 0x42cd00)
/usr/local/go/src/runtime/sema.go:71 +0x3d
sync.(*Mutex).Lock(0xc00037a140)
/usr/local/go/src/sync/mutex.go:134 +0x109
github.com/kata-containers/runtime/virtcontainers.(*monitor).stop(0xc00037a140)
/go/src/github.com/kata-containers/runtime/virtcontainers/monitor.go:95 +0x5f
github.com/kata-containers/runtime/virtcontainers.(*Sandbox).Delete(0xc0003c8160, 0x78effdc01, 0x0)
/go/src/github.com/kata-containers/runtime/virtcontainers/sandbox.go:773 +0x4fb
github.com/kata-containers/runtime/containerd-shim-v2.wait(0xc000478b80, 0xc000338240, 0x0, 0x0, 0x107d540, 0xc0000100f0, …
=> monitor: enlarge watch buffer

versions.yaml
Bump to latest stable
Fixes: #1816
=> kernel: update to 4.19.71

virtcontainers/container.go, virtcontainers/container_test.go
`virtcontainers.ensureDestinationExists` will create the bind destination directory/file, which should be removed properly when unmounting.
Fixes: https://github.com/kata-containers/runtime/issues/1974
=> vc: Remove bind destination when unmounting

virtcontainers/qemu.go, virtcontainers/qemu_arch_base.go, virtcontainers/qemu_arch_base_test.go, virtcontainers/qemu_ppc64le.go, virtcontainers/qemu_s390x.go
Add error return code to append functions.
Fixes: #2035
=> virtcontainer: add error return code

virtcontainers/sandbox.go
Fixes: #2068
Signed-off-by: Wang Liang <wangliangzz@inspur.com>
=> The unit of newMemory is MB

versions.yaml
Include patches that fixes overlay2 issues.
Fixes: #2082
=> versions: Update kernel to 4.19.75

virtcontainers/factory/cache/cache_test.go, virtcontainers/store/manager.go, virtcontainers/store/manager_test.go, virtcontainers/store/vc.go, virtcontainers/store/vc_test.go
1. vc store should reuse existing stores
2. add store prefix in order to allow UTs to be run as non-root
=> Fix cache factory UT

virtcontainers/sandbox.go
state: Load the state from storage early on
The hypervisor.createSandbox may need to access the state.
For eg, ACRN today needs to access the block index to assign
it to the root image of the VM. Hence load this early on.
Without this, the acrn createSandbox() call overwrites the wrong state
as it has not been loaded from storage yet.
Fixes #2026
=> Load state early so that hypervisor can store the correct state

.ci/versions_checker.sh, .travis.yml
Version checker does to work today
- Allow to detect stabe branches
Fixes #1581
=> ci: Fix versions_checker.sh

versions.yaml
Fixes: #2154
Signed-off-by: Yang Bo <bo@hyper.sh>
=> versions: support specify version in versions.yaml for rust agent.

versions.yaml
Fixes: #2162
Signed-off-by: Yang Bo <bo@hyper.sh>
=> versions: move cmake and musl version into versions.yaml

versions.yaml
Needed to build as part of release and CI process.
Fixes: #2218
=> versions: Add cloud-hypervisor

virtcontainers/persist/fs/fs.go
=> vc: Clean up directories in case MkdirAll fails

virtcontainers/container.go, virtcontainers/kata_agent.go
=> vc: Utilize map for newMounts to speed up replaceOCIMountSource

virtcontainers/sandbox.go
=> vc: Use map built-in accessor to find container in Sandbox#GetContainer

virtcontainers/clh.go
Fixes #2297
Signed-off-by: Ted Yu yuzhihong@gmail.com
=> vc: Check return value from os.MkdirAll in virtiofsdArgs

virtcontainers/fc.go
=> Fc comment

virtcontainers/persist/fs/fs.go
Fixes #2241
Signed-off-by: Ted Yu yuzhihong@gmail.com
=> vc: Persist file handle may leak in FS#ToDisk

virtcontainers/sandbox.go
Fixed `Sandbox::getAndSetSandboxBlockIndex() so that
it does not update `BlockIndex` if an error occurs.
Fixes #2244
=> vc: Don't adjust block index on error

virtcontainers/sandbox.go
=> vc: Remove device when AddDevice encounters error

virtcontainers/qemu.go
Commit 89e0dfae111e ("qemu: stop qemu process when virtiofsd quits")
stops sandbox when virtiofsd quits so that virtiofs mount inside guest
won't hang. But commit d5a3d0a61c70 ("virtiofs: use virtiofsd
--fd=FDNUM") deleted this monitor logic.
Add the Scanner back to monitor virtiofsd's stderr and stop sandbox if
Scanner returns error.
Note that we don't monitor the virtiofsd process itself is because
virtiofsd may be live-upgraded (when available) and the original
process may quit, but virtiofs service is still running.
Fixes: #2315 
Fixes: d5a3d0a61c70 ("virtiofs: use virtiofsd --fd=FDNUM")
Signed-off-by: Eryu Guan <eguan@linux.alibaba.com>
=> virtiofs: stop sandbox when virtiofsd quits

virtcontainers/clh.go
Fixes #2324
This achieves parity with the check on line 293.
=> vc: Check error return from storeState

virtcontainers/pkg/cloud-hypervisor/Makefile
Instead of point to master use the version defined
in versions.yaml
Fixes: #2341
=> clh: client: update acording to versions.yaml

virtcontainers/fc.go
When we used jailer to launch firecracker, kata container failed.
```
$ docker run --runtime kata-runtime busybox
docker: Error response from daemon: OCI runtime create failed: Failed to 
connect to firecrackerinstance (timeout 10s): unknown.
```
Causes and Fixes are as follows:
1. new flag `-config-file` belongs to the jailed firecracker.
so, adhering to the `end of command options` convention, we need to give `config-file` a 
prefix `--`.
2. The path of the config file(`fcConfig.json`) should be also relative to the jailed firecracker.
3. Since we do the configuration before func `fcInit` now, we also need to bring `jailer check` ahead.
=> FC: jailer failed when importing new flag "--config-file"

virtcontainers/container.go
In Container#mountSharedDirMounts, if sandbox.storeSandboxDevices() returns error, we should detach the device.
Fixes #2301
Signed-off-by: Ted Yu yuzhihong@gmail.com
=> vc: Detach device when unable to store sandbox device

netmon/netmon.go, netmon/netmon_test.go, virtcontainers/network.go, virtcontainers/network_test.go
With this PR, ipv6 addresses and routes are now handled by virtcontainers and netmon.
=> Add Ipv6 support

virtcontainers/mock_hypervisor.go
Clearly a result of copy&paste :)
=> virtcontainers: Fix error message in mockHypervisor

README.md
Minor updates on some wording and clarificaitons.
Fixes: #2144
=> docs: README: Minor grammatical updates

versions.yaml, virtcontainers/pkg/cloud-hypervisor/client/README.md, virtcontainers/pkg/cloud-hypervisor/client/api/openapi.yaml, virtcontainers/pkg/cloud-hypervisor/client/api_default.go, virtcontainers/pkg/cloud-hypervisor/client/client.go, virtcontainers/pkg/cloud-hypervisor/client/configuration.go, virtcontainers/pkg/cloud-hypervisor/client/docs/DiskConfig.md, virtcontainers/pkg/cloud-hypervisor/client/docs/NetConfig.md, virtcontainers/pkg/cloud-hypervisor/client/docs/VmResize.md, virtcontainers/pkg/cloud-hypervisor/client/go.mod, virtcontainers/pkg/cloud-hypervisor/client/go.sum, virtcontainers/pkg/cloud-hypervisor/client/model_disk_config.go, virtcontainers/pkg/cloud-hypervisor/client/model_net_config.go, virtcontainers/pkg/cloud-hypervisor/client/model_vm_resize.go, virtcontainers/pkg/cloud-hypervisor/cloud-hypervisor.yaml
=> Update Cloud Hypervisor to v0.5.0

Gopkg.lock
Gopkg.lock has gone out of sync.
Ran dep ensure to fix it.
Fixes #2445
=> dep: Fix dep check

virtcontainers/persist/fs/fs.go, virtcontainers/sandbox.go
=> Fix typos in sandbox and persist/fs

virtcontainers/api_test.go, virtcontainers/cgroups.go, virtcontainers/cgroups_test.go, virtcontainers/container.go, virtcontainers/kata_agent.go, virtcontainers/pkg/cgroups/manager.go, virtcontainers/pkg/cgroups/manager_test.go, virtcontainers/pkg/cgroups/utils.go, virtcontainers/pkg/cgroups/utils_test.go, virtcontainers/sandbox.go, virtcontainers/sandbox_test.go
=> Implement cgroup manager

virtcontainers/clh.go
Add support for new version format from clh.
Fixes: #2489
=> clh: Fix version check

versions.yaml, virtcontainers/clh.go, virtcontainers/clh_test.go, virtcontainers/pkg/cloud-hypervisor/client/README.md, virtcontainers/pkg/cloud-hypervisor/client/api/openapi.yaml, virtcontainers/pkg/cloud-hypervisor/client/api_default.go, virtcontainers/pkg/cloud-hypervisor/client/docs/DefaultApi.md, virtcontainers/pkg/cloud-hypervisor/client/docs/DeviceConfig.md, virtcontainers/pkg/cloud-hypervisor/client/docs/MemoryConfig.md, virtcontainers/pkg/cloud-hypervisor/client/docs/PmemConfig.md, virtcontainers/pkg/cloud-hypervisor/client/docs/VmRemoveDevice.md, virtcontainers/pkg/cloud-hypervisor/client/model_memory_config.go, virtcontainers/pkg/cloud-hypervisor/client/model_pmem_config.go, virtcontainers/pkg/cloud-hypervisor/client/model_vm_remove_device.go, virtcontainers/pkg/cloud-hypervisor/client/model_vm_resize.go, virtcontainers/pkg/cloud-hypervisor/cloud-hypervisor.yaml, virtcontainers/utils/utils.go
Enable memory hotplug for cloud hypervisor.  Use clh openAPI to start VM with max amount of memory (based in host memory). 
- Implement memory hotplug
- Memory resize only can be done to increase memory
Depends-on: github.com/kata-containers/tests#2413
=> clh: Enable memory hotplug

versions.yaml, virtcontainers/kata_agent.go
This includes a newer kernel and necessary overlay changes
that fix oustanding issue for running docker in docker using
overlay.
Fixes #2603
=> versions: Switch to virtio-fs-dev branch for kernel

versions.yaml
Update kernel from 5.4.15 to 5.4.32
Fixes #2612
=> version: Update kernel to lts 5.4.32

Makefile
SELinux support requires libselinux to be available, but that's not the only factor: for example, Fedora 31 has libselinux but not a version of selinux-policy that knows about Kata containers, so enabling SELinux support by default in that case causes usability issues.
Another issue with the current implementation is that, when libselinux is absent, SELinux support will be quietly disabled, which might not be what the user (or packager) intended.
To solve both problems, introduce the new `FEATURE_SELINUX` user variable. This variable takes one of three values:
* check (default): keep the current behavior;
* yes: enable SELinux support, erroring out if libselinux is
not present on the system;
* no: disable SELinux support.
In the future we might want to formalize support for optional …
=> makefile: Make SELinux support configurable

virtcontainers/kata_agent.go
This will fix #2695
Signed-off-by: bin liu <liubin0329@gmail.com>
=> virtcontainers: GetOOMEvent should have no timeout

virtcontainers/api.go, virtcontainers/device/config/pmem.go, virtcontainers/kata_agent.go, virtcontainers/kata_agent_test.go
=> Backports for log fixes

virtcontainers/agent.go, virtcontainers/api_test.go, virtcontainers/container.go, virtcontainers/kata_agent.go, virtcontainers/kata_agent_test.go, virtcontainers/mount.go, virtcontainers/mount_test.go, virtcontainers/noop_agent.go, virtcontainers/noop_agent_test.go, virtcontainers/qemu.go, virtcontainers/qemu_test.go, virtcontainers/virtcontainers_test.go, virtcontainers/vm.go
The PR backports following commits from master:
4d0f3c5f vc: make host shared path readonly
=> backport a few bugfixes from master

virtcontainers/qemu_ppc64le.go
=> qemu: Fix travis build failure for Power

virtcontainers/api.go, virtcontainers/bridgedmacvlan_endpoint.go, virtcontainers/device/config/config.go, virtcontainers/device/drivers/generic.go, virtcontainers/device/drivers/vfio.go, virtcontainers/endpoint.go, virtcontainers/ipvlan_endpoint.go, virtcontainers/macvtap_endpoint.go, virtcontainers/network.go, virtcontainers/persist/api/device.go, virtcontainers/physical_endpoint.go, virtcontainers/qemu.go, virtcontainers/sandbox.go, virtcontainers/tap_endpoint.go, virtcontainers/tuntap_endpoint.go, virtcontainers/veth_endpoint.go, virtcontainers/vhostuser_endpoint.go, virtcontainers/vhostuser_endpoint_test.go
backport https://github.com/kata-containers/runtime/pull/2775
=> [backport 1.11] create cgroup manager after creating the network 

virtcontainers/types/asset_test.go
Add additional test cases that cover more asset types and functions to
increase unit test coverage.
Fixes #2835
=> virtcontainers: Expand unit test coverage for asset

versions.yaml
Update kernel to latest lts in versions.yaml
Fixes #2895
=> kernel: move to the latest LTS kernel 5.4.60

virtcontainers/virtiofsd.go, virtcontainers/virtiofsd_test.go
@devimc, @jcvenegas, @amshinde, please, take a look.
=> [stable-1.11] Backport "virtiofsd: Improve logging"

.travis.yml
Fixes: #2957
Signed-off-by: bin liu <bin@hyper.sh>
=> ci: clear travis config warnings

containerd-shim-v2/wait.go, virtcontainers/pkg/oci/utils.go, virtcontainers/pkg/oci/utils_test.go
Fixes: #2955
Signed-off-by: bin liu <bin@hyper.sh>
=> runtime: write oom file to notify CRI-O OOM occurred

containerd-shim-v2/service.go, pkg/katautils/config.go, virtcontainers/container.go, virtcontainers/hypervisor.go, virtcontainers/pkg/oci/utils.go, virtcontainers/pkg/oci/utils_test.go, virtcontainers/sandbox.go
Changes in this backport
42ec8413 virtiofs: Disable DAX
fd75db90 virtiofsd: Use cache=auto
6239df7f virtcontainers: fix delete sandbox failed problem
ec12ddbb shimv2: handle ctx passed by containerd
7b09e967 sandbox: Disconnect from agent after VM shutdown
=> Stable 1.11 backports

virtcontainers/kata_agent.go
=> Fix some error reporting in listInterfaces() and listRoutes()

versions.yaml
In addition to features related to gathering metrics around
several data-points, the releases leading to this release
carry a few secirty fixes.
Lets update to latest fircracker release.
References:
https://github.com/firecracker-microvm/firecracker/issues/2057
https://github.com/firecracker-microvm/firecracker/issues/2177
Fixes: #3095
=> versions: Update firecracker to 0.21.3

versions.yaml
Release included important security updates.
References:
https://github.com/firecracker-microvm/firecracker/issues/2057
https://github.com/firecracker-microvm/firecracker/issues/2177
Fixes: #3095
(cherry picked from commit 11c8c19eb95505fff2075f0f3491d17dc83074a4)
=> backport: versions: Update firecracker to 0.21.3

cli/main.go, virtcontainers/factory/template/template.go, virtcontainers/factory/template/template_test.go
=> factory: Use lazy unmount
