kata-containers/runtime

.pullapprove.yml
Add a `pullapprove.yml` that requires each PR to be approved
by two members of the `runtime` team.
=> CI: Add pullapprove and require two acks / PR

.gitmodules
This adds Clear Containers as a Kata Containers runtime, under
runtime/cc-runtime
The Docker `create`, `start`, `run`, `exec` and `ps` commands
work when using the cc-runtime code together with the vanilla
Kata shim, proxy and agent components. Shortly we will also
document how to build and install all of those together.
Signed-off-by: Samuel Ortiz <sameo@linux.intel.com>
=> runtime: Add Clear Containers runtime

.gitmodules
Use a standalone cli repo so that it can be built inside the
kata runtime directory.
fixes: #17
=> runv: update submodule repo

Makefile
Add a basic `Makefile` to allow a runtime to be built:
- Clear Containers-based Kata runtime:
```
$ make KATA_RUNTIME=cc [install]
```
- `runv`-based Kata runtime:
```
$ make KATA_RUNTIME=runv [install]
```
Fixes #15.
=> build: Add minimal Makefile

.gitignore, .gitmodules, Makefile
So that we can use runv repo as git submodule without splitting it.
=> runv: modify GOPATH to build

CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md
Add a README, along with the standard code of conduct and contributing
docs.
Fixes #29.
=> docs: Add missing standard docs

.ci/run.sh, .ci/setup.sh
The setup script will be in charge of clone the test repository, meanwhile,
the run script will be in charge of execute for example the docker
integration tests.
Fixes #36
=> ci: Add run.sh and setup.sh in order to run the tests.

virtcontainers/kata_agent.go, virtcontainers/kata_agent_test.go
This pull request relies on the latest agent changes to enable the support of virtio-scsi for block devices.
Fixes #56
=> virtcontainers: kata_agent: Add virtio-scsi support

virtcontainers/hyperstart_agent.go, virtcontainers/kata_agent.go
Since ipv6 is not yet supported, we should skip all ipv6 routes including those that have an ipv6 gatway.
=> Skip routes with ipv6 gateway

virtcontainers/utils/virtcontainers-setup.sh
Since Go 1.8 users no longer need to have GOPATH set in their environment
for the Go tool chain to work.  If GOPATH is set, Go will use it.  Otherwise
it defaults to ~/go on linux.  As most users store their code in ~/go, they
don't bother setting GOPATH any more.  virtcontainers-setup.sh, in its
current form, fails for those users, as it requires GOPATH to be set.
This commit fixes the issue by calling go env "GOPATH" to determine the
correct location of the user's go code.  go env "GOPATH" will always
return the correct location, whether GOPATH is set, or not.
Signed-off-by: Mark Ryan <mark.d.ryan@intel.com>
=> utils: Use go env to discover the GOPATH

Makefile
Use `make -C $dir` for simplicity. Cleanup whitespace and add a `clean` rule.
Fixes #78.
=> Simplify toplevel makefile

virtcontainers/qemu.go
In case of virtio-block, we hotplug devices to a bridge.
We need to remove device from bridge while stopping a
container.
Fixes #82
=> virtcontainers: qemu: Call removeDeviceFromBridge for virtio-blk

virtcontainers/agent.go, virtcontainers/container.go, virtcontainers/hyperstart_agent.go, virtcontainers/kata_agent.go, virtcontainers/noop_agent.go
After hot adding vCPUs in the POD, agent's funtion `onlineCPUMem`
must be called to request the agent to online the vCPUs
fixes #67
=> virtcontainers: agent: use onlineCPUMem to online vCPUs

.gitmodules
Both cc-runtime and runv git submodules can now be removed since
the new folder cli defines the OCI wrapper, and the kata API is
defined and implemented through the virtcontainers package in this
same repository.
Fixes #64
=> submodules: Remove cc-runtime and runv

.ci/lib.sh
The github path to the tests repo is hard wired in lib.sh.
This makes it difficult to test any test repo WIP, as it ends
up calling back to the main repo.
Fix by using any value already set, and only setting to the main
repo if unset.
Fixes: #95
Signed-off-by: Graham whaley <graham.whaley@intel.com>
=> ci: allow path to tests repo to be over-wridden

.github/ISSUE_TEMPLATE.md, .gitignore, Makefile, data/kata-collect-data.sh.in
Add a data collection script that can be run by users and its output
pasted directly into a github issue.
The script is designed to make diagnosing issues as easy as possible
and its output provides a summary of a Kata Containers system
including:
- Versions of all components.
- Details of container managers.
- Errors found in the system journal.
Fixes #80.
=> scripts: Add data collection script

.pullapprove.yml
Add the standard doc team config to the pullapprove config file.
Fixes #99.
=> CI: Add doc team to pullapprove config

data/kata-collect-data.sh.in
Implement review feedback from @devimc on #93.
- Look for other runtime packages (Clear Containers and `runv`-based) in data collection script.
- Fix bug where collect script was looking for Clear Containers images rather than Kata Containers ones.
- Don't hard-code the architecture when looking for hypervisor packages.
Fixes #101.
=> Update data collection script based on review feedback

virtcontainers/device.go, virtcontainers/pod.go, virtcontainers/pod_test.go, virtcontainers/qemu.go
With this patch VFIO devices are hot plugged in the VM, that means
no more cold plug in kata containers.
fixes #85
=> virtcontainers: vfio: add support for hot plugging VFIO devices

versions.yaml
Add a YAML format database that is the equivalent of the Clear
Containers `versions.txt` file [1].
The file defines the versions of important non-golang dependencies used
by this and other Kata repositories particularly for testing and packaging.
Defining all version details centrally in this file avoids duplication
and "bitrot" when versions need to be changed.
[1] - https://github.com/clearcontainers/runtime/blob/master/versions.txt
Fixes #11.
=> versions: Add versions database

Gopkg.lock, Gopkg.toml, Makefile, cli/config.go, cli/config/configuration.toml.in, cli/config_test.go, cli/create.go, cli/create_test.go, cli/kata-env.go, vendor/github.com/intel/govmm/qemu/qemu.go, virtcontainers/asset.go, virtcontainers/hypervisor.go, virtcontainers/pkg/annotations/annotations.go, virtcontainers/pkg/oci/utils.go, virtcontainers/pod.go, virtcontainers/qemu.go, virtcontainers/qemu_amd64.go, virtcontainers/qemu_amd64_test.go, virtcontainers/qemu_arch_base.go, virtcontainers/qemu_arm64.go, virtcontainers/qemu_test.go, virtcontainers/virtcontainers_test.go
If an initrd image is configured in HypervisorConfig or passed in by annotations, append it to qemu command line arguments so that we boot the guest OS with the specified initrd image rather than a rootfs disk image.
A sample qemu command line:
> -name pod-test9 -uuid 9fc4a0e0-52a3-4e1c-b562-14b5c197dd2b -machine pc,accel=kvm,kernel_irqchip,nvdimm -cpu host,pmu=off -qmp unix:/run/virtcontainers/pods/test9/mon-9fc4a0e0-52a3-4e1c-b562-14b5c197dd2b,server,nowait -qmp unix:/run/virtcontainers/pods/test9/ctl-9fc4a0e0-52a3-4e1c-b562-14b5c197dd2b,server,nowait -m 2048M,slots=2,maxmem=4720M -device virtio-serial-pci,disable-modern=true,id=serial0 -device virtconsole,chardev=charconsole0,id=console0 -chardev socket,id=charconsole0,path=/run/virtcontainers/pods/test9/console.sock,server,nowait …
=> support to boot guest with an initrd image

virtcontainers/container.go, virtcontainers/kata_agent.go, virtcontainers/mount.go, virtcontainers/mount_test.go
Instead of ignoring containers based on their path, this commit
relies on the type of mount being "bind" to choose if this mount
should be ignored or not.
For instance, we have some use cases where k8s expects the path
"/dev/container-log" to be bind mounted inside the container, but
the code ignores it because it has the prefix "/dev" which is a
system prefix mount.
Fixes #116 #122
=> virtcontainers: Don't ignore container mounts based on their path

arch/amd64-options.mk, versions.yaml, virtcontainers/api_test.go, virtcontainers/documentation/api/1.0/api.md, virtcontainers/example_pod_run_test.go, virtcontainers/qemu_arch_base_test.go
This commit modifies version.yaml to now point to the qemu
2.11 stable version.
It modifies the default QEMU_CMD to be qemu-system-x86_64
instead of qemu-lite-system-x86_64.
And modifies virtcontainers unit tests to now point to the
correct QEMU_CMD.
Fixes: #118.
Depends-on: github.com/kata-containers/tests#182
=> qemu: Move to qemu 2.11

virtcontainers/api.go
In case a consumer of virtcontainers tries to start/stop a container,
or stop a pod, and for some reasons, this fails, virtcontainers always
tries to delete everything related to the container or the pod before
it returns the error.
The caller of the runtime is the one responsible for cleaning things
up if something goes wrong, that's why this cleanup call is never
needed.
A real example of that is the case of cc-runtime and CRI-O, where this
cleanup prevented CRI-O from retrieving proper state of the container
after the failure, leading to the inability to stop and remove the
container and the VM afterwards.
Fixes #87
=> virtcontainers: Do not rollback by deleting container or pod

cli/exec.go, cli/exec_test.go, virtcontainers/container.go, virtcontainers/container_test.go
If a container is not running, but created/ready instead, this means
a container process exists and that we can actually exec another
process inside this container. The container does not have to be
in running state.
Fixes #120
=> exec: Allow to exec a process on a ready container

cli/oci.go
Function getContainerInfo dosen't expand container id from prefix now
Fixes #139
=> cli: delete out-of-date comment

virtcontainers/api_test.go, virtcontainers/container.go, virtcontainers/container_test.go, virtcontainers/pkg/vcmock/container.go
Fix unit tests according with new changes introduced recently.
Use noopAgent in unit tests to add online fake resources.
Factorize configuration and hardware support for hotplugging block
devices into a single function and use that.
fixes #192
=> virtcontainers: fix unit tests

Gopkg.lock, Gopkg.toml, vendor/github.com/hashicorp/yamux/LICENSE, vendor/github.com/hashicorp/yamux/addr.go, vendor/github.com/hashicorp/yamux/const.go, vendor/github.com/hashicorp/yamux/mux.go, vendor/github.com/hashicorp/yamux/session.go, vendor/github.com/hashicorp/yamux/stream.go, vendor/github.com/hashicorp/yamux/util.go, vendor/github.com/kata-containers/agent/protocols/client/client.go, virtcontainers/api_test.go, virtcontainers/kata_agent.go, virtcontainers/kata_builtin_proxy.go, virtcontainers/kata_builtin_shim.go, virtcontainers/noop_agent_test.go, virtcontainers/pod.go, virtcontainers/pod_test.go, virtcontainers/podlist.go, virtcontainers/podlist_test.go, virtcontainers/proxy.go, virtcontainers/proxy_test.go, virtcontainers/shim.go, virtcontainers/shim_test.go, virtcontainers/virtcontainers_test.go
Add a new proxy type `KataProxyBuiltinType` and a new shim type `KataBuiltinShimType`. When they are specified, new proxy or shim processes will not be created. OTOH, the proxy and shim capabilities are provided by the kata runtime library directly.
For proxy, a yamux grpc dialer is used to create connections to the kata agent. And a goroutine is created to watch guest's console.
For shim, [sandbox relay APIs](https://github.com/kata-containers/documentation/blob/master/design/kata-api-design.md#sandbox-relay-api) will be provided. They are left to future PRs though.
Unfortunately due to limitation of the `yamux` library (at most one connection between client and server), this cannot be used with the kata runtime cli. So no cli change is included.
Depends-on: …
=> runtime: add builtin proxy and shim capability

virtcontainers/container.go
All bind mounts are now passed to the guest with 9p.
We need to exclude /dev/shm, as this is passed as a bind mount
in the spec. We handle /dev/shm in the guest by allocating
memory for it on the guest side. Passing /dev/shm as a 9p mount
was causing it to be mounted twice.
Fixes #190
=> virtcontainers: Do not pass /dev/shm as 9p mount

virtcontainers/container.go, virtcontainers/hyperstart_agent.go, virtcontainers/kata_agent.go, virtcontainers/mount.go
Check if a volume passed to the container with -v is a block device
file, and if so pass the block device by hotplugging it to the VM
instead of passing this as a 9pfs volume. This would give us
better performance.
Fixes #137
=> volumes: Attach volumes that are block device files as block devices

versions.yaml
This change uses latest commit from CRI-O
1.9 branch instead of using latest 1.9 release.
This will allow us to unskip a test from the
CRI-O ctr.bats test file, since it contains a race
condition fix.
Fixes: #182.
=> versions: Update CRI-O version

virtcontainers/kata_agent.go, virtcontainers/kata_agent_test.go
The runtime already hot added the number of vCPUs needed by each container,
in order to have a better control over those resources, CPU constraints
must be applied.
fixes #203
=> virtcontainers: kata_agent: apply CPU constraints

virtcontainers/kata_agent.go
Disable cpuset and cpumem constraints as this is not properly
supported yet.
If we add "cpuset_cpus" and "cpuset_mems" to the container.json,
kata-runtime failed to start, so we need to disable them.
Fixes: #221.
=> virtcontainers: Disable cpuset and cpumem

virtcontainers/api.go, virtcontainers/sandbox.go
After we rename pod to sandbox, still there are some codes left which
will cause some misunderstanding.Such as,`p` in short of `pod` left in
`sandbox.go`.So we need to channge it into `s` in short of `sandbox`.
Fixes:#230
Related: #200
Signed-off-by: Haomin Tsai <caihaomin@huawei.com>
=> runtime: fix codes misunderstanding after rename pod to sandbox

cli/config/configuration.toml.in
The config file is in TOML format which supports comments, so add the
license header to it.
Fixes #234.
=> config: Add SPDX license header to config file

virtcontainers/container.go, virtcontainers/mount.go, virtcontainers/mount_test.go
This reverts commit 08909b2213a23ab00a442a505f4b1a146e34b41b first.
It removes /dev from the system ignored mounts retaining /sys and /proc.
Regular files in /dev are treated separately, they are shared with container in the guest using 9p. Device nodes in /dev are ignored. One caveat is we handle block device files early on, these are passed to the guest using virtio-blk.
Fixes #219
=> Handle device nodes and regular files in /dev

virtcontainers/kata_agent.go
this patch is to honour docker `--cpuset-cpus` and
`--cpuset-mems` options.
fixes #221
=> virtcontainers: kata_agent: enable cpus and mem sets

Gopkg.lock, Gopkg.toml, vendor/github.com/intel/govmm/qemu/qemu.go, virtcontainers/bridge.go, virtcontainers/bridge_test.go, virtcontainers/qemu.go, virtcontainers/qemu_amd64.go, virtcontainers/qemu_amd64_test.go, virtcontainers/qemu_arch_base.go, virtcontainers/qemu_arch_base_test.go
This will allow to determine the PCI address of the device attached to the bridge within the guest.
=> Assign address to a pci bridge while appending it

virtcontainers/mount_test.go
Don't Attempt to create file below `/dev` when running as non-`root`.
Move the logic into a new `TestIsHostDeviceCreateFile` test and skip
unless `root.`
Fixes #242.
=> virtcontainers: Fix TestIsHostDevice test as non-root

versions.yaml
change from go1.10 to 1.9.2.
Our static checks and unit tests fail when using
go 1.10. Since we use go 1.9.2 to test in our CI,
reflect this version in versions.yaml
By doing this, we will be able to remove the hardcoded version
from the jenkins scripts and instead install golang using
`.ci/install_go.sh` from the tests repository. And when moving
to go1.10 using a PR, the CI will test that the static checks
and unit tests pass correctly.
Fixes: #254.
=> versions: change newest supported go version

cli/delete.go, cli/delete_test.go, cli/kill.go, cli/kill_test.go
This commit tries to address uses cases where the caller of the
runtime expects a kill to stop the container representing the pod,
meaning in our case the end of the VM.
This leads to some rework of the delete command since we want a
delete --force to always work, even if the container/pod has been
killed before.
Fixes #197
=> cli: Don't wait for OCI delete to stop the sandbox

Gopkg.lock, vendor/github.com/dlespiau/covertool/pkg/cover/cover.go, versions.yaml, virtcontainers/cc_proxy_test.go
- move to golang  1.10
- Fix issues needed move to go 1.10
=> versions: move to go 1.10

virtcontainers/api.go, virtcontainers/hook.go, virtcontainers/hook_test.go, virtcontainers/sandbox.go
We currently just send the pid in the state. While OCI specifies
a few other fields as well, this commit just adds the bundle path
and the container id to the state. This should fix the errors seen
with hooks that rely on the bundle path.
Other fields like running "state" string have been left out. As this
would need sending the strings that OCI recognises. Hooks have been
implemented in virtcontainers and sending the state string would
require calling into OCI specific code in virtcontainers.
The bundle path again is OCI specific, but this can be accessed
using annotations. Hooks really need to be moved to the cli as they
are OCI specific. This however needs network hotplug to be implemented
first so that the hooks can be called from the cli after the
VM has been created.
Fixes #271 …
=> hooks: Send the bundle path in the state that is sent with hooks

virtcontainers/container.go
Here is an interesting case I have been debugging. I was trying to
understand why a "kubeadm reset" was not working for kata-runtime
compared to runc. In this case, the only pod started with Kata is
the kube-dns pod. For some reasons, when this pod is stopped and
removed, its containers receive some signals, 2 of them being SIGTERM
signals, which seems the way to properly stop them, but the third
container receives a SIGCONT. Obviously, nothing happens in this
case, but apparently CRI-O considers this should be the end of the
container and after a few seconds, it kills the container process
(being the shim in Kata case). Because it is using a SIGKILL, the
signal does not get forwarded to the agent because the shim itself
is killed right away. After this happened, CRI-O calls into …
=> virtcontainers: Properly remove the container when shim gets killed

cli/create.go, cli/create_test.go, cli/delete.go, cli/delete_test.go, cli/exec_test.go, cli/kill_test.go, cli/main_test.go, cli/oci.go, cli/oci_test.go, cli/pause_test.go, cli/ps_test.go, cli/run_test.go, cli/start_test.go, cli/state_test.go
This commit will allow for better performance regarding the time spent
to retrieve the sandbox ID related to a container ID.
The way it works is by relying on a specific mapping between container
IDs and sanbox IDs, meaning it allows to retrieve directly the sandbox
ID related to a container ID from the CLI. This lowers complexity from
O(n²) to O(1), because we don't need to call into ListPod() which was
parsing all the pods and all the containers on the system everytime
the CLI need to retrieve this mapping.
This commit also updates the whole unit tests as a consequence. This
is involving most of them since they were all relying on ListPod()
before.
Fixes #212
=> cli: Optimize container research

data/kata-collect-data.sh.in
- Changed the collect script to display the contents of the osbuilder metadata file which provides details of the image.
- The collect script is now able to extract the osbuilder metadata from an initrd image.
Fixes #237.
=> Tidy up and add support for initrd and osbuilder metadata file

virtcontainers/agent.go, virtcontainers/hyperstart_agent.go, virtcontainers/interfaces.go, virtcontainers/kata_agent.go, virtcontainers/kata_agent_test.go, virtcontainers/monitor.go, virtcontainers/monitor_test.go, virtcontainers/noop_agent.go, virtcontainers/pkg/vcmock/sandbox.go, virtcontainers/sandbox.go, virtcontainers/sandbox_test.go
As described in [the API design](kata-containers/documentation/blob/master/design/kata-api-design.md), we need to support `Sandbox.Monitor()` operation that returns an error channel for the caller to watch on sandbox fetal errors.
Fixes #251
=> API: support sandbox monitor operation

Makefile
"make install" fails on a clean working directory:
$ make install
install: cannot stat ‘data/kata-collect-data.sh’: No such file or directory
This happens because install and install-scripts do not depend on the
runtime.  Make doesn't know it needs to build the runtime before it can
be installed.
Add the missing dependencies to the install targets so that "make
install" works on a clean working directory and rebuilds when source
files have been modified.
Note that SCRIPTS contains the generated kata-collect-data.sh script.
That file needs to be generated before it can be installed, so make
SCRIPTS a dependency of install-scripts.
Fixes: #283
Signed-off-by: Stefan Hajnoczi <stefanha@redhat.com>
=> Makefile: add missing dependencies to install targets

virtcontainers/agent.go, virtcontainers/container.go, virtcontainers/container_test.go, virtcontainers/hyperstart_agent.go, virtcontainers/interfaces.go, virtcontainers/iostream.go, virtcontainers/iostream_test.go, virtcontainers/kata_agent.go, virtcontainers/kata_agent_test.go, virtcontainers/noop_agent.go, virtcontainers/pkg/vcmock/sandbox.go, virtcontainers/sandbox.go, virtcontainers/sandbox_test.go
As described in [the API design](kata-containers/documentation/blob/master/design/kata-api-design.md), we need to support `sandbox.WaitProcess()`, `sandbox.WinsizeProcess()`, `sandbox.SignalProcess()` and `sandbox.IOStream()` operations.
=> add sandbox process operation relay API support

virtcontainers/hyperstart_agent.go, virtcontainers/hypervisor.go, virtcontainers/kata_agent.go, virtcontainers/kata_builtin_proxy.go, virtcontainers/kata_proxy.go, virtcontainers/mock_hypervisor.go, virtcontainers/mock_hypervisor_test.go, virtcontainers/qemu.go, virtcontainers/qemu_test.go, virtcontainers/utils/utils.go, virtcontainers/utils/utils_test.go, virtcontainers/virtcontainers_test.go
A Unix domain socket is limited to 107 usable bytes on Linux. However,
not all code creating socket paths was checking for this limits.
Created a new `buildSocketPath()` function (with tests) to encapsulate
the logic and updated all code creating sockets to use it.
Fixes #268.
=> socket: Enforce socket length

cli/exec_test.go, virtcontainers/pkg/oci/utils.go, virtcontainers/pkg/oci/utils_test.go
An empty string for an environment variable simply means that the
variable is unset. Do not error out if the env value is empty.
Fixes #288
=> oci: Allow environment values to be empty

virtcontainers/filesystem.go
Reduce the virtcontainers prefix path to avoid hitting the 107 byte
Unix domain socket path limit.
Related #268.
Fixes #290.
=> virtcontainers: Reduce path lengths

versions.yaml
=> versions: Move to k8s 1.10

Makefile, cli/config.go, cli/config/configuration.toml.in, cli/config_test.go, virtcontainers/container.go, virtcontainers/container_test.go, virtcontainers/hyperstart_agent.go, virtcontainers/hypervisor.go, virtcontainers/mock_hypervisor.go, virtcontainers/pkg/oci/utils.go, virtcontainers/qemu.go, virtcontainers/qemu_amd64.go, virtcontainers/qemu_arch_base.go, virtcontainers/qemu_arch_base_test.go, virtcontainers/qemu_arm64.go, virtcontainers/qemu_test.go, virtcontainers/sandbox.go
There is a relation between the maximum number of vCPUs and the
memory footprint, if QEMU maxcpus option and kernel nr_cpus
cmdline argument are big, then memory footprint is big, this
issue only occurs if CPU hotplug support is enabled in the kernel,
might be because of kernel needs to allocate resources to watch all
sockets waiting for a CPU to be connected (ACPI event).
For example
```
+---------------+-------------------------+
|               | Memory Footprint (KB)   |
+---------------+-------------------------+
| NR_CPUS=240   | 186501                  |
+---------------+-------------------------+
| NR_CPUS=8     | 110684                  |
+---------------+-------------------------+
```
In order to do not affect CPU hotplug and allow to users to have containers
with the same …
=> virtcontainers/qemu: reduce memory footprint

versions.yaml
Our tests CI is dependent on `gometalinter` which are run by the static
checks script. However, `gometalinter` changes a lot
and when it does, it breaks (what were) valid PRs.
Add `gometalinter` to the versions database so we can pin the version
we use to a known good one.
Fixes #304.
=> versions: Add gometalinter to versions database

arch/amd64-options.mk, versions.yaml
Update the runtime to use qemu-lite by default. After a
build this will be observed as the default in configuration.toml.
Fixes: #293
=> build: default to using qemu-lite-x86_64

README.md
Added links to the installation guides, as well as a
pointer to the kata containers architecutre document.
Fixes: #315
=> docs: update README to include links to user guides

virtcontainers/api.go, virtcontainers/pkg/vcmock/sandbox.go, virtcontainers/sandbox.go
Still there are some codes left which
will cause some misunderstanding
Change `p` in short of `pod` into `s` or `sandbox`
Fixes: #325
Signed-off-by: Haomin <caihaomin@huawei.com>
=> virtcontainers: fix codes misunderstanding in virtcontainers

cli/config.go
Since the runtime can load its configuration from multiple locations,
add a log field to show which location was used.
Change log level from Debug to Info as this is generally useful
information.
Fixes #335.
=> config: Show which config file loaded

virtcontainers/api.go
When a container is updated, those modifications are stored, to
avoid race conditions with other operations, a RW lock should be used.
fixes #346
=> virtcontainers/api: use RW lock to update containers

cli/kill.go, cli/kill_test.go, cli/pause.go, cli/pause_test.go, virtcontainers/agent.go, virtcontainers/api.go, virtcontainers/api_test.go, virtcontainers/container.go, virtcontainers/container_test.go, virtcontainers/hyperstart_agent.go, virtcontainers/implementation.go, virtcontainers/interfaces.go, virtcontainers/kata_agent.go, virtcontainers/noop_agent.go, virtcontainers/noop_agent_test.go, virtcontainers/pkg/oci/utils.go, virtcontainers/pkg/oci/utils_test.go, virtcontainers/pkg/vcmock/mock.go, virtcontainers/pkg/vcmock/mock_test.go, virtcontainers/pkg/vcmock/types.go
Instead of pausing the sanbox, this patch just pauses the container
allowing the communication with the agent. The communication with the agent
should be still possible even if all containers are paused, because of we don't
know when a new container can be created in the same sandbox.
Depends-on: github.com/kata-containers/agent#246
fixes #317
=> Fix pause-remove container

cli/main_test.go
runCommand([]string{"docker", "image", "inspect", testDockerImage}) will always fail, and it lead testcase pull busybox every time whether it exists or not.
Fixes #347
Signed-off-by: y00316549 <yangshukui@huawei.com>
=> unittest: tiny fix for incorrect parameters

virtcontainers/qemu_ppc64le.go
=> virtcontainers: Remove unnecessary kernel parameters for ppc64le

cli/main_test.go, virtcontainers/pkg/oci/utils.go, virtcontainers/pkg/oci/utils_test.go
In old specs.Spec, Capabilities is [] string, but we don't use CompatOCISpec  for compatibility in kataAgent/createContainer, it lead to docker-1.11.2 failed to start kata-container, this pr will fix this.
before this pr,
```
[root@localhost linux]# docker run --rm -it --runtime kata-runtime busybox sh
docker: Error response from daemon: oci runtime error: json: cannot unmarshal array into Go struct field Process.capabilities of type specs.LinuxCapabilities.
```
after this pr
```
[root@localhost linux]# docker run --rm -it --runtime kata-runtime busybox sh
/ # exit
```
=>  make sure kataAgent/createContainer can decode old specs.Spec

virtcontainers/qemu_ppc64le.go
=> ppc64le: Restrict maxmem to avoid HTAB allocation failure

cli/kata-check_amd64.go, cli/kata-check_arm64.go, cli/kata-check_ppc64le.go, cli/utils.go
The CPUinfo need to be refined in Arm architecture, because the
vendor and model of CPU may refer to different meaning in Arm architecture.
Besides, relevant contents extracted from /proc/cpuinfo may need to be
normalized for human-readability.
Fixes: #368
Signed-off-by: Wei Chen <wei.chen@arm.com>
=> cpuinfo/arm64: Refine CPUInfo in Arm64

README.md, virtcontainers/README.md, virtcontainers/documentation/api/1.0/api.md
Correct the document URLs which have gone stale.
The virtcontainers build status links have been moved to the top-level
README.
Fixes #376.
=> docs: Fix invalid URLs

virtcontainers/kata_agent.go, virtcontainers/kata_agent_test.go, virtcontainers/mount.go, virtcontainers/pkg/oci/utils.go, virtcontainers/pkg/oci/utils_test.go, virtcontainers/sandbox.go
This commit checks the size of "/dev/shm" for the sandbox container
which is then used to create the shared memory inside the guest.
kata agent then uses this size to set up a sandbox level shm
storage. The containers then simply bind mount this sandbox level
shm.
With this, we will now be able to support docker --shm-size option
as well have a shared shm within containers in a pod, since they are
supposed to be in the same IPC namespace.
Fixed #356
=> shm: Create shared /dev/shm

virtcontainers/cni.go, virtcontainers/cnm.go, virtcontainers/network.go, virtcontainers/network_test.go, virtcontainers/noop_network.go, virtcontainers/sandbox.go, virtcontainers/utils/virtcontainers-setup.sh
In case of physical network interfaces, we explicitly
pass through them to the VM. We need to bind them back to
the host driver when the sandbox is stopped, irrespective if
the network namespace has been created by virtcontainers or not.
Fixes #384
=> network: Always bind back physical interfaces

versions.yaml
The cni-plugins commit will be used to build that specific
version on the CI, instead of using master.
Fixes #407.
=> Versions: Add CNI plugins version

README.md
It pointed to how to enable logs, which is only a small portion of the
debug options for Kata  Containers.  Let's instead point to the
troubleshooting section, which includes pointers to adding logs and to
debug the guest vm.
=> docs: update debug runtime link

virtcontainers/agent.go, virtcontainers/container.go, virtcontainers/hyperstart_agent.go, virtcontainers/kata_agent.go, virtcontainers/noop_agent.go, virtcontainers/sandbox.go
Before this patch shared dir will reamin when sandox
has already removed.
Do clean up shared dirs after all mounts are umounted
Fix: #291
Signed-off-by: Haomin <caihaomin@huawei.com>
=> virtcontainers : fix shared dir resource remaining

cli/create.go, cli/run.go
This commit add a no-pivot flag (just a warning tip) in kata-runtime create and run cmd.
Fixes: #409 , #134
Signed-off-by: wenqi wang wangwenqi01@baidu.com
=> cli: add no-pivot flag to be compatible with docker in ramdisk

versions.yaml
update from v17.12 to v18.03.
18.03 is the version installed in the CI VMs
and when using v17.12 some hotplug cpu tests
fail. then we need to make v18.03 our official
supported version.
Fixes: #418.
=> versions: update supported docker version

virtcontainers/kata_agent.go, virtcontainers/sandbox.go
So that we let callers decide if kata-agent should let all containers in
a sandbox share the same pid namespace.
Fixes: #426
Signed-off-by: Peng Tao <bergwolf@gmail.com>
=> sandbox: expose share sandbox pidns setting

virtcontainers/qemu.go, virtcontainers/sandbox.go
We only need one qmp channel and it is qemu internal detail thus
sandbox.go does not need to be aware of it.
This was part of #303 and but does not really relate to vm factory so I take it out.
=> qemu: clean up qmp channel

cli/kata-check_amd64_test.go, cli/kata-check_arm64.go, cli/kata-check_arm64_test.go, cli/kata-check_data_arm64_test.go, cli/kata-check_ppc64le_test.go, cli/kata-check_test.go, cli/kata-env_amd64_test.go, cli/kata-env_arm64_test.go, cli/kata-env_ppc64le_test.go, cli/kata-env_test.go, cli/utils_test.go
There were missing test cases in Arm64 for platform-dependent kata-check and kata-env, leading to 'make test' failure under kata-containers/runtime
Fixes: #403
=> test: supplement test cases for kata-check and kata-env in Arm64

virtcontainers/kata_agent.go
If we send multiple grpcs at once when a client is being created, we end up
creating multiple connections to the agent and it breaks when using builtin
proxy since only one connection is allowed.
Fixes: #431
=> kata_agent: fix connection race

Makefile, data/kata-collect-data.sh.in
make install DESTDIR=/tmp/dest/
Before:
```
$tree /tmp/dest/
/tmp/dest/
└── usr
├── bin
│   └── kata-collect-data.sh
└── share
└── defaults
└── kata-containers
└── configuration.toml
```
Now:
```
$tree /tmp/dest/
/tmp/dest/
└── usr
├── local
│   └── bin
│       ├── kata-collect-data.sh
│       └── kata-runtime
└── share
├── bash-completion
│   └── completions
│       └── kata-runtime
└── defaults
└── kata-containers
└── configuration.toml
```
New summary:
```
• Summary:
destination install path (DESTDIR): /tmp/dest/
binary installation path (BINDIR) : /usr/local/bin
binaries to install               :
- kata-runtime
- data/kata-collect-data.sh
config to install (CONFIG)      : cli/config/configuration.toml
install path (CONFIG_PATH): …
```
=> [RFC] makefile: honor DESTDIR flag.

virtcontainers/network.go
Use pointer here since api.VhostUserDevice interface is implemented
by VhostUserNetDevice pointer.
Fixes #446
=> network: Use pointer for VhostUserNetDevice for Attach

versions.yaml
Update to kernel to get latest fixes.
Depends-on: github.com/kata-containers/agent#278
Fixes: #420
=> versions: Update kernel to version 4.14.51

cli/create.go, cli/delete.go, cli/events.go, cli/exec.go, cli/kill.go, cli/pause.go, cli/ps.go, cli/start.go, cli/state.go, cli/update.go
Adding cid+sid fields to the log entries generated by most of the CLI
commands will make debugging across the system easier.
Fixes #452.
=> logging: Add containerID and sandboxID to all log calls

virtcontainers/agent.go, virtcontainers/api.go, virtcontainers/cc_proxy.go, virtcontainers/hyperstart_agent.go, virtcontainers/kata_agent.go, virtcontainers/kata_builtin_proxy.go, virtcontainers/kata_proxy.go, virtcontainers/no_proxy.go, virtcontainers/noop_agent.go, virtcontainers/noop_proxy.go, virtcontainers/proxy.go, virtcontainers/sandbox.go
When do sandbox release, the kataBuiltInProxy will
be closed, and it will stop the watch of vm's console;
Thus it needs to restart the proxy to monitor the vm
console once to restore the sandbox.
Fixes: #441
=> api: To watch the vm console in FetchSandbox api

cli/create.go, cli/delete.go, cli/events.go, cli/exec.go, cli/kill.go, cli/main.go, cli/pause.go, cli/ps.go, cli/start.go, cli/state.go
Once `containerID` and `sandboxID` fields are available, re-register the logger with the external packages to ensure they too display these important fields.
Fixes #467.
=> logging: Reset external loggers when cid+sid available

virtcontainers/qemu.go
Add a kernel command-line option that the agent can read to determine
the sandbox ID of the VM. It can use this to create a `sandbox=` log
field for improved log analysis.
Fixes #465.
=> qemu: Pass sandboxID to agent for logging purposes

cli/main.go
Add the runtime CLI command name to the virtcontainers logger so that it
is clear when reading virtcontainers log entries which runtime command
they refer to.
Fixes #448.
=> main: Pass runtime CLI command to vc logger

versions.yaml
default image-type(aka clearlinux) couldn't work in aarch64, so we add specifc image-type to avoid jenkins set-up failure.
Fixes: #461
=> ci: add specfic image-type for aarch64

Gopkg.lock, Gopkg.toml, vendor/github.com/docker/go-units/duration.go, vendor/github.com/docker/go-units/ulimit.go, vendor/github.com/hashicorp/yamux/session.go, vendor/github.com/hashicorp/yamux/stream.go, vendor/github.com/hashicorp/yamux/util.go, vendor/github.com/intel/govmm/qemu/qemu.go, vendor/github.com/intel/govmm/qemu/qmp.go, virtcontainers/hypervisor.go, virtcontainers/qemu.go, virtcontainers/qemu_test.go
As discussed in #303, I'm splitting the memory hotplug part from the vm factory PR to get more eyes on it. The govmm part of change is already merged so we just need to change qemu to call the APIs properly.
However, because this is just part of the vm factory PR, there is no actual caller for the internal memory device hotplug API yet. That said, I did test it roughly with following hack and saw qmp hotplug commands succeed:
```
diff --git a/virtcontainers/sandbox.go b/virtcontainers/sandbox.go
index 87f8eda..6bba236 100644
--- a/virtcontainers/sandbox.go
+++ b/virtcontainers/sandbox.go
@@ -947,6 +947,14 @@ func (s *Sandbox) startVM() error {
s.Logger().Info("VM started")
+       // HACK: test memory hotplug
+       defer func() {
+               _, err := …
```
=> hypervisor/qemu: add memory hotplug support

virtcontainers/cc_proxy_test.go, virtcontainers/kata_proxy.go, virtcontainers/kata_proxy_test.go, virtcontainers/proxy_test.go
Add the `-sandbox` option when launching the proxy. This isn't strictly
required by the proxy, but is extremely useful for log analysis to allow
log entries to be matched to sandboxes as the proxy will add a
`sandbox` field in each log entry.
Fixes #463.
=> proxy: Pass sandbox to proxy

virtcontainers/qemu.go, virtcontainers/qemu_ppc64le.go
The "Failed to allocate HTAB of requested size,
try with smaller maxmem" error in ppc64le occurs
when maxmem allocated is very high. This got fixed
in qemu 2.10 and kernel 4.11. Hence put a maxmem
restriction of 32GB per kata-container if qemu
version less than 2.10
Fixes: #415
=> virtcontainers: Set ppc64le maxmem depending on qemu version

.ci/go-no-os-exit.sh, Makefile
The `go-no-os-exit` check seems to have bitrotted, and silently passes.
This looks to have come about when we moved the runtime code into the `cli` subdir.
Whilst there, we should get it to check virtcontainers as well.
=> Fix no exit static check

versions.yaml
Some test fixes were introduced into the 1.9 and 1.10 branches
of cri-o. These fixes will help us minimize random failures.
Fixes #481.
=> versions: Update CRI-O supported version

cli/kata-env.go, cli/kata-env_test.go
Having a direct JSON output for kata-env will help record
results in our CIs in some instances. Add that ability with
a kata-env command line extension.
Fixes: #474
=> kata-env: Add ability to output as JSON

virtcontainers/kata_agent.go
It helps tracking each request that is sent and we can match with the
one printed by kata-agent on the guest side to find out any stack
requests in the middle.
=> kata_agent: print request details

cli/delete_test.go, cli/exec_test.go, cli/run_test.go, cli/update_test.go
A number of tests were not cleaning up after themselves, which left
a bunch of files in the TMPDIR.
Ensure we remove all the tmpfiles and dirs we create.
=> Ensure tests clean their tempfiles

cli/create.go
When vm factory is enabled, create vm factory automatically
during creation.
Fixes: #504
=> cli: create vm factory if failed to load existing one

virtcontainers/api.go, virtcontainers/kata_agent.go, virtcontainers/sandbox.go
virtcontainers: process the case that kata-agent doesn't start in VM
If kata-agent process is not launched to run in VM, kata-runtime will exit because of timeout,
however kata-proxy and qemu process will still resident in host
Call Check grpc function to check whether grpc server is running in kata-agent process in VM,
if not and then do some rollback operation to stop kata-proxy and qemu processes
Fixes: #297
Signed-off-by: flyflypeng <jiangpengfei9@huawei.com>
=> virtcontainers: process the case that kata-agent doesn't start in VM

virtcontainers/filesystem_test.go, virtcontainers/sandbox.go, virtcontainers/sandbox_test.go
ContainerID is supposed to be unique within a sandbox. It is better to use
a map to describe containers of a sandbox.
Fixes: #502
=> sandbox: change container slice to a map

virtcontainers/sandbox.go
When createNetwork failed, cleanup the NetNs if it created.
Fixes: #508
=> virtconainers: rollback the NetNs when createNetwork failed

codecov.yml
Because codecov coverage regarding the patch is very inconsistent,
this commit introduces codecov.yml config file in order to disable
this check.
Fixes #511
=> codecov: Explicitly disable codecov/patch coverage

virtcontainers/kata_agent.go
In slow systems when run  multiples containers in parallel.  The start-up time
takes longer and when we do the initial gprc server check, we got a time-out
because is not ready.
This PR adds a better error message when this happens and increase the time-out
to 10 seconds.
Notice that this fix the CI but  we still need to find the route cause why
is taking longer and try to reduce this delay.
=> agent: Increase timeout for check request.

versions.yaml
Docker 18.06 was released last week, update our
supported docker to this new version.
Fixes: #510
=> versions: Update docker-ce to 18.06

cli/main.go, virtcontainers/factory/factory.go, virtcontainers/factory/factory_test.go
So that we actually use the same logger as other packages when being
invoked by CLI.
Fixes: #520
=> factory: add SetLogger API

cli/delete.go, cli/events.go, cli/exec.go, cli/kill.go, cli/pause.go, cli/ps.go, cli/start.go, cli/update.go, virtcontainers/api.go, virtcontainers/container.go, virtcontainers/device/api/interface.go, virtcontainers/hack/virtc/main.go, virtcontainers/implementation.go, virtcontainers/interfaces.go, virtcontainers/kata_agent.go, virtcontainers/network.go, virtcontainers/pkg/hyperstart/hyperstart.go, virtcontainers/pkg/oci/utils.go, virtcontainers/pkg/vcmock/mock.go, virtcontainers/pkg/vcmock/mock_test.go, virtcontainers/sandbox.go, virtcontainers/virtcontainers_test.go
Improve containerID and sandboxID logging by:
- Ensuring that `setExternalLoggers()` saves any previously-set log fields
(this required a `SetLogger()` API change).
- Calling `setExternalLoggers()` as early as possible, then again once new fields become available.
This is necessary to ensure that all virtcontainers functions atleast have access to the containerID for logging purposes.
PR also performs various log cleanup.
Fixes #519.
=> Ensure containerID and sandboxID fields logged as early as possible

Gopkg.lock, Gopkg.toml, cli/config.go, cli/config/configuration.toml.in, cli/config_test.go, cli/kata-env.go, vendor/github.com/intel/govmm/qemu/qemu.go, vendor/github.com/intel/govmm/qemu/qmp.go, virtcontainers/agent_test.go, virtcontainers/hypervisor.go, virtcontainers/kata_agent.go, virtcontainers/kata_agent_test.go, virtcontainers/kata_proxy.go, virtcontainers/no_proxy.go, virtcontainers/qemu.go, virtcontainers/qemu_arch_base.go, virtcontainers/qemu_test.go, virtcontainers/utils/utils.go, virtcontainers/utils/utils_linux.go, virtcontainers/utils/utils_linux_test.go, virtcontainers/utils/utils_test.go
This PR completes the support to use vsock and no proxy configuration.
In order to create add VSOCK support we added:
- coldplug support for VSOCK socket device.
- Implemented a way to find a context ID based in a random search.
A random  number  is generated between 3 and max `uint32` (4'294,967,295)
and uses it as context ID. The range is large enough to have a low collision probability. Using `ioctl` checks if the context ID is free, else find the immediate next free context ID.
- When the hypervisor option `use_vsock` is true the runtime will check for vsock support . If vsock is supported, not proxy will be used and the shims will connect to the VM using VSOCKS. This flag is true by default, so will use VSOCK when possible.
- The `kata-env` subcommand now shows information about if …
=> Use VSOCK when is available in the host.

virtcontainers/qemu.go, virtcontainers/qemu_test.go
So that if there is any remaining state, we do not let it interfere
with the new one. This should fix the occasional vm factory hang.
=> qemu: clear qmp state before wait for qemu process

virtcontainers/qemu.go, virtcontainers/qemu_test.go
Remove the `initcall_debug` boot option from the kernel command-line as
we don't need it any more and it generates a ton of boot messages that
may well be impacting performance.
Fixes #526.
=> kernel: Remove initcall_debug boot option

virtcontainers/qemu.go
To use the filepath.Join() instead of the simple
string append method to form the file path, otherwise
it will lose the "/" between the two parts.
Fixes #543.
Signed-off-by: Fupan Li <lifupan@gmail.com>
=> virtcontainers: fix the issue of cleanup the vm's path

cli/factory.go, cli/factory_test.go
It checks vm factory status and prints the result.
Fixes: #545
=> cli: support factory status command

virtcontainers/qemu.go
Right now we create it in `createsandbox` and it would
create the vm dir unnecessarily for fetchsandbox() and
it ends up leaving an empty vm dir behind even after
DeleteSandbox.
Fixes: #547
=> qemu: create vm directory before launching qemu

versions.yaml
Last week openshift origin v3.10.0 was released,
this PR updates our supported version from 3.9.0 to
3.10.0
This also updates the cri-o version that we use for
openshift, which is now cri-o 1.10.
Fixes: #552.
=> versions: update openshift to 3.10.0

virtcontainers/qemu_amd64.go, virtcontainers/qemu_arch_base.go
In order to start playing with the "virt" machine type for Kata,
we need this new machine type to be part of the list of supported
machines for qemu on x86 architecture.
Fixes #558
=> virtcontainers: qemu: x86: Support "virt" machine type

virtcontainers/qemu_ppc64le.go
nvdimm is fundamental to get rootfs approach
working for Kata Containers on ppc64le. It should
be added to the default qemu machine option list.
Fixes: #561
=> virtcontainers: ppc64le: Add nvdimm to defaultQemuMachineOption

virtcontainers/network.go, virtcontainers/network_test.go
Instead of continuing with the network setup, we should detect
if host network namespace was requested and error out early.
Fixes #499
=> network: Error out when host-networking is requested

Gopkg.lock
NOP update that simply updates the file format of the `dep` `Gopkg.lock`
file to the latest format.
Note: `dep ensure` run using `dep` at commit
https://github.com/golang/dep/commit/6b79ccc4052b44b52a424209e2a32682cc84c11c.
Fixes #573.
=> vendor: Update dep lock file for new format

versions.yaml
The commit for qemu needs to be updated to the tip
of the qemu-lite-2.11.0 branch. The qemu packages for
1.12.0 also contain the latest commit.
Fixes #582
=> versions: Update the commit for qemu-lite

virtcontainers/api.go, virtcontainers/container.go, virtcontainers/device/api/interface.go, virtcontainers/device/manager/manager.go, virtcontainers/implementation.go, virtcontainers/interfaces.go, virtcontainers/pkg/vcmock/mock.go, virtcontainers/pkg/vcmock/sandbox.go, virtcontainers/pkg/vcmock/types.go, virtcontainers/sandbox.go, virtcontainers/sandbox_test.go
Fixes #50
Add new interface sandbox.AddDevice, then for Frakti use case, a device
can be attached to sandbox before container is created.
=> devices: add interface "sandbox.AddDevice"

cli/kata-env.go, cli/kata-env_test.go
`kata-env` did not include the path to the runtime exe itself.
Add that into the Runtime section.
Fixes: #577
=> cli: kata-env: add runtime path to output

.travis.yml
Bump the CI travis's go to 1.10 to meet
the building kata shim v2 for containerd.
Fixes: 575
=> CI: bump the CI travis's go to 1.10

cli/kata-env.go, cli/kata-env_test.go
Add a new field in `HostInfo` structure to show if vsocks are
supported in the host.
fixes #589
=> cli: kata-env: show if vsocks are supported

virtcontainers/api_test.go, virtcontainers/documentation/api/1.0/api.md, virtcontainers/hack/virtc/main.go, virtcontainers/network.go, virtcontainers/pkg/oci/utils.go, virtcontainers/pkg/oci/utils_test.go
Remove unsed variable, the variable is set just in one place, and
never is used again.
Fixes: #603
=> vc: Remove unused variable NumInterfaces

virtcontainers/network.go
When creating a device structure to be added to the hypervisor, make
sure that the device includes the vhost-user type.  In particular,
for network devices, specific it is VhostUserNet
Fixes: #601
=> network: fix vhost-user net creation

Gopkg.lock, Gopkg.toml, vendor/github.com/containernetworking/cni/LICENSE, vendor/github.com/containernetworking/cni/pkg/types/args.go, vendor/github.com/containernetworking/cni/pkg/types/types.go, vendor/github.com/kata-containers/agent/protocols/client/client.go
Increase dial timeout to fix context deadline exceeded when
using vsocks
Shortlog:
93fe84e protocols: increase dial timeout
730b977 client: bypass grpc dialer backoff strategy
41c09c2 agent: enable memory hierarchical account
4f70b1c channel: remove unused functions
f6486e7 channel: support communication channel hotplug
28afabb release: Kata Containers 1.2.0
fixes #576
=> vendor: update kata agent

Makefile, cli/config.go, cli/config/configuration.toml.in, cli/config_test.go, cli/kata-env_test.go, virtcontainers/hypervisor.go, virtcontainers/qemu.go
We need this configuration due to a limitation in seabios
firmware in handling hotplug for PCI devices with large BARS.
Long term, this needs to be fixed in the firmware.
Fixes #594
=> vfio: Add configuration to support VFIO hotplug on root bus

virtcontainers/qemu.go
The QMP shutdown is taken care of by the sandbox release, through a
call to hypervisor.disconnect(). By shutting down the QMP at the qemu
level directly, we are creating some unrecoverable errors by trying to
close an already closed channel.
This patch simply removes the faulty code, following the same design
other hotplug functions are designed.
Fixes #627
=> virtcontainers: qemu: Don't shutdown QMP from hotplug

virtcontainers/kata_agent.go, virtcontainers/kata_agent_test.go, virtcontainers/network.go, virtcontainers/network_test.go
The specific agent implementation kata_agent was defining a very
useful generic function that is now moved to the global file
network.go.
Fixes #629
=> virtcontainers: kata_agent: Move out a generic function

Gopkg.lock, Gopkg.toml, vendor/github.com/intel/govmm/qemu/qemu.go, vendor/github.com/intel/govmm/qemu/qmp.go, virtcontainers/qemu.go
With qemu 2.10, a write lock was added for qcow images that
prevents the same image to be passed more than once.
This can be over-ridden using the --share-rw option which is
desired for raw images.
This solves an issue with running Kata with devicemapper
using the privileged mode as in this case all devices on the host
are passed to the container using the block device associated
with the rootfs, causing it to be passed twice to qemu.
Fixes #606
=> Pass qemu --share-rw option for hotplugging disks

Gopkg.lock, Gopkg.toml, vendor/github.com/grpc-ecosystem/grpc-opentracing/LICENSE, vendor/github.com/grpc-ecosystem/grpc-opentracing/PATENTS, vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc/client.go, vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc/errors.go, vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc/options.go, vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc/package.go, vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc/server.go, vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc/shared.go, vendor/github.com/kata-containers/agent/protocols/client/client.go, virtcontainers/kata_agent.go
Update the agent vendoring for the new `NewAgentClient()` API - the
agent client code will enable gRPC tracing when passed a context
containing an opentracing span.
Agent client code changes:
6d26d61 client: Add context parameter and enable tracing support
Fixes #640.
=> vendor: Update kata agent for gRPC tracing

virtcontainers/kata_builtin_proxy.go
So daemons such as containerd shimv2 can still see it.
Fixes: #647
=> builtin-proxy: print guest console output to logger

virtcontainers/kata_agent.go, virtcontainers/kata_agent_test.go
Apply all supported memory constraints to the contrainer
inside the virtual machine.
fixes #653
=> virtcontainers: Apply memory constraints

cli/config.go, cli/kata-env.go, cli/kata-env_test.go, virtcontainers/network.go, virtcontainers/network_test.go, virtcontainers/pkg/cni/OWNERS, virtcontainers/qemu_ppc64le.go
Walked through all patches on master from HEAD (8bbd9b5) to 1.2.0 , and cherrypicked the relevant ones.  Analysis is as follows:
```
1.2.1 | * ee1ea36 network: fix vhost-user net creation
1.2.1 | * | 161e3a7 vc: Remove unused variable NumInterfaces
1.2.1 | * | 88d79f3 cli: kata-env: show if vsocks are supported
NO * |   26f3107 Merge pull request #287 from caoruidong/hotplug
| * | 7beb309 test: add UTs for network hotplug
| * | 72df219 cli: add network commands
| * | 1a17200 virtcontainers: add sandbox hotplug network API
| * | 6666426 vendor: update govmm and agent changes
NO * | |   b473dc4 Merge pull request #579 from lifupan/master
| * | | 4850579 CI: bump the CI travis's go to 1.10
1.2.1 | * | | 8b69c75 cli: kata-env: add runtime path to output
NO * | |   cd514b6 Merge pull request …
```
=> Stable 1.2.1 candidate

cli/kata-check_amd64_test.go, cli/kata-check_arm64_test.go, cli/kata-check_generic_test.go, cli/kata-check_ppc64le_test.go, cli/kata-env.go, cli/kata-env_arm64_test.go, cli/kata-env_generic_test.go, cli/kata-env_ppc64le_test.go
Fix nasty bug which resulted in `kata-env` showing `VMContainerCapable = true` even on amd64 systems without virtualisation support (thankfully `kata-check` still showed the correct results).
Added arch-specific tests to avoid any possibility of regression.
Fixes #660.
=> kata-env: Fix amd64 VM container capable check

virtcontainers/kata_agent.go, virtcontainers/kata_agent_test.go
Apply devices constraints to the container in the virtual machine
fixes #656
=> virtcontainers: apply devices constraints

virtcontainers/agent.go, virtcontainers/hyperstart_agent.go, virtcontainers/noop_agent.go
Fixes #638
Latest kata-runtime can't build with golang 1.8.3, fix it for backward compatibility.
=> build: fix breaking 1.8.3 build

virtcontainers/qemu_arch_base.go
drivers package is already removed from this file.
fixes #674
=> virtcontainers: delete out-of-date TODO

Gopkg.lock, Gopkg.toml, vendor/github.com/intel/govmm/qemu/qmp.go, virtcontainers/qemu.go
govmm has ExecuteBlockdevAdd() function and ExecuteBlockdevDel() function
doesn't compatible with qemu 2.8,because blockdev-add and x-blockdev-del usages
are different between qemu 2.7 and qemu 2.8
shortlog:
ce070d1 govmm: modify govmm to be compatible with qemu 2.8
0286ff9 qemu/qmp: support hotplug a nic whose qdisc is mq
8515ae4 qmp: Remind users that you must first call ExecuteQMPCapabilities()
21504d3 qemu/qmp: Add netdev_add with chardev support
ed34f61 Add some negative test cases for qmp.go
17cacc7 Add negative test cases for qemu.go
fixes: #637
Signed-off-by: flyflypeng <jiangpengfei9@huawei.com>
=> vendor: update govmm to be compatible with qemu 2.8

virtcontainers/kata_agent.go, virtcontainers/kata_agent_test.go
Due to issue https://github.com/kata-containers/runtime/issues/677
commit 137769a694136ef744fcb22ba389910fe1c1d951 must be reverted
This reverts commit 137769a694136ef744fcb22ba389910fe1c1d951.
fixes #685
=> virtcontainers: revert apply devices constraints

virtcontainers/container.go
RemoveContainer is called right after SignalProcess(SIGKILL), the container
process might be still running and container Destroy() will fail, thus it's better
to wait on this process exited before to issue RemoveContainer.
Fixes: #690
=> virtcontainers: wait until process exited before RemoveContainer

virtcontainers/default_network.go, virtcontainers/sandbox.go
For vm factory, we also need netns to be set otherwise we fail to
create new VMs in `s.network.run`.
Fixes: #681
=> network: always assign sandbox networkNS

virtcontainers/qemu_arm64.go, virtcontainers/qemu_arm64_test.go
on aarch64, we support different gic interrupt controllers.
The maximum number of vCPUs depends on the GIC version, or on how many redistributors we can fit into the memory map.
Fixes: #584
Signed-off-by: Wei Chen <Wei.Chen@arm.com>
=> qemu: refactor maximum vcpus supported in aarch64

cli/config.go, cli/config_test.go, cli/kata-env_test.go, cli/utils.go, cli/utils_test.go
Add a heuristic to ensure the amount of memory allocated to the
hypervisor is bigger than the size of the image.
This catches simple configuration issues where `default_memory=` is set
to a smaller value than the size of either the `image=` or `initrd=`
files.
If the configured image type is `initrd`, fail but only warn in the
logs for `image` as although it seems a highly unlikely scenario, it is
permitted.
Update tests to ensure that created resources have `>0` bytes.
Fixes #636.
=> config: Detect if VM memory smaller than image

cli/config.go, cli/config_test.go
Sadly CI failed to catch the broken line due to the fact that it is introduced by a different
PR that passed w/o the naming PR.
```
./config.go:604:27: config.DefaultMemSz undefined (type virtcontainers.HypervisorConfig has no field or method DefaultMemSz)
Makefile:331: recipe for target '/golang/src/github.com/kata-containers/runtime/kata-runtime' failed
make: *** [/golang/src/github.com/kata-containers/runtime/kata-runtime] Error 2
```
Fixes: #709
=> cli: fix build

Gopkg.lock, Gopkg.toml, vendor/github.com/intel/govmm/qemu/qemu.go, vendor/github.com/intel/govmm/qemu/qmp.go, versions.yaml, virtcontainers/device/config/config.go, virtcontainers/qemu.go, virtcontainers/qemu_arch_base.go
Kata Containers does not provide good entropy. Enable a paravirtual rng device to provide a random number generator source.
Depens on: https://github.com/intel/govmm/pull/45
Fixes: #445
=> qemu: Add rng virtio device

virtcontainers/kata_agent.go
We do not support it yet. If we pass it to the agent, container creation
will fail.
Depends-on: github.com/kata-containers/runtime#710
Fixes: #711
=> kata_agent: disable cgroup namespace

virtcontainers/device/drivers/vfio.go
Adds per-device VFIO ids allowing IOMMU groups with
multiple devices to be passed to qemu.
Fixes #708
Signed-off-by: Edward Guzman <eguzman@nvidia.com>
=> devices: add per-device VFIO ids

virtcontainers/hypervisor.go, virtcontainers/mock_hypervisor.go, virtcontainers/network.go, virtcontainers/qemu.go
Instead of using a default queue size of 8 for Multiqueue virtio-net,
use the number of vCPUs on the guest as the queue size.
This is the recommended approach for setting up the queue size.
This also shown better performance results.
=> Set the queue size for Multiqueue virtio-net as the number of vCPUs on the guest.

cli/config.go, cli/config_test.go, cli/kata-env.go, cli/kata-env_test.go, virtcontainers/pkg/oci/utils.go
The runtime and hypervisor `Debug` options were always showing as
`false` (although all debug options in `configuration.toml` were
correctly honoured).
Note: Also moved location of `FactoryConfig` in `RuntimeConfig` as the
`malign` linter was complaining:
```
virtcontainers/pkg/oci/utils.go:102:20:warning struct of size 408 could be 400 (maligned)
```
Fixes #724.
=> kata-env: Fix display of debug options

cli/config.go, cli/config_test.go
If neither initrd nor rootfs path is mentioned in
the configuration.toml file, then error out stating
the same
Fixes: #587
=> cli: Error out if initrd/rootfs not define in config file

Gopkg.lock, Gopkg.toml, cli/config.go, cli/config/configuration.toml.in, vendor/github.com/intel/govmm/qemu/qmp.go, virtcontainers/hypervisor.go, virtcontainers/network.go, virtcontainers/qemu.go, virtcontainers/qemu_arch_base.go
Add `disable_vhost_net` option to enable or disable the use of
vhost_net. Vhost_net can improve network performance.
Fixes: #169
=> cli: add configuration option to enable/disable vhost_net

versions.yaml
golang version 1.8.3 is old and the runtime cannot even be built with
it now it seems.
Since it is no longer considered a stable version [1], move to the
oldest official stable version (version 1.9.7).
Fixes #642.
[1] - https://golang.org/dl/
=> versions: Bump golang from 1.8.3 to 1.9.7

Gopkg.lock, Gopkg.toml, vendor/github.com/intel/govmm/qemu/image.go, vendor/github.com/intel/govmm/qemu/qemu.go, vendor/github.com/intel/govmm/qemu/qmp.go, virtcontainers/qemu.go
backport from commit-id: f841e89 in master branch to stable 1.2 branch
govmm has ExecuteBlockdevAdd() function and ExecuteBlockdevDel() function
doesn't compatible with qemu 2.8,because blockdev-add and x-blockdev-del usages
are different between qemu 2.7 and qemu 2.8
shortlog:
ce070d1 govmm: modify govmm to be compatible with qemu 2.8
0286ff9 qemu/qmp: support hotplug a nic whose qdisc is mq
8515ae4 qmp: Remind users that you must first call ExecuteQMPCapabilities()
21504d3 qemu/qmp: Add netdev_add with chardev support
ed34f61 Add some negative test cases for qmp.go
17cacc7 Add negative test cases for qemu.go
2706a07 qemu: Use the supplied context.Context for launching
e46092e qemu: Do not try and generate invalid RTC parameters
fcaf61d qemu/qmp: add vfio mediated device support
4461c45 …
=> vendor: update govmm to be compatible with qemu 2.8 to stabel 1.2 branch

data/kata-collect-data.sh.in
Add details of the KSM throttler to the output of the data collection
script. Look for both Kata and Clear Containers KSM throttler details.
Fixes #739.
=> scripts: Add throttler details to collect script

versions.yaml
Update the version that is used to test Kata.
```yaml
cri-containerd:
version: "v1.0.5"
meta:
containerd-version: "1.1.3"
```
Fixes: #748
=> versions: update containerd version

cli/create.go, cli/create_test.go, cli/main.go, cli/run.go, cli/run_test.go, virtcontainers/kata_agent.go, virtcontainers/kata_agent_test.go, virtcontainers/pkg/oci/utils.go, virtcontainers/pkg/oci/utils_test.go, virtcontainers/sandbox.go
Add support for cgroup driver systemd.
systemd cgroup is not applied in the VM since in some cases like initrd images
there is no systemd running and nobody can update a systemd cgroup using
systemctl.
fixes #596
=> cli: add systemd-cgroup option

virtcontainers/kata_agent.go, virtcontainers/kata_agent_test.go
It shouldn't set kataAgent.state.URL in its configure() method
for builtin kata proxy, otherwise the following check of whether
is it nil in startProxy() will return directly and failed to
start builtin proxy which will log the qemu's console.
Fixes: #756
=> virtcontainers: fix the issue of missing starting builtin proxy

Gopkg.lock, Gopkg.toml, vendor/github.com/intel/govmm/qemu/qmp.go, virtcontainers/device/config/config.go, virtcontainers/device/drivers/vfio.go, virtcontainers/device/drivers/vfio_test.go, virtcontainers/qemu.go
Enable GPU device support in kata runtime, including GVT-g and GVT-d.
GVT-g: graphic virtualization technology with mediated pass through
GVT-d: graphic virtualization technology with direct pass through
BDF of device eg "0000:00:1c.0" is used to distinguish GPU device in GVT-d,
while sysfsdev of device eg "f79944e4-5a3d-11e8-99ce-479cbab002e4"is used
in GVT-g.
Signed-off-by: Zhao Xinda <xinda.zhao@intel.com>
=> device: Add GPU device support

Makefile, cli/config.go, cli/config/configuration.toml.in, cli/config_test.go, cli/kata-env.go, cli/kata-env_test.go, virtcontainers/hypervisor.go, virtcontainers/qemu.go, virtcontainers/qemu_amd64.go, virtcontainers/qemu_amd64_test.go, virtcontainers/qemu_arch_base.go, virtcontainers/qemu_arch_base_test.go, virtcontainers/qemu_ppc64le.go, virtcontainers/qemu_ppc64le_test.go, virtcontainers/qemu_test.go, virtcontainers/sandbox.go
When we try to update the memory more than one time the runtime will try to add another slot of memory. This will fail due to we only add one extra memory slot.
Because the amount of slots has to be defined at qemu startup lets define a amount of slots.
Also add information about it on kata-env sub-command:
```diff
Hypervisor]
MachineType = "pc"
Version = "QEMU..."
Path = "/opt/kata/bin/qemu-system-x86_64"
BlockDeviceDriver = "virtio-scsi"
Msize9p = 8192
+  MemorySlots = 10
Debug = false
UseVSock = false
```
=> config: Add Memory slots config

virtcontainers/kata_agent.go
Otherwise we'll leave kata-proxy process dangling around forever.
Fixes: #759
=> agent: clean up proxy process if start sandbox failed

virtcontainers/kata_agent.go
Kata agent expects the pci address to be passed and not the
predicted device name.
Fixes #773
=> block: Fix how rootfs is passed to kata-agent using virtio-blk

virtcontainers/agent.go, virtcontainers/container.go, virtcontainers/hyperstart_agent.go, virtcontainers/kata_agent.go, virtcontainers/noop_agent.go, virtcontainers/sandbox.go
This reverts commit 8a6d383715f6cd8e0777ab5d14a421129bdff8c0.
Don't remove all directories in the shared directory because
`docker cp` re-mounts all the mount points specified in the
config.json causing serious problems in the host.
fixes #777
=> virtcontainers: revert "fix shared dir resource remaining"

Makefile, cli/config.go, cli/config/configuration.toml.in, cli/config_test.go, cli/kata-env.go, cli/kata-env_test.go, virtcontainers/device/config/config.go, virtcontainers/hypervisor.go, virtcontainers/qemu.go, virtcontainers/qemu_arch_base.go
Today we use `/dev/random` as entropy source.
This is a blocking entropy source, when the
host is getting a low amount of entropy the
Kata VM startup takes longer because block
trying to get entropy from the source.
This change allow to change the entropy source.
For example: urandom
Fixes: #702
=> vc: qemu: Add config option to choose entropy source.

virtcontainers/kata_agent.go
It does not give better pjdfstest results but allows us to pass
ubuntu `apt update`, fedora `dnf install`, and also launch `mariadb:latest`.
Fixes: #769
cc @sboeuf @WeiZhang555 @gnawux @egernst
=> agent: change 9pfs mount option to cache=mmap

data/kata-collect-data.sh.in
Make the output of `kata-collect-data.sh` slightly more attractive and
easier to read by using syntax highlighting where possible. This is
achieved by specifying a language for some of the code blocks,
specifically for the TOML config files and output of `kata-env` and the
YAML osbuilder config file.
See:
- https://help.github.com/articles/creating-and-highlighting-code-blocks/
- https://github.com/github/linguist
Fixes #775.
=> scripts: Use syntax highlighting in collect script

Gopkg.lock, vendor/github.com/intel/govmm/qemu/image.go, vendor/github.com/intel/govmm/qemu/qmp.go
Last time govmm was updated it was not vendored correctly
Fixes #797
=> vendor: fix govmm package

virtcontainers/qemu_amd64.go, virtcontainers/qemu_amd64_test.go
Add block device capability for q35 as this machine type supports it.
This was never added with the introduction of q35 support.
Fixes #771
=> block: Advertise block support for q35

virtcontainers/network.go, virtcontainers/network_test.go, virtcontainers/qemu_arch_base.go, virtcontainers/qemu_arch_base_test.go
Add support for macvlan driver by bridging it with a macvtap or
tap+bridge and moving the mac and ip address from the
macvlan to the bridged interface.
Fixes #162
=> network: Add support for macvlan and macvtap driver

Gopkg.lock, Gopkg.toml, vendor/github.com/intel/govmm/qemu/qemu.go, vendor/github.com/intel/govmm/qemu/qmp.go, virtcontainers/qemu.go, virtcontainers/qemu_amd64.go
The virt machine type provided by the NEMU project needs to be
supported the same way we support pc and q35 machine types.
First, this patch takes care of adding the hotpluggable block device
capability to this machine type, this way when using devicemapper, we
prevent the code from falling back on using 9pfs instead of SCSI.
It also add one or several bridges to this machine type, as the code
is tightly coupled to the fact that a bridge is required for PCI
hotplug.
At last, it changes the name of the PCI host bridge (main bus), to
use "pcie.0". The default set up from pc machine type "pci.0" is not
suitable for this machine type.
Fixes #804
=> virtcontainers: qemu: Add proper support for virt machine type

virtcontainers/network.go
Sort endpoints by name to control the order in which
they are passed to the VM as the interface name inside
the VM depends on the order in which it is passed.
Long term we should come up with a more robust approach.
Fixes #785
=> network: Sort endpoints by name

virtcontainers/network.go
Sort endpoints by name to control the order in which
they are passed to the VM as the interface name inside
the VM depends on the order in which it is passed.
Long term we should come up with a more robust approach.
Fixes #785
(cherry picked from commit 8f1b28da34e5091d5383448ac163de148d1b96d4)
=> network: Sort endpoints by name - stable 1.3

virtcontainers/network.go
Sort endpoints by name to control the order in which
they are passed to the VM as the interface name inside
the VM depends on the order in which it is passed.
Long term we should come up with a more robust approach.
Fixes #785
(cherry picked from commit 8f1b28da34e5091d5383448ac163de148d1b96d4)
=> network: Sort endpoints by name - stable1.2

Gopkg.lock, Gopkg.toml, vendor/github.com/intel/govmm/qemu/qemu.go, vendor/github.com/intel/govmm/qemu/qmp.go, virtcontainers/qemu.go, virtcontainers/qemu_arch_base.go
As we try to make sure we don't pull unneeded dependency when using
QEMU or NEMU as the hypervisor, and because SeaBIOS and OVMF firmware
already handle what's done by the default efi-virtio.rom binary, this
commit gets rid of this dependency by providing a default empty one.
Fixes #812
=> qemu: Disable the default romfile used by virtio-pci

cli/config/configuration.toml.in, cli/create_test.go, virtcontainers/api.go, virtcontainers/container.go, virtcontainers/container_test.go, virtcontainers/mock_hypervisor.go, virtcontainers/pkg/oci/utils.go, virtcontainers/pkg/oci/utils_test.go
When create sandbox, we setup a sandbox of 128M base memory, and
then hotplug memory that is needed for every new container. And
we change the unit of c.config.Resources.Mem from MiB to Byte in
order to prevent the 4095B < memory < 1MiB from being lost.
Fixes #400
Signed-off-by: Clare Chen <clare.chenhui@huawei.com>
Signed-off-by: Zichang Lin <linzichang@huawei.com>
=> sandbox/virtcontainers: memory resource hotplug when create container.

virtcontainers/api.go
Add missing trace calls to remaining public virtcontainers API
functions.
Fixes #824.
=> virtcontainers: Add missing API trace calls

cli/create.go, cli/create_test.go, cli/run_test.go
The bundle path was documented as defaulting to the current directory
but was not being set to that value if not explicitly specified.
Fixes #821.
=> create/run: Make bundle path default to cwd

virtcontainers/kata_agent.go
Kata agent expects the pci address to be passed and not the
virtPath in guest.
Fixes: #831
=> device: fix the issue of passing wrong device address using virtio-blk

versions.yaml, virtcontainers/monitor.go, virtcontainers/pkg/mock/cc_proxy_mock.go
Move to golang version 1.10.4 -- the oldest stable golang release at the
time of writing -- since golang 1.10+ is needed to make namespace
handling safe.
See:
- https://github.com/golang/go/issues/20676
- https://github.com/golang/go/commit/2595fe7fb6f272f9204ca3ef0b0c55e66fb8d90f
Also bumped `languages.golang.meta.newest-version` to golang version
1.11, which is the newest stable release at the time of writing.
Fixes #148.
=> versions: Update golang to 1.10.4

cli/config.go, cli/config/configuration.toml.in, cli/config_test.go, cli/kata-env.go, cli/kata-env_test.go, cli/network.go, cli/network_test.go, virtcontainers/bridgedmacvlan_endpoint.go, virtcontainers/bridgedmacvlan_endpoint_test.go, virtcontainers/default_network.go, virtcontainers/endpoint.go, virtcontainers/macvtap_endpoint.go, virtcontainers/network.go, virtcontainers/network_test.go, virtcontainers/physical_endpoint.go, virtcontainers/pkg/oci/utils.go, virtcontainers/qemu.go, virtcontainers/qemu_arch_base_test.go, virtcontainers/sandbox.go, virtcontainers/tap_endpoint.go, virtcontainers/veth_endpoint.go, virtcontainers/veth_endpoint_test.go, virtcontainers/vhostuser_endpoint.go
If `disable_new_netns` set to true, create VM and shim processes in the host netns
Fixes #731
=> cli: add configuration option to use or not use host netns

cli/config/configuration.toml.in, virtcontainers/network.go, virtcontainers/network_test.go
Instead of creating a bridge, use tc filter rules to redirect
traffic between veth and tap interface.
=> network: Use tc filtering rules in bridge mode

virtcontainers/physical_endpoint.go
Instead of using ethtool for getting the driver for network
devices, use sysfs instead. This is because in case of virtio
devices, ethtool returns virtio-net instead of virtio-pci for
virtio network devices. We need to bind/unbind from virtio-pci
driver in case of virtio-net devices.
Fixes #612
=> vfio: Change the way the driver is fetched

virtcontainers/endpoint.go, virtcontainers/ipvlan_endpoint.go, virtcontainers/ipvlan_endpoint_test.go, virtcontainers/network.go, virtcontainers/qemu_arch_base.go
Ipvlan is supported using tc filtering rules to redirect traffic between the ipvlan interface and tap interface.
=> Add support for ipvlan network driver

virtcontainers/factory/template/template.go, virtcontainers/factory/template/template_test.go, virtcontainers/qemu.go
This makes `saveSandbox` wait for migration completion, then we can remove the arbitrary sleep waiting for migration completion when creating a tempalte vm.
The govmm patch will be revendored once it is merged.
=> qemu: query migrate status

virtcontainers/factory/factory.go, virtcontainers/factory/factory_test.go
reflect.DeepEqual would return false when comparing nil map/slice with
empty map/slice. We would want to return success in such case, since it
is possible for upper layers to send these kind of configs.
Fixes: #844
=> factory: use customised deep compare

Makefile, cli/config.go, cli/config/configuration.toml.in, cli/config_test.go, virtcontainers/hypervisor.go, virtcontainers/kata_agent.go
Replaces #720 
- Rebased on current master
- Re-vendoring of `kata-containers/agent`, in a separate commit.
- Better documentation of the location of guest hooks per https://github.com/kata-containers/agent/pull/365#discussion_r217945769
=> cli: add guest hook path option (v2)

cli/kata-env.go, cli/kata-env_test.go
Both of the netmon and proxy should use the right path
figured out from the configure instead of the default settings
to get their versions.
Fixes: #868
Signed-off-by: Fupan Li <lifupan@gmail.com>
=> cli: fix the issue of using wrong path to get version

virtcontainers/default_network.go, virtcontainers/network.go, virtcontainers/noop_network.go, virtcontainers/sandbox.go
For non-factory case, default network endpoints are cold plugged. But for vm factory, we need to hotplug them after vm is assigned to the new sandbox.
=> enable default network endpoints hotplug for vm factory

cli/network.go, cli/network_test.go, netmon/netmon.go, netmon/netmon_test.go, virtcontainers/agent.go, virtcontainers/api.go, virtcontainers/api_test.go, virtcontainers/hyperstart_agent.go, virtcontainers/implementation.go, virtcontainers/interfaces.go, virtcontainers/kata_agent.go, virtcontainers/kata_agent_test.go, virtcontainers/network.go, virtcontainers/network_test.go, virtcontainers/noop_agent.go, virtcontainers/pkg/types/types.go, virtcontainers/pkg/vcmock/mock.go, virtcontainers/pkg/vcmock/mock_test.go, virtcontainers/pkg/vcmock/sandbox.go, virtcontainers/pkg/vcmock/types.go, virtcontainers/sandbox.go
The logic wants that virtcontainers should be the place where the common packages should be defined. This pull request takes care of defining generic network structures into a new package `pkg/types/types.go`, which is basically a duplication of what is defined by the agent. But this allows virtcontainers and its consumers (kata-runtime, kata-netmon, kata-containerd-shim) to be independent from the agent.
Based on the new package that define a new field `LinkType` for the structure `Interface`, Kata does not need anymore to do any assumption about the type of interface that needs to be added.
Fixes #866
Fixes #876
=> virtcontainers: Rely on new interface LinkType field

Makefile
Build {runtime,netmon} as Position-Independent-Executable (PIE) for improved
security and compliancy with distros packaging guidelines.
Fixes: #875
=> runtime,netmon: build as Position-Independent-Executable

virtcontainers/network.go
Align with other network models.
Fixes #884.
=> network: Use constant string for "none" network model

.ci/install-yq.sh, .travis.yml, Makefile, golang.mk, versions.yaml
Check that the system golang version is new enough to build with
according to the data from the `versions.yaml` file.
Update the verions in the versions.yaml accordingly, and add a note
describing what the 'newest-version' item represents.
Note, we only do a minimum requirement check, and are not checking
against the 'newest-version' info from the yaml.
Fixes: #148
Inspired-by: Wei Zhang <zhangwei555@huawei.com>
Idea-by: James O. D. Hunt <james.o.hunt@intel.com>
=> build: check golang version meets min req.

virtcontainers/container.go
Got "docker: Error response from daemon: OCI runtime create failed:
QMP command failed: unknown." when "docker run --privileged" with kata.
In qemu part, it got:
"Could not open '/dev/sr0': Read-only file system"
or
"No medium found"
The cause is qemu need open block device to get its status.
But /dev/sr0 is a CDROM that cannot be opened.
This patch let newContainer doesn't attach device if it is a CDROM
to handle the issue.
Fixes #829
=> newContainer: Not attach device if it is a CDROM

virtcontainers/api.go, virtcontainers/interfaces.go, virtcontainers/pkg/vcmock/sandbox.go, virtcontainers/sandbox.go, virtcontainers/sandbox_test.go
In order to support use cases such as `kata-containerd-shim-v2`, where we have a long running process holding the `Sandbox` pointer, there is no reason to call into the stateless functions, as they would recreate a new `Sandbox` pointer and the corresponding ones for containers.
Instead, this PR allows such case to use the sandbox API directly, avoiding to waste time in re-initialization and duplication.
Fixes #903
=> sandbox: Extend sandbox API

virtcontainers/network.go
Bind back the nic's MAC in HotDetach. So we don't need to modify
nic's MAC in description to hotplug it again.
Fixes: #894
=> network: support hotplug a nic several times

cli/oci.go, cli/utils_arch_base.go
Fixes: #908
Type of StatFs is not always declared as int64 for all the architecture(e.g s390x).
The function archConvertStatFs could be reimplemented for other architecture
to correctly convert the StatFs.Type.
=> build: introduction of archConvertStatFs function

virtcontainers/qemu.go, virtcontainers/qemu_arch_base.go, virtcontainers/qemu_test.go
This PR defines a new function supportGuestMemoryHotplug that
clearly defines if the architecture supports memory hotplug. The function
can be reimplemented in virtcontainers/qemu_$arch.go file for each
architecture.
Fixes: #910
=> virtcontainers: Add function supportGuestMemoryHotplug

virtcontainers/device/drivers/vfio.go
Since struct VFIODevice needed to be stored into disk by storeSandboxDevices() function,
however struct VFIODevice has a field named "vfioDevs", which is named begin with lower-case,
so it can't be written into file by json.Marshal.And this bug will will cause hotplug vfio
device can not been removed correctly while container exits.
Fixes: #924
Signed-off-by: flyflypeng <jiangpengfei9@huawei.com>
=> virtcontainers: fix sandbox store struct VFIODevice bug

versions.yaml
Update supported versions of Kubernetes with its
corresponding CRI implementations:
- Kubernetes from 1.10.5 to 1.12.2
- cri-o from 1.10 to 1.12.0, commit:
fa540c8e806d28c2cbcd157bdf8acf2b20990ab6 as it is needed
for fixing the devicemapper issues when removing a pod.
More info on this issue, see:
kubernetes-sigs/cri-o#1883
- containerd from 1.1.3 to 1.2.0
Fixes: #927.
=> versions: Update Kubernetes, containerd and cri-o

cli/kata-env.go, cli/kata-env_test.go, pkg/katautils/config.go, virtcontainers/pkg/oci/utils.go
Show whether runtime tracing is enabled in the output of `kata-env`.
Fixes #936.
=> kata-env: Show runtime trace setting

cli/kata-check.go, cli/kata-check_amd64.go, cli/kata-check_amd64_test.go, cli/kata-check_arm64.go, cli/kata-check_ppc64le.go, cli/kata-check_test.go, cli/kata-env.go
We do not really require nested VT to run kata containers. Let's not
depend on it being there.
Let's see if it fixes the recent nested vt related CI issues.
=> kata-check: do not require nested vt

cli/config/configuration.toml.in, pkg/katautils/config.go, pkg/katautils/config_test.go
If VM factory templating is enabled (`enable_template=true`), error if
the configured image is not an `initrd=` one.
Also add a note to the config file explaining that a normal image cannot
be used - only initrd images are supported.
Fixes #948.
=> config: Check factory config

virtcontainers/utils/utils_linux.go, virtcontainers/utils/utils_linux_test.go
The PR changes the parameter args from uint32 to uint64 for ioctl function. That leads to an endianess bug.
Fixes: #947
=> virtcontainers: change uint32 to uint64 for ioctl

Gopkg.lock, Gopkg.toml, vendor/github.com/intel/govmm/CONTRIBUTORS.md, vendor/github.com/intel/govmm/qemu/image.go, vendor/github.com/intel/govmm/qemu/qemu.go, vendor/github.com/intel/govmm/qemu/qemu_arch_base.go, vendor/github.com/intel/govmm/qemu/qemus390x.go, vendor/github.com/intel/govmm/qemu/qmp.go, virtcontainers/qemu.go, virtcontainers/qemu_arch_base.go, virtcontainers/qemu_test.go
Updating the govmm vendoring fixes the virtio-pci hotplug
when using NEMU in nested environments.
Shortlog:
f9b31c0 qemu: Allow disable-modern option from QMP
d617307 Run tests for the s390x build
b36b5a8 Contributors: Add Clare Chen to CONTRIBUTORS.md
b41939c Contributors: Add my name
dab4cf1 qmp: Add tests
5ea6da1 Verify govmm builds on s390x
ee75813 contributors: add my name
c80fc3b qemu: Add s390x support
ca477a1 Update source file headers
e68e005 Update the CONTRIBUTING.md
2b7db54 Add the CONTRIBUTORS.md file
b3b765c qemu: test Valid for Vsock for Context ID
3becff5 qemu: change of ContextID from uint32 to uint64
f30fd13 qmp: Output error detail when execute QMP command failed
7da6a4c qmp: fix mem-path properties for hotplug memory.
e4892e3 qemu/qmp: preparation for s390x support …
=> vendor: Update govmm vendoring

cli/config/configuration.toml.in, pkg/katautils/config.go, pkg/katautils/config_test.go, virtcontainers/kata_shim.go, virtcontainers/shim.go
Add a new `enable_tracing` option to `configuration.toml` to enable shim tracing.
Fixes #934.
=> shim: Add trace config option

virtcontainers/kata_agent.go, virtcontainers/qemu_arch_base.go, virtcontainers/qemu_test.go, virtcontainers/utils/utils_linux.go, virtcontainers/utils/utils_linux_test.go
The PR changes the Contex ID of Vsock from `uint32` to `uint64`. Otherwise, that leads to an endianess issue. For more information see https://github.com/kata-containers/runtime/issues/947.
Fixes: #958
=> Update cid vsock

cli/config/configuration.toml.in
Add block_device_cache_set, block_device_cache_direct
and block_device_cache_noflush.
Fixes: #997
=> config: Add cache-related options for block devices

arch/s390x-options.mk, cli/kata-check_data_s390x_test.go, cli/kata-check_s390x.go, cli/kata-check_s390x_test.go, cli/kata-env_s390x_test.go, cli/utils_s390x.go, versions.yaml, virtcontainers/hypervisor.go, virtcontainers/qemu.go, virtcontainers/qemu_arch_base.go, virtcontainers/qemu_arch_base_test.go, virtcontainers/qemu_s390x.go, virtcontainers/qemu_s390x_test.go
The PR adds the support for s390x.
In the case of CCW devices, the vhost-user devices are not supported.
See #659. An error message is thrown if they tried to be used.
Memory hotplug is not supported on s390 yet and an error message is thrown.
The VirtioNetPCI has been changed to VirtioNet. The generalization
allows to set the VirtioNet to the correct CCW device for s390x.
A lot of the elements in this PR have been taken from https://github.com/kata-containers/runtime/pull/667
Fixes: #666
Co-authored-by: Yash D Jain ydjainopensource@gmail.com
Signed-off-by: Alice Frosi <afrosi@de.ibm.>
=> s390x: add support for s390x

virtcontainers/qemu_arm64.go
Since kata-agent is using virtio-console to output debugging info and the console ports are available in the guest as `/dev/hvc0` and `/dev/hvc1`, we should swap origin console type `console=ttyAMA0` with `console=hvc0,hvc1`.
Fixes: #1033
Signed-off-by: Wei Chen <Wei.Chen@arm.com>
=> qemu-arm64: refactor 'console=hvc0,hvc1' for kata-agent debugging

pkg/katautils/config.go
shimv2 missed to enable vsock in KataAgentConfig.
Fixes: #1037
Signed-off-by: Fupan Li <lifupan@gmail.com>
=> katautils: fix the issue of shimv2 boot failed with vsock enabled

virtcontainers/network.go
The multiqueue flag associated with the TUNTAP network device cannot
be used if the number of queues indicates 0. When 0, this means the
multiqueue is not supported, and we cannot use the according flag.
Fixes #1051
=> virtcontainers: network: Use multiqueue flag only when appropriate

virtcontainers/sandbox_test.go
We can use the background context when creating test sandboxes from the
sanbox unit tests. This shuts the "trace called before context set"
erros down.
Fixes: #1048
Signed-off-by: Samuel Ortiz <sameo@linux.intel.com>
=> virtcontainers: Add context when creating tests sandboxes

pkg/katautils/config.go
Vsock conflicts with factory, when both of them are enabled,
kata will try to create a new vm template which is useless,
thus it's better to disable template to save a lot of time.
Fixes: #1055
=> katautils: check config factory/template and vsock

virtcontainers/cgroups.go
In case the hypervisor implementation does not return any thread
ID, this should not issue any error since there is simply nothing
to constraint.
Fixes #1062
=> virtcontainers: cgroups: Don't error if no thread ID

pkg/katautils/config.go, virtcontainers/device/config/config.go, virtcontainers/device/drivers/block.go, virtcontainers/device/manager/manager.go, virtcontainers/hyperstart_agent.go, virtcontainers/hypervisor.go, virtcontainers/kata_agent.go, virtcontainers/kata_agent_test.go, virtcontainers/qemu.go, virtcontainers/qemu_arch_base.go, virtcontainers/sandbox_test.go
Add support for virtio-mmio block devices. Firecracker only support virtio-mmio.
Note: Add a firecracker specific workaround to handle the fact that rootfs of the VM itself is also sent in as block device.
=> Firecracker: virtio mmio support

pkg/katautils/config.go
In order to let the user choose firecracker hypervisor instead of
QEMU (from the configuration.toml), let's add it to the list of
supported hypervisors.
Fixes #1042
Depends-on: github.com/kata-containers/runtime#1044
=> config: Add firecracker as a supported hypervisor configuration

virtcontainers/container.go, virtcontainers/hyperstart_agent.go, virtcontainers/kata_agent.go, virtcontainers/sandbox_test.go
In case we use an hypervisor that cannot support filesystem sharing,
we copy files over to the VM rootfs through the gRPC protocol. This
is a nice workaround, but it only works with regular files, which
means no device file, no socket file, no directory, etc... can be
sent this way.
This is a limitation that we accept here, by simply ignoring those
non-regular files.
Fixes #1068
=> mounts: Ignore existing mounts if they cannot be honored

virtcontainers/api.go, virtcontainers/fc.go, virtcontainers/hypervisor.go, virtcontainers/mock_hypervisor.go, virtcontainers/qemu.go, virtcontainers/qemu_test.go, virtcontainers/sandbox.go
This includes cleaning up the sandbox on disk resources, and closing fds opened when preparing the hypervisor.
=> sandbox: cleanup sandbox if creation failed

cli/config/configuration.toml.in, pkg/katautils/config-settings.go, pkg/katautils/config.go, virtcontainers/device/config/config.go, virtcontainers/device/drivers/block.go, virtcontainers/device/manager/manager.go, virtcontainers/hypervisor.go, virtcontainers/kata_agent.go, virtcontainers/qemu.go, virtcontainers/qemu_amd64.go, virtcontainers/qemu_arch_base.go, virtcontainers/qemu_arm64.go, virtcontainers/qemu_ppc64le.go, virtcontainers/qemu_s390x.go
These patches need the agent patch in https://github.com/kata-containers/agent/pull/424.
Set block_device_driver to "nvdimm" will make the hypervisor use
the block device as NVDIMM disk.
The nvdimm driver's read speed is faster than others.
Following is result of the disk io test rand 128k read, 128k write, 4k read and 4k write:
nvdimm:
READ: bw=12.1GiB/s (12.9GB/s), 1471MiB/s-1558MiB/s (1543MB/s-1634MB/s), io=10.6TiB (11.7TB), run=900001-900001msec
WRITE: bw=153MiB/s (160MB/s), 6240KiB/s-35.3MiB/s (6390kB/s-36.0MB/s), io=134GiB (144GB), run=900001-900005msec
READ: bw=1025MiB/s (1075MB/s), 1025MiB/s-1025MiB/s (1075MB/s-1075MB/s), io=901GiB (967GB), run=900001-900001msec
WRITE: bw=56.9MiB/s (59.7MB/s), 6092KiB/s-9323KiB/s (6238kB/s-9547kB/s), io=50.0GiB (53.7GB), run=900001-900004msec …
=> block: Add new block storage driver "nvdimm"

virtcontainers/container.go
Unmount recursively to unmount bind-mounted volumes.
Fixes: #965
Signed-off-by: Ning Lu <crossrunning@outlook.com>
=> container: Use lazy unmount

containerd-shim-v2/service.go
If the env KATA_CONF_FILE was set, shimv2 will use it as the
kata configure file, otherwise, it will try to find it from
/etc and /usr/share directory.
Fixes: #1091
=> shimv2: get the kata configure file from env KATA_CONF_FILE

virtcontainers/api.go, virtcontainers/sandbox.go
We include `agent.startSandbox` into `startVM` as those 2 always go together.
=> First createSandboxFromConfig simplification

cli/kill.go, cli/kill_test.go, virtcontainers/container.go, virtcontainers/sandbox.go, virtcontainers/sandbox_test.go
cri containerd calls kill on stopped sandbox and if we
fail the call, it can cause `cri stopp` command to fail
too.
Also add a few logs to track container state transitioning.
Fixes: #1084
=> cli: allow to kill a stopped container and sandbox

versions.yaml
We need to bump the kernel version from 4.14.67 to 4.19.10 in order
to follow the recent kernel config bump.
Fixes #1029
=> versions: Bump to kernel 4.19.10

versions.yaml
This reverts commit 802bfa26c9d99f50dc6e0eb11f2d049487339f63.
Seems that we have some performance issues when
using this new kernel. Reverting to have a clean CI and
have a proper investigation about the degradation.
Fixes: #1100.
=> kernel: Revert "versions: Bump to kernel 4.19.10"

cli/kata-check_ppc64le.go, cli/kata-check_ppc64le_test.go
The contents of /proc/cpuinfo were
trimmed and hence the "model" field could
not be parsed despite being a field in
/proc/cpuinfo. Fix this issue.
Fixes: #1089
=> kata-runtime: Return correct kata-env on ppc64le

virtcontainers/fc.go, virtcontainers/hypervisor.go, virtcontainers/mock_hypervisor.go, virtcontainers/mock_hypervisor_test.go, virtcontainers/qemu.go, virtcontainers/qemu_test.go, virtcontainers/sandbox.go, virtcontainers/virtcontainers_test.go, virtcontainers/vm.go
We remove the `waitSandbox` and `init` methods from the hypervisor interface in order to simplify it a bit.
=> Hypervisor interface simplification

versions.yaml
Add firecracker version to versions.yaml. This allows kata
packaging to build and package firecracker.
Fixes: #1103
=> Versions: Add firecracker version

cli/ps.go
Fixes: #1017
reason: when calls vci.ProcessListContainer, fix wrong parameter order
Signed-off-by: x00464843 <xueshaojia@huawei.com>
=> cli: fix parameter order error in cli/ps.go

cli/update.go, virtcontainers/container.go
Before, we would only allow for a container-update command
to proceed if the container was in the running state. So
long as the container is created, this should be allowed.
This was found using the `static` policy for Kubernetes CPU
manager[1]. Where the `update` command is called after the
`create` runtime command (when the container state is `ready`).
[1] https://github.com/kubernetes/community/blob/95a4a1/contributors/design-proposals/node/cpu-manager.md#example-scenarios-and-interactions
Fixes: #1083
=> update: allow do update on ready.

virtcontainers/sandbox_test.go
s/Emtpy/Empty/g
Fixes: #1145
Signed-off-by: Samuel Ortiz <sameo@linux.intel.com>
=> virtcontainers: Fix unit test typo

containerd-shim-v2/exec.go, containerd-shim-v2/service.go
It'll be much clear to unmarshal Protobuf.Any using
UnmarshalAny().
Fixes: #1130
=> shimv2: use the UnmarshalAny() to unmarshal Protobuf.Any

virtcontainers/qemu_ppc64le.go
Remove `nvdimm` from qemu command line
as the upstream qemu on ppc64le does not have
nvdimm capabilities yet.
Fixes: #1136
=> virtcontainers: ppc64le qemu does not have nvdimm capabilities yet

virtcontainers/qemu_s390x.go
The parameter is needed when you want to use the image option
Fixes: #1140
=> s390x: root parameter is missing

virtcontainers/qemu_s390x.go
=> s390x: change pci bridge type

cli/kata-check_data_ppc64le_test.go, cli/kata-check_ppc64le.go
IBM P9 systems can support virtualization with SMT
on. Make sure TestCCCheckCLIFunction passes on P8
(works only with SMT=off) and P9 as well.
Fixes: #1114
=> runtime: Fix TestCCCheckCLIFunction on P9 system

cli/main.go
Config paths are set correctly but they must be set before handleShowConfig
fixes #1185
cc @jodh-intel 
=> cli: set config options before showing config paths

Makefile
As arch detection isn't being done and KNOWN_HYPERVISORS was only
being populated via environment variable settings (and is a runtime
rather than build time dependency anyway) just provide a set of
defaults that can be overridden as needed at build time.
This will also cause any hypervisor configuration to always be
installed.
=> Makefile: Provide default hypervisor CMD settings

README.md
add snapcraft store banner
fixes #1198
=> snap: add snapcraft store banner

virtcontainers/cc_proxy.go, virtcontainers/filesystem_resource_storage_test.go, virtcontainers/hyperstart_agent_test.go, virtcontainers/kata_agent_test.go, virtcontainers/kata_builtin_proxy.go, virtcontainers/kata_proxy.go, virtcontainers/no_proxy.go, virtcontainers/pkg/hyperstart/mock/hyperstart.go, virtcontainers/pkg/mock/cc_proxy_mock.go, virtcontainers/qemu_test.go, virtcontainers/sandbox_test.go
Remove a bunch of useless and noisy logs and false positive errors in order to get a clean virtcontainers unit tests log.
Fixes #1211
=> Reduce virtcontainers unit test noise

pkg/katautils/config.go, pkg/katautils/config_test.go
If only initrd or rootfs image is installed,
allow to start Kata Containers without erroring
out.
Fixes:  #1174
=> runtime: Do not error if only initrd/rootfs image installed

Makefile
In GOPATH not set mode got:
make: go: Command not found
Makefile:38: arch/-options.mk: No such file or directory
make: go: Command not found
Makefile:237: *** "ERROR: No hypervisors known for architecture  (looked for: firecracker qemu)".  Stop.
The root cause is GOPATH not set mode is not set ARCH.
Set it to fix the issue.
Fixes: #1224
=> Makefile: Set ARCH in GOPATH not set mode

virtcontainers/store/filesystem_backend.go
Adding debug messages which state which files
are being deleted could be helpful in analyzing
situations like leaky pod issues.
Fixes: #1234
=> virtcontainers: Improve debug messages when deleting files

versions.yaml
We are using a newer hash for the packaged qemu-lite.
Update our record in versions.yaml to use the same version
in our CI.
Fixes: #1236.
=> versions: Update qemu-lite hash

versions.yaml
Update:
- k8s to version 1.13.3
- cri-o to version 1.13.0
- containerd to version 1.2.4, which
according to its release notes, uses
cri plugin version da0c016c830b2ea97fd1d737c49a568a816bf964
Fixes: #1238.
=> versions: update k8s, cri-o and containerd

cli/kata-check.go, cli/kata-check_amd64_test.go, cli/kata-check_arm64.go, cli/kata-check_arm64_test.go, cli/kata-check_ppc64le_test.go, cli/kata-check_s390x_test.go, cli/kata-check_test.go, cli/kata-env_test.go, virtcontainers/hypervisor_amd64_test.go, virtcontainers/hypervisor_arm64_test.go, virtcontainers/hypervisor_test.go, virtcontainers/qemu.go, virtcontainers/qemu_amd64.go, virtcontainers/qemu_arch_base.go, virtcontainers/qemu_arm64.go, virtcontainers/qemu_arm64_test.go, virtcontainers/qemu_ppc64le.go, virtcontainers/qemu_s390x.go
```
09:55:00 cli/kata-check_arm64.go:129:9:warning: if block ends with a return statement, so drop this else and outdent its block (move short variable declaration to its own line if necessary) (golint)
09:55:02 virtcontainers/qemu_arm64_test.go:43:23:warning: unused variable or constant undeclared name: virt (varcheck)
09:55:02 virtcontainers/qemu_arm64_test.go:50:11:warning: unused variable or constant undeclared name: defaultMemSlots (varcheck)
09:55:02 virtcontainers/qemu_arm64_test.go:54:40:warning: unused variable or constant too few arguments in call to arm64.memoryTopology (varcheck)
09:55:02 virtcontainers/qemu_arm64_test.go:29:23:warning: unused variable or constant undeclared name: virt (varcheck)
09:55:02 cli/kata-check_test.go:141:113:warning: unused variable or constant …
```
=> Unit test: fix bugs on a few unit tests on aarch64

cli/delete.go, cli/delete_test.go
When a container does not exist, runc does not fail.  Lets mimic this
behavior, sometimes kuberentes will try to force delete containers that
could not be created and gets confused if delete --force fails.
Fixes: #1219
=> delete: force: Do not fail on non exiting container

virtcontainers/api.go, virtcontainers/api_test.go, virtcontainers/cgroups.go, virtcontainers/cgroups_test.go, virtcontainers/container.go, virtcontainers/fc.go, virtcontainers/hypervisor.go, virtcontainers/kata_agent.go, virtcontainers/mock_hypervisor.go, virtcontainers/qemu.go, virtcontainers/sandbox.go, virtcontainers/sandbox_test.go, virtcontainers/types/sandbox.go
All containers run in different cgroups even the sandbox, with this new
implementation the sandbox cpu cgroup wil be equal to the sum of all its
containers and the hypervisor process will be placed there impacting to the
containers running in the sandbox (VM). The default number of vcpus is
used when the sandbox has no constraints. For example, if default_vcpus
is 2, then quota will be 200000 and period 100000.
**c-ray test**
http://www.futuretech.blinkenlights.nl/c-ray.html
```
+=============================================+
|         | 6 threads 6cpus | 1 thread 1 cpu  |
+=============================================+
| current |   40 seconds    |   122 seconds   |
+==============================================
|   new   |   37 seconds    |   124 seconds   | …
```
=> virtcontainers: reimplement sandbox cgroup

virtcontainers/qemu.go
Sometimes qemu/qmp commands error out and VM files
get left behind on the host filesystem. Clen them up
irrespective of `stopSandbox` succeeds or fails.
Fixes: #1246
=> qemu: Cleanup Vm paths irrespective of Sandbox stop pass/fail

virtcontainers/device/drivers/vhost_user_blk.go
Commit affd6e3216cbcfe797c617f61138bda1a5e928b2 ("devices: add reference
count for devices.") introduced an attach count for devices.  The
vhost-user-blk device increments the counter instead of decrementing it
when detaching.
Fixes: #1259
Signed-off-by: Stefan Hajnoczi <stefanha@redhat.com>
=> devices: fix attach count for vhost-user-blk

virtcontainers/cgroups.go, virtcontainers/container.go
sandbox cgroup use V1NoConstraints, this only create memory subsystem,
but when delete, load parent cgroup always use `cgroups.V1`, so other
subsystem path can not be find, sandbox cgroup can not be deleted.
Fixes: #1263
=> cgroups: fix failed to remove sandbox cgroup

versions.yaml
We need to bump the kernel version from 4.14.67 to 4.19.24 in order
to follow the recent kernel config bump.
Fixes #618 
Fixes #1029
=> versions: Bump to kernel 4.19.24

virtcontainers/api.go, virtcontainers/store/manager.go
Add a `store.SetLogger()` API to allow the store package to log with the standard set of fields (as expected by the log parser [1].
Fixes #1297.
---
[1] - https://github.com/kata-containers/tests/tree/master/cmd/log-parser#logfile-requirements
=> store: Add SetLogger API

virtcontainers/network.go
We have 7 types of endpoints, but forget ipvlan in unmarshal funciton.
So add it and refactor for cyclomatic complexity reason.
Fixes #1254
=> Network: add ipvlan unmarshal

virtcontainers/sandbox.go, virtcontainers/utils/utils.go
We were grabbing a running total of quota and period for each container
and then calculating the number of resulting vCPUs. Summing period
doesn't make sense.  To simplify, let's just calculate mCPU per
container, keep a running total of mCPUs requested, and then translate
to sandbox vCPUs after.
Fixes: #1292
=> virtcontainers: fix vCPU calculation errors

virtcontainers/sandbox.go, virtcontainers/utils/utils.go
We were grabbing a running total of quota and period for each container
and then calculating the number of resulting vCPUs. Summing period
doesn't make sense.  To simplify, let's just calculate mCPU per
container, keep a running total of mCPUs requested, and then translate
to sandbox vCPUs after.
Fixes: #1292
=> fix vCPU calculations: bug fix for stable-1.5 cpu calculations fix stable

README.md
Now that we have been moved the CI to ubuntu 18.04, we need to update the
README.
Fixes #1300
=> doc: Fix invalid URLs

Makefile, golang.mk
The cause that make "sudo make install" fail is not "GOPATH not set",
but no go command in path.
But the commit still keep the "GOPATH not set" because
execute "unset GOPATH; make" will fail because "go build" cannot work
without GOPATH.
=> Makefile: Change "GOPATH not set" to "No GO command"

virtcontainers/qemu.go
reason: When excutes ExecuteNetCCWDeviceAdd, the DevID is always "virtio-".
If add-iface multy times, qemu may report "dumplicated id:virtio-".
Fixes: #1305
=> qemu: fix devID value error

pkg/katautils/config.go, pkg/katautils/config_test.go
Check the "builtIn" first when updating the shim/proxy/agent,
thus can avoid checking the shim/proxy's binary files path which
is needless for "builtIn" type.
Fixes: #1314
=> config: check the builtIn first when updating shim/proxy/agent

virtcontainers/api.go, virtcontainers/sandbox.go
The store refactor (#1066) inadvertently broke runtime tracing as it created new contexts containing trace spans.
Reworking the store changes to re-use the existing context resolves the problem since runtime tracing assumes a single context.
Fixes #1277.
=> tracing: Fix tracing

Makefile
Got aarch64 fail in No GO command or GOPATH not set mode:
Makefile:38: arch/aarch64-options.mk: No such file or directory
Makefile:237: *** "ERROR: No hypervisors known for architecture aarch64 (looked for: firecracker qemu)".  Stop.
The cause is the machine hardware name of aarch64 is aarch64 but
runtime's arch make file's name is arm64-options.mk.
This commit convert aarch64 to arm64 to fix the issue.
Fixes: #1320
=> Makefile: Fix aarch64 fail in No GO command or GOPATH not set mode

cli/kata-env_amd64_test.go, cli/kata-env_arm64_test.go, cli/kata-env_ppc64le_test.go, cli/kata-env_test.go
Since arch-specific func `getExpectedHostDetails` holds undefined struct field `SupportVSocks` on arm64, unit test `TestEnvGetEnvInfoSetsCPUType`, `TestEnvGetHostInfo` and so on failed.
I'm trying to use generic func `genericgetExpectedHostDetails` on arm64 to avoid similar issues.
=> unit-test: fix undefined struct field SupportVSocks on arm64

virtcontainers/kata_builtin_proxy.go, virtcontainers/kata_builtin_proxy_test.go
kata builtin proxy has always watched the qemu's console
whether proxy's debug is set or not, this is not aligned
with kata cli. This patch will change it and watch the
qemu's console only when proxy's debug is set in kata config.
Fixes: #1318
=> virtcontainer: watch the qemu's console when proxy's debug enabled

versions.yaml
In order to automate the checking of our component versions against their upstream sources,
add 'uscan' formatted URL regexps to items that have a 'version:' key to allow scripts to determine
both our current version, and how to find the latest upstream version.
=> Add upstream version url regexp's to allow upto date checks

virtcontainers/Makefile, virtcontainers/api_test.go, virtcontainers/proxy.go, virtcontainers/vm.go, virtcontainers/vm_test.go
- Simply empty string proxy type handling and cast string  ProxyType
- Allow run make check-go-test from virtcontainers directory 
Fixes: #1312
=> unit test: Fix local test

virtcontainers/hyperstart_agent_test.go, virtcontainers/kata_agent_test.go, virtcontainers/sandbox_test.go
When sandbox creation failed, we should do rollback operations to
cleanup those files and folders. Including:
- share path
- cgroup subsystems
- sandbox local resources
Fixes: #862
Signed-off-by: l00397676 <lujingxiao@huawei.com>
=> test: add tests for sandbox creation rollback and cleanup

virtcontainers/veth_endpoint.go
This a bool field. It is useless because veth endpoint is never a
physical endpoint. And it is never used.
Fixes #1343
=> Network: remove Physical field in VethEndpoint

virtcontainers/container.go, virtcontainers/container_test.go, virtcontainers/kata_agent.go
This patch fixes the issue where vrious version of snapshotters,
overlay, block based graphdriver, containerd-shim-v2 overlay, block
based snapshotters mount & create rootfs differently and kata should be
able to handle them all.
The current version of the code always assumes that a folder named
'rootfs' exists within the mount device and that is the path the
container should start at. This patch checks the existing mount point
and if it is the same as the rootFs passed to the container, we no
longer add a suffix to the container's rootfs path.
Fixes: #1325
Co-Authored-by: Manohar Castelino <manohar.r.castelino@intel.com>
=> Fix rootfs mount assumptions

pkg/katautils/config.go, pkg/katautils/config_test.go, pkg/katautils/create.go
Reduce memory footprint ~7% by disabling some systemd services like
systemd-journald and systemd-udevd, those services are just consuming memory
and are not needed. For example kata-agent logs the errors through the proxy.
fixes #1339
=> pkg: reduce memory footprint

data/kata-collect-data.sh.in
- Add details of the crio config to the data collection script.
- Add a new sub-section for containerd details.
Fixes #1349.
This should help make diagnosing issues like https://github.com/kata-containers/documentation/issues/389 faster.
/cc @egernst, @chavafg.
=> Add crio and containerd details to collect script

virtcontainers/qemu_arm64.go, virtcontainers/qemu_arm64_test.go
As Arm64 is using the block device as the rootfs in guest. If we run two or more kata-container instances
on one host, we will get following error:
```
root@entos-thunderx2-desktop:~# docker run -dt --runtime kata-runtime ubuntu
7baf2c0f26100b0e642ad4122ce9ea1cb556fb3ed6cfcb454cb0586cbbe6194d
root@entos-thunderx2-desktop:~# docker run -dt --runtime kata-runtime ubuntu
2065fcf560c136091b5e69b6a12c95de94308309bb7fd5309df852503752203a
docker: Error response from daemon: OCI runtime create failed: qemu-system-aarch64: -device virtio-blk,drive=image-9f100592ac95eec6,scsi=off,config-wce=off: Failed to get "write" lock
Is another process using the image?: unknown.
```
Thanks to the new expanded IPA_SIZE feature in kernel 4.20 and Eric Auger's patch set [ARM virt: Initial RAM expansion and …
=> arm64: support NVDIMM

virtcontainers/qemu.go
QMP doesn't guarantee the order of the array that is returned by
`query-memory-devices` command. So we would better search the whole
array to find out the current max slot, rather than simply use the last
element's slot.
Fixes: #1362
=> vc:qemu: Fix id calculation of memory hotplug

virtcontainers/qemu.go, virtcontainers/qemu_test.go
Return error soon when addDeviceToBridge() can not get empty address
from bridges, or the error will thrown by qemu, this is not obvious.
Fixes: #1005
=> qemu: throw error when fail to get addr from bridges

pkg/katautils/create_test.go, pkg/katautils/utils.go, pkg/katautils/utils_test.go, virtcontainers/container.go, virtcontainers/mount.go, virtcontainers/mount_test.go
We were considering all empty-dir k8s volumes as backed by tmpfs.
However they can be backed by a host directory as well.
Pass those as 9p volumes, while tmpfs volumes are handled as before,
namely creating a tmpfs directory inside the guest.
The only way to detect "Memory" empty-dirs is to actually check if the
volume is mounted as a tmpfs mount, since any information of k8s
"medium" is lost at the OCI layer.
Fixes #1341
=> volumes: Handle k8s empty-dirs of "default" medium type

virtcontainers/api_test.go, virtcontainers/container.go, virtcontainers/utils/utils.go, virtcontainers/utils/utils_test.go
Create cgroup path relative the cgroups mount point if it's absolute,
or create it relative to a runtime-determined location if the path
is relative.
fixes #1365
fixes #1357
=> virtcontainers: honor OCI cgroupsPath

virtcontainers/qemu_s390x.go
The bridges function was missing for s390x
Fixes: #1380
=> s390x: add bridges function

pkg/katautils/create.go, virtcontainers/qemu_amd64.go
Mounting the rootfs as read-only fs the binaries can't be modified.
fixes #1389
=> virtcontainers: improve security and mount the rootfs as read-only fs

.ci/install-yq.sh
install-yq.sh use curl but not check if curl is available or not.
Add code to check curl before use it.
Fixes: #1379
=> ci: check curl before use it

pkg/katautils/config.go
After code check and test, found VMCache can work with vsock.
Remove the code that prohibit them from working together.
Fixes: #1400
=> config: Make VMCache can work with vsock

data/kata-collect-data.sh.in
Use a clever HTML trick to allow the output of the data collection script to be hidden / unhidden in the github.com interface.
See the example at the top of https://github.com/kata-containers/runtime/issues/1347.
Fixes #1386.
=> Allow data collection to be hidden

data/kata-collect-data.sh.in
osbuilder recently added the ability to create images with a DAX/NVDIMM header [1], however this change broke the data collection script. Update that script to handle images with and without this header.
The data collection script will now assume a header is present. However, if it fails to find the required partition data, it will try again, this time assuming the image does not have a DAX/NVDIMM header.
Fixes #1404.
[1] - https://github.com/kata-containers/osbuilder/pull/236
=> Update collect script for dax nvdimm images

cli/factory.go, cli/factory_test.go, virtcontainers/factory/factory.go, virtcontainers/factory/factory_test.go, virtcontainers/factory/template/template.go, virtcontainers/factory/template/template_test.go
Now, function NewFactory will return nil even create template
does't complete. As for this, it will tell user that factory
has been initialized no matter whether the template is created
or not. This patch correct it by adding another return value
of error in NewFactory.
Fixes: #1333
Signed-off-by: Jianyong Wu  <jianyong.wu@arm.com>
@jodh-intel @grahamwhaley @Pennyzct
=> Factory: Fix fake return value issue on creating template

pkg/katautils/config.go, pkg/katautils/config_test.go
Like shim, we should validate the proxy path if it is provided.
Fixes: #1424
=> config: validate proxy path

cli/kata-check.go, cli/kata-check_test.go, cli/kata-env_test.go, virtcontainers/hypervisor_test.go, virtcontainers/qemu.go
ARM CI is failing.
Copy log from #1414:
```
18:09:54 func genericMemoryTopology(memoryMb, hostMemoryMb uint64, slots uint8, memoryOffset uint32) govmmQemu.Memory {
18:09:54      ^
18:09:54 cli/kata-check.go:55:2: `genericCPUFlagsTag` is unused (deadcode)
18:09:54 	genericCPUFlagsTag    = "flags"      // nolint: varcheck, unused
18:09:54 	^
18:09:54 cli/kata-check.go:56:2: `genericCPUVendorField` is unused (deadcode)
18:09:54 	genericCPUVendorField = "vendor_id"  // nolint: varcheck, unused
18:09:54 	^
18:09:54 cli/kata-check.go:57:2: `genericCPUModelField` is unused (deadcode)
18:09:54 	genericCPUModelField  = "model name" // nolint: varcheck, unused
18:09:54 	^
18:09:54 cli/kata-check_test.go:31:6: `testCPUData` is unused (deadcode)
18:09:54 type testCPUData struct {
18:09:54      ^ …
```
=> linter: remove deadcode linter check for generic item

cli/create.go, containerd-shim-v2/create.go, containerd-shim-v2/delete.go, containerd-shim-v2/service.go, pkg/katautils/create.go, pkg/katautils/create_test.go, pkg/katautils/utils.go, virtcontainers/api.go, virtcontainers/api_test.go, virtcontainers/container.go, virtcontainers/container_test.go, virtcontainers/example_pod_run_test.go, virtcontainers/hack/virtc/main.go, virtcontainers/hyperstart_agent.go, virtcontainers/kata_agent.go, virtcontainers/mount.go, virtcontainers/pkg/oci/utils.go, virtcontainers/pkg/oci/utils_test.go, virtcontainers/sandbox.go
If containerd snapshotter is a block storage backed, it's better to plug container rootfs into hypervisor as a block storage instead of mount it onto host, thus:
change container's rootfs from string to mount alike struct as below:
RootFs struct {
// Source specify the BlockDevice path
Source string
// Target specify where the rootfs is mounted if it has been mounted
Target string
// Type specifies the type of filesystem to mount.
Type string
// Options specifies zero or more fstab style mount options.
Options []string
// Mounted specifies whether the rootfs has be mounted or not
Mounted bool
}
If the container's rootfs has been mounted as before, then this struct can be
initialized as: RootFs{Target: \<rootfs path\>, Mounted: true} to be compatible with
previous case.
=> shimv2: optionally plug rootfs block storage instead of mounting it

virtcontainers/cgroups.go, virtcontainers/container.go, virtcontainers/types/sandbox.go
Fixes: #1415
Container resources have been saved to ContainerConfig so there's no
need to save it again in state.json.
=> cgroups: remove duplicate fields from state

virtcontainers/api_test.go, virtcontainers/cc_shim_test.go, virtcontainers/kata_shim_test.go, virtcontainers/noop_agent_test.go, virtcontainers/sandbox_test.go
Fixes: #1422
Detect failing test case:
```
....
=== RUN   TestEnterContainerFailingContNotStarted
--- PASS: TestEnterContainerFailingContNotStarted (0.01s)
=== RUN   TestEnterContainer
--- FAIL: TestEnterContainer (0.00s)
Error Trace: sandbox_test.go:1154
Error:      	Expected value not to be nil.
Messages:   	Entering non-running container should fail
Error Trace: sandbox_test.go:1157
Error:      	Expected nil, but got: &errors.errorString{s:"Can not
move from running to running"}
Messages:   	Failed to start sandbox: Can not move from running to
running
FAIL
```
`TestEnterContainerFailingContNotStarted` calls `cleanUp` at function
begging but it doesn't clean its garbage after it ends.
`TestEnterContainer` only call `cleanUp` in the end but it doesn't do
cleanUp in the begging, that …
=> tests: do cleanUp() always in the end

virtcontainers/api.go, virtcontainers/sandbox.go
add vm cleanup before startVM()
Fixes: #1426
=> qemu: fix qemu leak when failed to start container

virtcontainers/qemu.go, virtcontainers/qemu_test.go
Instead of the agent trying to determine if a serial
or vsock channel is used, pass this information explicitly
as a kernel command line option.
Fixes #1457
=> vsock: Pass info about vsock being used or not to the agent.

README.md, cli/factory.go, cli/factory_test.go, pkg/katautils/config.go, pkg/katautils/config_test.go, virtcontainers/api.go, virtcontainers/api_test.go, virtcontainers/cc_shim_test.go, virtcontainers/factory/factory.go, virtcontainers/factory/factory_test.go, virtcontainers/factory/template/template.go, virtcontainers/factory/template/template_test.go, virtcontainers/kata_shim_test.go, virtcontainers/noop_agent_test.go, virtcontainers/sandbox.go, virtcontainers/sandbox_test.go
relevant backports since 1.6 release:
eadf977 Factory: Fix fake return value issue on creating template
dd6e8eb tests: do cleanUp() always in the end
096fa04 qemu: fix qemu leak when failed to start container
fb64a3e doc: update architecture.md link
dca7a6f config: validate proxy path
=> Stable 1.6 backports

.ci/lib.sh, README.md, pkg/katautils/config.go, pkg/katautils/config_test.go, virtcontainers/Makefile, virtcontainers/api.go, virtcontainers/sandbox.go
relevant backports since 1.6:
096fa04 qemu: fix qemu leak when failed to start container
fb64a3e doc: update architecture.md link
config: validate proxy path
virtcontainers: makefile fix .ci path
=> Stable 1.5 backports

.ci/install-yq.sh
1. Set version to 2.3.0
2. Check the fail of curl
=> Fix yq issues

pkg/katautils/config.go
when use shim v2 interface to run container, no need to use kata-proxy
and kata-shim, remove kata-proxy and kata-shim in config file will cause
panic since type assertion. add check to avoid panic
Fixes: #1440
=> config: fix panic in type assertion

virtcontainers/qemu.go
For cpu hotplug, the options socketID and threadID are not used.
Fixes: #1448
=> s390x: not set socketID and threadID

.travis.yml
We have hit an issue using trusty in travis and go 1.11.7
Using xenial the issue is fixed.
Fixes: #1492.
=> travis: use xenial

virtcontainers/pkg/nsenter/nsenter.go, virtcontainers/pkg/nsenter/nsenter_test.go
Depending of the linux versions some namespaces are supported or not.
To avoid failures running containers and unit tests in old linux kernels,
only the supported namespaces should be used.
Depends-on: github.com/kata-containers/tests#1414
fixes #228
=> virtcontainers: Use only supported namespaces

pkg/katautils/config.go
When used builtin proxy, it's better to config the proxy
debug based on setting in kata configuration.
Fixes:#1495
=> katautils: fix the issue of missing proxy debug config

virtcontainers/hypervisor.go, virtcontainers/qemu.go, virtcontainers/vm.go
Store related in directory /var/lib/vc/sbs and /run/vc/sbs if
vm template is enabled.
The cause is NewVM and NewVMFromGrpc will create vcStore with
VM's ID and set it as store of hypervisor if the factory is enabled.
This commit record the VM's ID to HypervisorConfig.VMid and remove
directories in qemu.cleanupVM to handle the issue.
Fixes: #1452
=> qemu: Remove the storage directories if qemu get from the factory

cli/delete.go, cli/delete_test.go, cli/events_test.go, cli/exec_test.go, cli/kill_test.go, cli/main_test.go, cli/network_test.go, cli/pause_test.go, cli/ps_test.go, cli/update_test.go, containerd-shim-v2/pause_test.go, containerd-shim-v2/utils.go, virtcontainers/api_test.go, virtcontainers/cgroups_test.go, virtcontainers/container.go, virtcontainers/container_test.go, virtcontainers/kata_agent.go, virtcontainers/kata_agent_test.go, virtcontainers/pkg/oci/utils.go, virtcontainers/pkg/oci/utils_test.go, virtcontainers/sandbox.go, virtcontainers/sandbox_test.go, virtcontainers/store/vc.go, virtcontainers/types/container.go, virtcontainers/types/sandbox.go
The only thing we really need to record in common is statestring and cgrouppath. Let's split them. `ContainerStatus.BlockIndex` can also be moved once we drop the legacy hyperstart agent.
container share pidns property checking is also modified. We no longer rely on the first container process id since it is unavailable in shimv2 case anyway. Whenever a container has a pidns path, we'll make it share the sandbox pidns. /cc @amshinde
=> split sandbox/container state

containerd-shim-v2/service.go
There is no need to send another SIGKILL signal following
SIGTERM signal, otherwise, sending the SIGKILL signal would
get failed since the container process would has been terminated
by the previous SIGTERM signal.
Fixes:#1493
=> shimv2: fix the issue of stop container failed

cli/kata-check_amd64_test.go
We don't really require nested nor unrestricted_guest to run. And there
is no point validating host cpu properties in UT.
Fixes: #1508
=> cli: fix kata-check test

virtcontainers/factory/template/template.go, virtcontainers/factory/template/template_amd64.go, virtcontainers/factory/template/template_arm64.go, virtcontainers/factory/template/template_ppc64le.go, virtcontainers/factory/template/template_s390x.go, virtcontainers/qemu.go, virtcontainers/qemu_amd64.go, virtcontainers/qemu_arch_base.go, virtcontainers/qemu_arm64.go, virtcontainers/qemu_ppc64le.go, virtcontainers/qemu_s390x.go
Template: enable template for arm64
Now, template feature can't work on arm64. When using bypass-shared-memory
cap to saving sandbox as a template, new sandbox cloning from the template
will fail. From initial investigation, it maybe a qemu issue. Further
research should be done.
To enable template on arm64, this patch adds a switch to offer the capability
to open or close the bypass-shared-memory cap.
While closing bypass-shared-memory cap, saving vm will occupy more space
and consume more time. So increase 300M for mount size and bump the time
waiting for migration to 10 seconds.
Fixes: #1336
Signed-off-by: Jianyong Wu  <jianyong.wu@arm.com>
@jodh-intel @grahamwhaley  @bergwolf  @Pennyzct
=> Factory: enable template feature for arm64

virtcontainers/api_test.go, virtcontainers/cgroups.go, virtcontainers/container.go
prepend a kata specific string to oci cgroup path to form a different cgroup path, thus cAdvisor couldn't find kata containers cgroup path on host to prevent it from grabbing the stats data.
Fixes:#1488
=> virtcontainers: prepend a kata specific string to host cgroups path

pkg/katautils/create.go, pkg/katautils/create_test.go, pkg/katautils/utils.go, pkg/katautils/utils_test.go, virtcontainers/container.go, virtcontainers/kata_agent.go, virtcontainers/kata_agent_test.go, virtcontainers/mount.go, virtcontainers/mount_test.go
**Some notes about this PR:**
- I've based it off https://github.com/kata-containers/runtime/pull/1418, as it had logic around host k8s emptyDir completed for me.
- There is a corresponding PR in the kata-agent repo which actually creates the directories: https://github.com/kata-containers/agent/pull/521
---
This introduces a new storage type: local. Local storage type will
tell the kata-agent to create an empty directory in the sandbox
directory within the VM.
K8s host emptyDirs will then use the local storage type and mount it
inside each container. By doing this, we utilise the storage medium
that the sandbox uses. In most cases this will be 9p.
If the VM is using device mapper for container storage, the containers
will benefit from the better performance of device mapper for
host …
=> storage: create k8s emptyDir inside VM

pkg/katautils/create.go, pkg/katautils/create_test.go, pkg/katautils/utils.go, pkg/katautils/utils_test.go, virtcontainers/container.go, virtcontainers/mount.go, virtcontainers/mount_test.go
We handle system directories differently, if its a bind mount
we mount the guest system directory to the container mount and
skip the 9p share mount.
However, we should not do this for docker volumes which are directories
created by Docker.
This introduces a Docker specific check, but that is the only
information available to us at the OCI layer.
Fixes #1417 
=> mounts: Add check for system volumes

virtcontainers/container_test.go, virtcontainers/hyperstart_agent_test.go, virtcontainers/kata_agent_test.go, virtcontainers/virtcontainers_test.go
1. fix ut failure as cleanup removes the initial test setup, as stated in #1525 
2. make ut runnable with non-root
=> fix ut failure due to incorrect cleanup and make it runnable with non-root

virtcontainers/cgroups.go
Don't set a default CPU constraint if period and quota are not specified, that
way the container will inherit the CPU constraint from its parent. Container
creation won't fail if the parent CPU constraint is smaller than the default
number of vCPUs.
fixes #1521
=> virtcontainers: inherit parent's CPU constraint

netmon/netmon.go, netmon/netmon_test.go
The agent expects a IP CIDR for the route destination
rather than an IP address. netmon was incorrectly
converting route dest to an IP address and hence
exiting with an error.
Fixes #1523
=> netmon: Fix bug in how routes are converted

netmon/netmon.go, netmon/netmon_test.go
The agent expects a IP CIDR for the route destination
rather than an IP address. netmon was incorrectly
converting route dest to an IP address and hence
exiting with an error.
We did not have an integration test for netmon with tcfilter mode.
macvtap mode did not uncover this, as with macvtap routes are
not really passed to the agent.
We delete the IP on the veth device, and netmon looks at the
routes after the IP is deleted with macvtap.
Fixes #1523
=> stable 1.6 backport: netmon: Fix bug in how routes are converted

netmon/netmon.go, netmon/netmon_test.go
The agent expects a IP CIDR for the route destination
rather than an IP address. netmon was incorrectly
converting route dest to an IP address and hence
exiting with an error.
We did not have an integration test for netmon with tcfilter mode.
macvtap mode did not uncover this, as with macvtap routes are
not really passed to the agent.
We delete the IP on the veth device, and netmon looks at the
routes after the IP is deleted with macvtap.
Fixes #1523
=> Stable 1.5 backport: netmon: Fix bug in how routes are converted

Makefile, virtcontainers/network.go
tcfilter requires no changes to the interface provided by the network
plugin and supports a larger set of plugins.
Fixes #1501
=> network: Make tcfilter model as default

virtcontainers/kata_agent.go
The "ephemeral" is just used to indicate ephemeral volumes in
runtime. We should not pass it to agent. Instead, "bind" should be
the correct mount type to be passed.
Fixes: #1438
Signed-off-by: Xie Yongji <xieyongji@baidu.com>
=> agent: pass correct mount type to agent for ephemeral volumes

Makefile, cli/kata-check_amd64_test.go, containerd-shim-v2/service.go, pkg/katautils/config.go, versions.yaml, virtcontainers/api_test.go, virtcontainers/cgroups.go, virtcontainers/container.go, virtcontainers/network.go
Backports include below changes
https://github.com/kata-containers/runtime/pull/1502
https://github.com/kata-containers/runtime/pull/1441
https://github.com/kata-containers/runtime/pull/1518
https://github.com/kata-containers/runtime/pull/1509
https://github.com/kata-containers/runtime/pull/1494
=> backport: 1.6.2 backport patches

virtcontainers/factory/template/template.go
Check if vm templateing is on before vm templateing initialize.
Fixes: #1514
=> factory: Check if vm templateing is on before vm templateing initialize

virtcontainers/api.go, virtcontainers/container.go, virtcontainers/container_test.go, virtcontainers/device/api/interface.go, virtcontainers/device/drivers/block.go, virtcontainers/device/drivers/generic.go, virtcontainers/device/drivers/vfio.go, virtcontainers/device/drivers/vhost_user_blk.go, virtcontainers/device/drivers/vhost_user_net.go, virtcontainers/device/drivers/vhost_user_scsi.go, virtcontainers/mount_test.go, virtcontainers/persist.go, virtcontainers/persist/api/config.go, virtcontainers/persist/api/container.go, virtcontainers/persist/api/device.go, virtcontainers/persist/api/interface.go, virtcontainers/persist/api/network.go, virtcontainers/persist/api/sandbox.go, virtcontainers/persist/api/version.go, virtcontainers/persist/fs/fs.go, virtcontainers/persist/fs/fs_test.go, virtcontainers/persist/manager.go, virtcontainers/persist/manager_test.go, virtcontainers/persist/plugin/README.md, virtcontainers/persist_test.go, virtcontainers/sandbox.go, virtcontainers/sandbox_test.go, virtcontainers/virtcontainers_test.go
Fixes #803
This demonstrate how to use new `virtcontainers/persist/api/` package brought by #874 
<del>This PR is only for demo, please don't merge it. </del>
This is ready for review and merge now :-)
=> persist: baseline persist data format

cli/create.go, containerd-shim-v2/create.go, pkg/katautils/create.go, pkg/katautils/create_test.go, virtcontainers/api.go, virtcontainers/api_test.go, virtcontainers/container.go, virtcontainers/container_test.go, virtcontainers/example_pod_run_test.go, virtcontainers/kata_agent.go, virtcontainers/kata_agent_test.go, virtcontainers/mount.go, virtcontainers/persist.go, virtcontainers/persist/api/container.go, virtcontainers/pkg/oci/utils.go, virtcontainers/pkg/oci/utils_test.go, virtcontainers/sandbox.go, virtcontainers/sandbox_test.go, virtcontainers/types/container.go
We can use the same data structure to describe both of them.
So that we can handle them similarly.
Fixes: #1566
=> vc: change container rootfs to be a mount

versions.yaml
Need to figure out why CI didn't catch and address
package build failure.  In the meantime, unblock 1.6.2.
Fixes: #1571
=> revert kernel bump for 1.6.2 release

versions.yaml
This commit bumps the golang version to remove the go modules hash mismatch between 1.11 and 1.12.
Reasoned by https://github.com/cri-o/cri-o/pull/2247
Fixes #1520
=> Update golang to 1.12.3

cli/create.go, containerd-shim-v2/create.go, pkg/katautils/create.go, pkg/katautils/create_test.go, virtcontainers/api.go, virtcontainers/api_test.go, virtcontainers/container.go, virtcontainers/container_test.go, virtcontainers/example_pod_run_test.go, virtcontainers/kata_agent.go, virtcontainers/kata_agent_test.go, virtcontainers/mount.go, virtcontainers/persist.go, virtcontainers/persist/api/container.go, virtcontainers/pkg/oci/utils.go, virtcontainers/pkg/oci/utils_test.go, virtcontainers/sandbox.go, virtcontainers/sandbox_test.go, virtcontainers/types/container.go
This reverts commit 196661bc0d351daa42b793b75ffdc0b88d3bcf39.
Reverting because cri-o with devicemapper started
to fail after this commit was merged.
Fixes: #1574.
=> Revert "vc: change container rootfs to be a mount"

versions.yaml
This release is based off of QEMU 4.0 and also includes support for
virtio-fs.
Fixes: #1580
Signed-off-by: Rob Bradford <robert.bradford@intel.com>
=> versions: Bump NEMU version to latest release

cli/list.go, cli/list_test.go
kata-runtime list command should list all valid container, not fail
when some containers information uncorrent, like rootfs not found.
Fixes: #1592
=> cli: do not fail on list when some containers bust

containerd-shim-v2/container.go, containerd-shim-v2/service.go, containerd-shim-v2/wait.go
in wait function, should send msg to exit channel after task status has
updated, since shim.Wait() is running in another goroutine, when it
receive msg from exit channel, it will stop waiting and return, then
someone who hold this Wait() get return, it can delete task, if exit msg
is send first, the container status may still be running.
Fixes: #1600 
=> shim v2: fix set status when container exit

virtcontainers/kata_agent.go, virtcontainers/kata_shim.go, virtcontainers/shim.go
The proxy is in charge to print the agent logs, but when `use_vsocks` is true
the runtime doesn't start the proxy, because it's not needed, hence the agent
logs are ignored. To mitigate this limitation and to make the debugging
process easier, the fist shim started (the one who monitors the sandbox)
will read the console.sock and print the agent logs.
Depends-on: github.com/kata-containers/shim#172
fixes #1596
=> virtcontainers: Use shim to print the agent logs if there is no proxy

virtcontainers/Makefile
The virtcontainers `Makefile` was referencing an old script to handle static checks. Although these are still run if `make` is invoked at the top-level, correct the error.
Fixes #1609.
=> build: Fix virtcontainers static check make target

virtcontainers/fc.go
firecracker: Add support for default VM configuration
Kata support specifing the default VM configuration via configuration.toml. This allows the system or cluster admin  to choose the default (i.e minimum) size of the VM.
Add support in kata to respect the VM configuration for firecracker.
Fixes: #1594
=>  firecracker: Add support for default VM configuration

virtcontainers/fc.go
Add support for v0.15.x. Change the drive naming scheme to match
the requirement of v0.15.x
Fixes: #1598
=> firecracker: Add support for v0.15.x

virtcontainers/container.go
In privileged mode, all host devices are supposed to be passed
to the container in config.json. Skip floppy drives.
Fixes #1551
=> devices: Skip floppy drives while passing devices to guest

versions.yaml
=> Firecracker: update to version v0.15.2

virtcontainers/fc.go
Firecracker does not support pci. It also uses kbd to implement reboot/reset.
Fix the kernel boot params to address this.
It also does not have good entropy at startup. Use the hardware random
number generator to support entropy.
Fixes: #1620
=> Firecracker: Fix kernel command line parameters

virtcontainers/qemu_arch_base.go, virtcontainers/qemu_arch_base_test.go
sockets * cores * threads should be equal to maxcpus otherwise a
warning is thrown: 'warning: Invalid CPU topology deprecated:
sockets * cores * threads != maxcpus'
This warning in the future will be an error and won't be possible to run
kata containers.
fixes #1605
=> virtcontainers: fix invalid CPU topology

versions.yaml
Upgrade firecracker to 0.16.0
Fixes: 0.16.0
=> firecracker: Upgrade firecracker to 0.16.0

virtcontainers/fc.go
Setup rootfs to be RO both from the VMM point of view and the
VM point of view.
Fixes: #1632
=> firecracker: Setup rootfs to be RO

virtcontainers/container.go
This change updates the isSystemMount check for mountSharedDirMounts
when setting up shared directory mounts for the container and uses
the source of the mount instead of the destination for the check.
We want to exclude system mounts from the host side as they
shouldn't be mounted into the container.
We do however want to allow system mounts within the
container as denying them can prevent some containers from
running properly.
Fixes #1591
Signed-off-by: Alex Price <aprice@atlassian.com>
=> mounts: fix isSystemMount check for mountSharedDirMounts

versions.yaml
This will update the k8s version to latest 1.14.1 and CRI-O to
commit 3ddde3dee35a239712ee26fa542abe5609c4f44f. We are
using this commit as crio 1.14 has an issue: cri-o/cri-o#2221 
and also does not include test fixes of cri-o/cri-o@7b8c298.
Depends-on: github.com/kata-containers/tests#1528
Fixes #1617
=> versions: Update K8s and CRI-O version

pkg/katatestutils/constraints.go, pkg/katatestutils/constraints_api.go, pkg/katatestutils/constraints_test.go
Fix version comparison bug whereby the specified operator was being applied to the wrong version number.
The version handling for distro and kernel versions was incorrect. This was not clear as the internal logic was rather difficult to understand. Renaming `constraintInvalid()` to `constraintValid()` and updating`NotValid()` correspondingly makes the logic clearer and exposed the bug, allowing it to be fixed.
Added two new tests to ensure correct behaviour:
- `TestConstraintNotValidKernelVersion()`
- `TestConstraintNotValidDistroVersion()`
Also, added the following distro version constraints for parity with the kernel version constraints:
- `NeedDistroVersionGE()`
- `NeedDistroVersionLE()`
- `NeedDistroVersionNotEquals()`
Finally, fixed a comment and reset the internal state of the …
=> Fix test constraint version numbers

pkg/katautils/create.go, pkg/katautils/network.go
when kata container start fails, netns will leak, add a defer func
to fix it
Fixes: #1640
=> vc: fix netns leak

containerd-shim-v2/create.go
Latest containerd commit<c0f0b21314b93a1> had moved the
step of creating rootfs dir from creating bundle to container
creation; in order to support both of the old and latest
containerd, check the "rootfs" existed before creating it.
=> shimv2: create the rootfs dir if it doesn't exist

containerd-shim-v2/create.go, containerd-shim-v2/create_test.go, containerd-shim-v2/service.go
This latest ttrpc vendor supports the feature of request timeout propgation.
this feature will do context cancel after a service call return, and this cancel
will propagated into kata sandbox's agent/hypervisor and resulted in the following
calls canceled. To fix this issue, pass the service's context instead of the service's
call's context to CreateSandbox(), and this context will live until the shim exited.
Fixes:#1627
=> shimv2: fix the issue ttrpc server canceled context

virtcontainers/api.go, virtcontainers/container.go, virtcontainers/container_test.go, virtcontainers/device/api/interface.go, virtcontainers/device/drivers/block.go, virtcontainers/device/drivers/generic.go, virtcontainers/device/drivers/vfio.go, virtcontainers/device/drivers/vhost_user_blk.go, virtcontainers/device/drivers/vhost_user_net.go, virtcontainers/device/drivers/vhost_user_scsi.go, virtcontainers/device/manager/manager.go, virtcontainers/persist.go, virtcontainers/persist/api/device.go, virtcontainers/persist/api/interface.go, virtcontainers/persist/fs/fs.go, virtcontainers/persist/fs/fs_test.go, virtcontainers/persist_test.go, virtcontainers/sandbox.go, virtcontainers/sandbox_test.go, virtcontainers/types/sandbox.go
Fixes #803
It contains several commits:
1. Simplify new store API to make the code easier to understand and use.
2. newstore: remove file "devices.json" 
=> newstore:  removing deprecated files when use new store driver

pkg/katautils/network_test.go
Skip TestHostNetworkingRequested test as nsfs is not supported on
older kernel versions. Currently, CentOS has issues with this test as is using
a kernel version of 3.10 and to run this test we need a kernel version
greater than 3.19.
Fixes #1629
=> test: Skip namespace test on Centos

cli/kata-check.go, cli/kata-check_amd64.go, cli/kata-check_amd64_test.go, cli/kata-check_arm64.go, cli/kata-check_ppc64le.go, cli/kata-check_s390x.go, cli/kata-check_test.go, pkg/katautils/config_test.go, virtcontainers/utils/utils.go, virtcontainers/utils/utils_test.go
In a few host machines, when vhost_vsock isn't built-in, but could be loadable, value `SupportVoscks` from `kata-env` still outputs false.
We add `modprobe -i vhost_vsock` in func `SupportsVsocks` to try to avoid above scenario.
```
[Host]
Kernel = "5.0.7"
Architecture = "arm64"
VMContainerCapable = true
SupportVSocks = true
[Host.Distro]
Name = "Ubuntu"
Version = "18.04"
[Host.CPU]
Vendor = "3rd Party Limited"
Model = "v8"
```
```
[Host]
Kernel = "5.0.7"
Architecture = "arm64"
VMContainerCapable = true
SupportVSocks = false
[Host.Distro]
Name = "Ubuntu"
Version = "18.04"
[Host.CPU]
Vendor = "3rd Party Limited"
Model = "v8"
```
Related: #1195 #581
=> support-vsock: load vhost_vsock module if it isn't built-in

cli/kata-check.go, cli/kata-check_amd64.go, cli/kata-check_amd64_test.go, cli/kata-check_arm64.go, cli/kata-check_ppc64le.go, cli/kata-check_s390x.go, cli/kata-check_test.go, pkg/katautils/config_test.go, pkg/katautils/create.go, pkg/katautils/network.go, virtcontainers/qemu_arch_base.go, virtcontainers/qemu_arch_base_test.go, virtcontainers/utils/utils.go, virtcontainers/utils/utils_test.go
This stable backport includes the below changes.
https://github.com/kata-containers/runtime/pull/1513
https://github.com/kata-containers/runtime/pull/1606
https://github.com/kata-containers/runtime/pull/1641
The below changes marked as `stable-candidate` were not included cause of missing base changes.
https://github.com/kata-containers/runtime/pull/1623 
https://github.com/kata-containers/runtime/pull/1628
https://github.com/kata-containers/runtime/pull/1630
https://github.com/kata-containers/runtime/pull/1651
=> backports: Bp 1.6.4 rel

virtcontainers/sandbox.go
Network namespace needs to be propagated if available at
createSandbox()
Fixes: #1664
=> Networking: Ensure that network namespace is propagated

pkg/katautils/create.go
There are still some systemd units that fail to start for different
reasons. Disable these systemd units to improve boot time.
fixes #1686
cc @grahamwhaley 
=> pkg/katautils: improve boot time disabling systemd units

virtcontainers/network.go
Fixes: #1673
Signed-off-by: Zha Bin <zhabin@linux.alibaba.com>
=> network: delete IP addrs on bridge model to prevent ARP conflict

versions.yaml
Now that CRI-O released a new version we can update it.
Fixes #1696
=> versions: Update CRI-O version to 1.14.1

virtcontainers/qemu_s390x.go
Remove time package because not used
Fixes: #1680
=> s390x: fix compile error for 1.6.3

virtcontainers/kata_proxy.go
Got a defunct kata-proxy after kata quit when VMCache is enabled.
The reason is vmcache server opens kata-proxy but doesn't wait it.
If VMCache is disabled, kata-runtime will quit before kata-proxy.
So it will not meet the issue.
Open a special goroutine do cmd.Wait in kataProxy.start to handle
the isssue.
Fixes: #1678
=> kata_proxy: Open a special goroutine do cmd.Wait

versions.yaml
Set the minimum golang version to 1.11.10, the latest stable 1.11 version
at the time of writing. Go 1.11 is required to build the agent with working
vsock support.
Fixes: #1693
=> versions: Update golang to 1.11.10

virtcontainers/qemu.go
When hugepage is not enabled, virtiofsd fails to setup vq with qemu and it causes qemu process to hang forever. waitSandbox only checks qmp so cannot detect such failure. Add virtiofsd debug log and stop qemu if virtiofsd quits.
=> Add virtiofsd log and fix qemu hang due to virtiofsd vq setup failure

pkg/katautils/create.go
The systemd units and files that are not needed in Kata Containers,
are removed when the image is created, therefore we don't need to mask
them.
fixes #1704
=> katautils: don't mask systemd units

virtcontainers/pkg/oci/utils_test.go
Fix the test case TestGetShmSizeBindMounted by
setting the right ShmSize for ppc64le.
Fixes: #1702
=> virtcontainers: Set correct Shmsize for ppc64le

virtcontainers/api.go, virtcontainers/network.go, virtcontainers/qemu.go, virtcontainers/sandbox.go
If kata containers is using vfio and vhost net，the unbinding
of vfio would be hang. In the scenario, vhost net kernel thread
takes a reference to the qemu's mm, and the reference also includes
the mmap regions on the vfio device file. so vhost kernel thread
would be not released when qemu is killed as the vhost file
descriptor still is opened by shim v2 process, and the vfio device
is not released because there's still a reference to the mmap.
Fixes: #1669
Signed-off-by: Yang, Wei <w90p710@gmail.com>
=> shim v2: Close vhostfd after vm get vhostfd

virtcontainers/qemu_ppc64le_test.go
Set test qemu major/minor version when
running unit test TestQemuPPC64leMemoryTopology
Fixes: #1308
=> virtcontainers: Set test qemu version for unit test

.ci/static-checks.sh
We need to build kata-runtime to have the correct files
in place to be able to run the static checks script.
Fixes #1716.
=> ci: Build kata-runtime before running static checks

containerd-shim-v2/container.go, containerd-shim-v2/delete.go, containerd-shim-v2/service.go, containerd-shim-v2/wait.go
For k8s, once all of the containers in a pod terminated, the pod status would be set "Succeeded" or "Failed" according the containers exited status, in any case, kubelet would consider the pod has terminated, and would try to cleanup the pod cgroup resources, which means kubelet would kill all of the processes in the pod cgroups, thus the qemu process would be killed by accident, at a result, kata shimv2 wouldn't communicate with qemu to do some sandbox cleanup and left the shimv2 process there.
This patch will try to fix this issue by moving "stop sandbox" from deleting podsandbox container stage to the time when podsandbox container exited and before kubelet detect the podsandbox container exited, thus kubelet wouldn't kill the hypervisor process.
=> fix the issue of hypervisor process is killed by kubelet 

containerd-shim-v2/create.go, containerd-shim-v2/service.go
```
//the network namespace created by cni plugin
netns, err = namespaces.NamespaceRequired(ctx)
if err != nil {
return nil, errors.Wrap(err, "create namespace")
}
```
the netns is a containerd namespace concept, it not netns, event a cni
set netns for this, this is a tricky way, so remove the logic.
Fixes: #1692
=> shimv2: remove use containerd ns as netns

versions.yaml
Use only one version to install cri-contaienrd
- version could be a containerd version or a commit of the cri
repository.
Fixes: #1464
=> versions: Update cri-containerd  yaml

versions.yaml
virtio-fs is now available in 1.7 release and needs hugepages enabled.
NEMU's machine_type `virt` has issues getting network access when
hugepages is enabled. Temporarily changing type to `pc` to fix this
issue. Accompanying changes to runtime and tests are underway.
Fixes: #1709
=> nemu: update nemu version

data/kata-collect-data.sh.in
The rootfs image was fixed, now the DAX metadata and 2 MBRs headers are part
of the same image. Mounting the rootfs partiton with an offset of 2M is no
more needed, since the first MBR is read by partx or losetup by default.
fixes #1443
cc @jodh-intel 
Signed-off-by: Julio Montes julio.montes@intel.com
=> data: Revert pull request #1405

virtcontainers/fc.go, virtcontainers/sandbox.go
Make sure the hypervisor is stopped if startSandbox does not succeed, by calling stopSandbox.
Fixes: #1636
=> virtcontainers: kill hypervisor if startSandbox fails

data/kata-collect-data.sh.in
Use `kata-containers.runtime` that is the runtime binary, to
collect the data if the kata-runtime binary is not installed
fixes #1720
=> data/kata-collect-data: support kata containers snap

pkg/katautils/create.go
Here we have done with logger and container ID map
Just delete these code.
fixes #1740
Signed-off-by: Haomin Tsai <caihaomin@huawei.com>
=> runtime : delete redundant code in CreateContainer

cli/config/configuration-qemu.toml.in, pkg/katautils/config-settings.go, pkg/katautils/config.go, virtcontainers/hypervisor.go, virtcontainers/persist/api/config.go, virtcontainers/qemu.go, virtcontainers/qemu_test.go
A file based memory backend mapped to the host, fot eg: '/dev/shm' will
be used by virtio-fs for performance reasons. This change is a generic
implementation of that for kata. This will be enabled default for
virtio-fs negating the need to enable hugepages in that scenario. This
option can be used without virtio-fs by setting 'file_mem_backend' to
the location in the configuration file. Default value is an empty
string.
Fixes: #1656
=> runtime: Enable file based backend

.ci/static-checks.sh
We need to build kata-runtime to have the correct files
in place to be able to run the static checks script.
Fixes #1716.
=> backport 1.7: ci: Build kata-runtime before running static checks

.ci/static-checks.sh
We need to build kata-runtime to have the correct files
in place to be able to run the static checks script.
Fixes #1716.
=> backport: ci: Build kata-runtime before running static checks

virtcontainers/qemu_amd64.go, virtcontainers/qemu_amd64_test.go
Turn off VMX if vm-factory is enabled since it's not migratable yet.
see https://bugzilla.redhat.com/show_bug.cgi?id=1689216
fixes #1747
=> virtcontainers: support vm factory in QEMU 4

cli/config/configuration-fc.toml.in
proxy will never be use with the Firecracker VMM. Keeping this header
will result in runtime failures, since the configuration will be parsed
on the path searched for.
Since vsock will always be used, remove the proxy section.
Fixes: #1761
=> fc-toml: remove proxy section in config

README.md
Update the README explaining that Kata Containers are Linux-based and run on Linux hosts.
Fixes: #1759.
=> docs: Explain Kata Containers are Linux-based

virtcontainers/qemu_ppc64le.go
We need to add a few extra defaultQemuMachineOptions
for ppc64le for kata to work with  qemu 4.0 version.
Fixes: #1771
=> vc: Add some defaultQemuMachineOptions for qemu 4.0

cli/factory.go, pkg/katautils/config.go, pkg/katautils/create.go, virtcontainers/factory/factory.go, virtcontainers/factory/template/template.go, virtcontainers/factory/template/template_test.go
As virtio v1.1 spec states:
The guest_cid configuration field MUST be fetched to determine the current CID when a VIRTIO_VSOCK_EVENT_TRANSPORT_RESET event is received.
Existing connections MUST be shut down when a VIRTIO_VSOCK_EVENT_TRANSPORT_RESET event is received.
Listen connections MUST remain operational with the current CID when a VIRTIO_VSOCK_EVENT_TRANSPORT_RESET event is received.
We should be able to use vm templating together with vsock easily, as
qemu already sends VIRTIO_VSOCK_EVENT_TRANSPORT_RESET event to guest.
=> factory: make vm templating work with vsock

Makefile
hugepages were enbled by default on NEMU to allow use of virtio-fs. kata
now has a change where virtio-fs will default to use /dev/shm as the
shared memory file backing location. With that, we should be able to
disable default hugepages for NEMU
Fixes: #1775
=> Disable default hugepages enabling for virtio-fs

Makefile
hugepages were enbled by default on NEMU to allow use of virtio-fs. kata
now has a change where virtio-fs will default to use /dev/shm as the
shared memory file backing location. With that, we should be able to
disable default hugepages for NEMU
Fixes: #1775
(cherry picked from commit a75db860277d9127f96574f9c413980f99e49a1e)
=> NEMU: Disable default hugepages enabling for virtio-fs

containerd-shim-v2/stream.go
our testing found that the client does not open
stdin with O_WRONLY, so the shim v2 was blocked forever
in open stdin with O_RDONLY. It's better to make it
opened with O_NONBLOCK, and do not block starting process
of container. and the containerd runc shim has done this
by bc1ff514 as well.
Signed-off-by: Yang, Wei <w90p710@gmail.com>
Signed-off-by: Yang, Wei <wei.yang1@linux.alibaba.com>
=> Use O_NONBLOCK for tty stdin.

virtcontainers/fc.go, virtcontainers/hypervisor.go, virtcontainers/qemu_amd64.go, virtcontainers/qemu_arm64.go, virtcontainers/qemu_s390x.go
Let's make this option consistent cross all archs, since from a security point of view, there is no need
for us to write to the rootfs.
Fixes: #1642
=> kernelRootParams: define agnostic commonkernelRootParams

pkg/katautils/hook.go
detail how kata work with libnetwork
1. kata create a new netns
2. with EnterNS, kata change netns to the created one.
3. in pre-start hook, kata will re-exec libnetwork process
libnetwork-setkey, and send self pid to it. libnetwork use
/proc/pid/ns/net to find the netns kata use, and set veth into the netns.
v1/v2 shim use the same way to create network, v1 can successful
because EnterNS changed both current thread and main thread's netns.
But use v2 shim, only changed current thread netns, main thread still
use host netns, so it fails. Looks like v1 just lucky to be successful.
In kata, `state.Pid` should be tid.
Fixes: #1788
=> katautils: fix shim v2 fail to work with libnetwork

Gopkg.lock, vendor/github.com/hashicorp/errwrap/LICENSE, vendor/github.com/hashicorp/errwrap/README.md, vendor/github.com/hashicorp/errwrap/errwrap.go, vendor/github.com/hashicorp/errwrap/errwrap_test.go, vendor/github.com/hashicorp/errwrap/go.mod, vendor/github.com/hashicorp/go-multierror/.travis.yml, vendor/github.com/hashicorp/go-multierror/LICENSE, vendor/github.com/hashicorp/go-multierror/Makefile, vendor/github.com/hashicorp/go-multierror/README.md, vendor/github.com/hashicorp/go-multierror/append.go, vendor/github.com/hashicorp/go-multierror/append_test.go, vendor/github.com/hashicorp/go-multierror/flatten.go, vendor/github.com/hashicorp/go-multierror/flatten_test.go, vendor/github.com/hashicorp/go-multierror/format.go, vendor/github.com/hashicorp/go-multierror/format_test.go, vendor/github.com/hashicorp/go-multierror/go.mod, vendor/github.com/hashicorp/go-multierror/go.sum, vendor/github.com/hashicorp/go-multierror/multierror.go, vendor/github.com/hashicorp/go-multierror/multierror_test.go, vendor/github.com/hashicorp/go-multierror/prefix.go, vendor/github.com/hashicorp/go-multierror/prefix_test.go, vendor/github.com/hashicorp/go-multierror/sort.go, vendor/github.com/hashicorp/go-multierror/sort_test.go, virtcontainers/api_test.go, virtcontainers/mount.go, virtcontainers/mount_test.go
Add error handling surrounding the syscall of unmounting the
container rootfs
Fixes: #164
Signed-off-by: gabrielle beyer <gabrielle.n.beyer@intel.com>
=> vc: error handling for bindUnmount functionalities

pkg/katautils/hook.go
detail how kata work with libnetwork
1. kata create a new netns
2. with EnterNS, kata change netns to the created one.
3. in pre-start hook, kata will re-exec libnetwork process
libnetwork-setkey, and send self pid to it. libnetwork use
/proc/pid/ns/net to find the netns kata use, and set veth into the netns.
v1/v2 shim use the same way to create network, v1 can successful
because EnterNS changed both current thread and main thread's netns.
But use v2 shim, only changed current thread netns, main thread still
use host netns, so it fails. Looks like v1 just lucky to be successful.
In kata, `state.Pid` should be tid.
Fixes: #1788
=> [cherry-pick 1.6]: katautils: fix shim v2 fail to work with libnetwork

virtcontainers/qemu_ppc64le.go
TestQemuPPC64leMemoryTopology fails on ppc64le
as the corect qemu version is not detected.
Fixes: #1790
=> vc: Fix TestQemuPPC64leMemoryTopology after qemu version bump

pkg/katautils/hook.go
detail how kata work with libnetwork
1. kata create a new netns
2. with EnterNS, kata change netns to the created one.
3. in pre-start hook, kata will re-exec libnetwork process
libnetwork-setkey, and send self pid to it. libnetwork use
/proc/pid/ns/net to find the netns kata use, and set veth into the netns.
v1/v2 shim use the same way to create network, v1 can successful
because EnterNS changed both current thread and main thread's netns.
But use v2 shim, only changed current thread netns, main thread still
use host netns, so it fails. Looks like v1 just lucky to be successful.
In kata, `state.Pid` should be tid.
Fixes: #1788
=> [cherry-pick 1.7]: katautils: fix shim v2 fail to work with libnetwork

virtcontainers/experimental/README.md
Fix an internal markdown document link.
Fixes: #1803.
=> docs: Fix doc link

pkg/katautils/tracing.go
Add a log message for every trace span created, required by the tracing tests to validate tracing is working.
Fixes: #1814.
=> trace: Add missing log message

Makefile
shimv2 binary was not being built in case of any source changes.
Add dependency of source files to the shimv2 make target to fix this.
Fixes #1805
=> shimv2: Make shimv2 in case any source files change

versions.yaml
Update to newer stable kernel
Fixes: #1816
Depends-on: github.com/kata-containers/packaging#592
=> versions: update kernel to 4.19.52

virtcontainers/README.md
Kubernetes moved CRI document within the sig-node directory. Updating
README.md accordingly.
Fixes: 1837
=> vc: update CRI link

virtcontainers/kata_agent.go, virtcontainers/kata_agent_test.go
With #1485, we moved the default medium empty-dir creation to the
sandbox rootfs. This worked for devicemapper, but in case of overlay
the "local" directory was being created outside the sandbox rootfs.
As a result we were seeing the behaviour seen in #1818.
Fixes #1818
=> empty-dir: Fix bug in the way empty-dirs are handled for overlay

virtcontainers/README.md
The old one was invalidated since 2019-07-01.
Fixes: #1847
=> vc/readme: fix cri url

containerd-shim-v2/metrics.go
This fixes #1856
Signed-off-by: Odin Ugedal <odin@ugedal.com>
=> shimv2: Add missing page size to Hugetlb Stat

.ci/versions_checker.sh, .travis.yml
This will take the VERSION of all the components in order to
verify that they match among them before merging the runtime.
Fixes #1581
Depends-on: github.com/kata-containers/packaging#614
=> ci: Verify and block merge if other projects are not updated

virtcontainers/qemu_test.go, virtcontainers/sandbox_test.go
Fixed `TestSandboxCreationFromConfigRollbackFromCreateSandbox` which requires that the hypervisor does not exist. Unfortunately, it does exist (as a fake test binary), but isn't executable meaning although the test failed (since an error is expected), rather than the expected `ENOENT` error, the test was logging a message similar to the following since the fake hypervisor exists with non-executable permissions:
```
Unable to launch /tmp/vc-tmp-526112270/hypervisor: fork/exec /tmp/vc-tmp-526112270/hypervisor: permission denied
```
Update the `TestQemuAddDeviceKataVSOCK` test so that it:
- Doesn't hard-code the file descriptor number.
- Cleans up after itself.
The latter issue was causing an odd error similar to the following in the test output:
```
Unable to launch …
```
=> Fix fork exec test errors

.ci/versions_checker.sh, .travis.yml
This will take the VERSION of all the components in order to
verify that they match among them before merging the runtime.
Fixes #1581
=> backport: Verify and block merge if other projects are not updated

versions.yaml
Fixes #1866
Relates to https://github.com/kata-containers/tests/pull/1778
=> versions: update CRI-O to v1.14.6

versions.yaml
This PR relates to https://github.com/kata-containers/tests/pull/1778
Fixes #1872
=> versions: add crictl version which is compatible with OpenShift

virtcontainers/qemu.go
Kata with virtio-fs fails to do memory hotplugging. This is caused by
the fact that hot plugged memory is always backed by
'memory-backend-ram' while virtio-fs expects it to be backed by file and
shared for it to be able to use the system the way it is intended. This
chnage allows using file based memory backend for virtio-fs, hugepages
or when the user prefers to use a file backed memory
Fixes: #1745
=> virtiofs: Allow memory hotplug with virtiofs

virtcontainers/qemu.go, virtcontainers/qemu_amd64.go, virtcontainers/qemu_arch_base.go, virtcontainers/qemu_arm64.go, virtcontainers/qemu_ppc64le.go, virtcontainers/qemu_s390x.go, virtcontainers/qemu_test.go
As we want to move to upstream qemu, we should drop as many private qemu patches as possible. One big change we carry with qemu-lite is the migration bypass-shared-memory patch. Qemu 4.0 already has a x-ignore-shared migration capability. With a small change to it, we can make it work similar to bypass-shared-memory and thus get rid of the private qemu patch. Then we can use x-ignore-shared instead of bypass-shared-memory to implement the VM template feature.
=> qemu: use x-ignore-shared to implement vm template

Gopkg.lock, Gopkg.toml, containerd-shim-v2/metrics.go, vendor/github.com/intel/govmm/qemu/qemu.go, vendor/github.com/intel/govmm/qemu/qemu_arch_base.go, vendor/github.com/intel/govmm/qemu/qmp.go, virtcontainers/qemu.go, virtcontainers/qemu_amd64.go, virtcontainers/qemu_arch_base.go, virtcontainers/qemu_arm64.go, virtcontainers/qemu_ppc64le.go, virtcontainers/qemu_s390x.go, virtcontainers/qemu_test.go
The following fixes landed on master since RC0 and should be included:
c192343c virtiofs: Allow memory hotplug with virtiofs
0a18fba3 runtime: Disable disable-modern for virtio QMP add
0d7b9819 vendor: update govmm and match code
c980da47 test: Fix fd leak causing test error
5628825a shimv2: Add missing page size to Hugetlb Stat
qemu: use x-ignore-shared to implement vm template
=> Backports for 1.8

virtcontainers/mount_test.go, virtcontainers/sandbox_test.go
1. 
```
=== RUN   TestStartNetworkMonitor
--- FAIL: TestStartNetworkMonitor (0.00s)
Error Trace:    sandbox_test.go:1481
Error:          Expected nil, but got: &errors.errorString{s:"Error switching to ns /proc/6648/task/6651/ns/net: operation not permitted"}
```
2.
```
=== RUN   TestBindUnmountContainerRootfsENOENTNotError
--- FAIL: TestBindUnmountContainerRootfsENOENTNotError (0.00s)
Error Trace:    mount_test.go:360
Error:          Expected nil, but got: 0x1
```
They should both be skipped with non-root.
=> Fix UT failures with non-root

Gopkg.lock, Gopkg.toml, vendor/github.com/intel/govmm/qemu/qmp.go, virtcontainers/qemu.go
CPU topology has changed in QEMU 4.1: socket > die > core > thread.
die option must be specified in order to hotplug CPUs on x86_64
Depends-on: github.com/kata-containers/packaging#657
fixes #1913
=> virtcontainers: support SMP die

versions.yaml
Bump CI to kubernetes 1.15.
Fixes: #1860
=> versions: Upgrade to k8s 1.15

.gitignore
Add acrn's generated configuration toml file to the gitignore list.
Fixes: #1927
=> acrn: Add toml to gitignore

virtcontainers/kata_agent.go
When virtio_fs_cache is set to none, the mount options for the folder
inside the guest should not contain the dax option else it leads to
invalid address errors and a crash of the daemon on the host.
Fixes: #1907
=> virtiofs: fix virtiofs crash when cache=none

pkg/katautils/create.go
Currently kata sets the init process to systemd even when it isn't installed,
the criteria to determinate whether systemd is used as init or not
is very odd, since kata only checks whether the `image` option is set in the
configuration file, unfortunately not all images have systemd installed.
Instead kata should rely on the guest kernel and `osbuilder` to use the right
init process. `osbuilder` creates a symbolic link to `systemd` or `kata-agent`
depending on the `AGENT_INIT` environment variable.
fixes #1937
=> pkg/katautils: Do not set `init` in the kernel command line

virtcontainers/qemu.go
We start virtiofsd in foreground (-f option), so we should wait for it
to reclaim its resources to avoid zombie process when qemu or virtiofsd
got killed unexpectedly.
Fixes: #1934
Signed-off-by: Eryu Guan <eguan@linux.alibaba.com>
=> virtiofs: wait for virtiofsd process to release its resources

containerd-shim-v2/wait.go
Fixes: #1929
in containerd-kata-v2, container can only be deleted in Delete
interface, or other shim operates(like kill/delete) all fails
since can not get container info.
=> shim-v2: fix shim leak when hypervisor exit unexpectly

virtcontainers/api.go
in create sandbox, if process error, should remove network without judge
NetNsCreated is true, since network is created by kata and should be
removed by kata, and network.Remove has judged if need to delete netns
depend on NetNsCreated
Fixes: #1920
=> network: fix failed to remove network

netmon/netmon.go, virtcontainers/network.go
Routes with proto "kernel" are routes that are automatically added
by the kernel.
It is a route added automatically when you assign an address to an
interface which is not /32.
With this commit, these routes are ignored. The guest kernel
would add these routes on the guest side. A corresponding commit on the
agent side would no longer delete these routes while updating them.
Without this commit, netlink gives an error complaining that a route
already exists when you try to add a route with the same dest subnet.
Something like:
dest: 192.168.1.0/24 device:net1 source:192.168.1.217 scope:253
dest: 192.168.1.0/24 device:net2 source:192.168.1.218 scope:253
Fixes: #1811
=> network: Ignore routes with proto as "kernel"

versions.yaml
52 is long in the tooth.  On to x.y.65!
Fixes: #1947
=> versions: kernel: update to 4.19.65

virtcontainers/utils/utils_linux.go
Make error handling better by propogating error.
Fixes #1953
=> vsock: Propogate error for vsock ioctl

virtcontainers/sandbox.go
We might need to call hypervisor hotunplug to really remove
a network device. We cannot do it after stopping the VM.
Fixes: #1956
Signed-off-by: Peng Tao <bergwolf@hyper.sh>
=> sandbox: remove network before stopping vm

virtcontainers/container.go
We can only pause a running container.
Fixes: #1960
=> container: do not pause a StateReady container

virtcontainers/kata_agent.go
If guest is malfunctioning, we need a way to bail out. Add
a default timeout for most of the grpc requests so that the
runtime does not wait indefinitely.
Fixes: #1952
=> agent: add default timeout for grpc requests

virtcontainers/network.go, virtcontainers/sandbox.go
#1957 is problematic that it causes vfio nic passthrough to fail, because we need to bind the device back to host and that is not possible when qemu is still running. So we should revert it.
And to fix the original issue #1956, we can just skip hotunplug all together as it is not really necessary when stopping a vm.
=> do not hotplug network device when stopping sandbox

virtcontainers/qemu.go
We've cleaned it up the first time. Future stop will
only fail.
Fixes: #1958
=> qemu: do not try to stop qemu multiple times

pkg/katautils/config.go, virtcontainers/kata_builtin_proxy.go, virtcontainers/kata_builtin_proxy_test.go, virtcontainers/no_proxy.go, virtcontainers/proxy.go
For no proxy type, we also need the feature
of watch hypervisor's console to help debug.
Fixes:#1932
=> add watchconsole for no_proxy type

versions.yaml
Update qemu version to bring the latest fixes and improvements:
* migration: allow private destination ram with x-ignore-shared
* hw/i386: Fix linker error when ISAPC is disabled
* hw/i386: turn off vmport if CONFIG_VMPORT is disabled
Depends-on: github.com/kata-containers/packaging#680
fixes #1978
=> versions: update version of qemu to 4.1.0

virtcontainers/proxy.go
Since firecracker hasn't support console watching by now, so skip
watching console if the consoleURL is empty.
Fixes: #1970
=> virtcontainers: Fix the issue of watching console for firecracker

virtcontainers/acrn.go, virtcontainers/cgroups.go, virtcontainers/fc.go, virtcontainers/hypervisor.go, virtcontainers/kata_agent.go, virtcontainers/mock_hypervisor.go, virtcontainers/persist/api/hypervisor.go, virtcontainers/persist/api/version.go, virtcontainers/qemu.go, virtcontainers/qemu_test.go, virtcontainers/vm.go
Right now virtiofsd daemon is not in sandbox cgroup. We should add it to the same cgroup as the qemu main process.
Before fix:
```
$sudo cat /proc/101318/cgroup
12:pids:/system.slice/containerd.service
11:rdma:/
10:net_cls,net_prio:/
9:memory:/system.slice/containerd.service
8:freezer:/
7:blkio:/system.slice/containerd.service
6:cpu,cpuacct:/system.slice/containerd.service
5:perf_event:/
4:devices:/system.slice/containerd.service
3:cpuset:/
2:hugetlb:/
1:name=systemd:/system.slice/containerd.service
0::/system.slice/containerd.service
```
After fix:
```
$sudo cat /proc/99841/cgroup
12:pids:/system.slice/containerd.service
11:rdma:/
10:net_cls,net_prio:/
9:memory:/kata/docker/kata_84b5062407c3b2a8dde2bf51391f553362fb5f81a8ac1d7d891dcdd61c832fb2
8:freezer:/ …
```
=> add virtiofsd to sandbox cgroup

virtcontainers/sandbox.go, virtcontainers/sandbox_test.go
When create container failed, it should delete the container
config from sandbox, otherwise, the following new creating container
would get a wrong resources caculating which would contain the previous
failed container resources such as memory and cpu.
Fixes: #1997
=> Fix the issue of update resources wrong

virtcontainers/qemu.go
strErr is qemu log message, should add err in error message, or if fail
before launch qemu, can not get corrent message.
Fixes: #1991
=> qemu: fix error message miss

containerd-shim-v2/delete.go, containerd-shim-v2/utils.go, containerd-shim-v2/wait.go, virtcontainers/api.go, virtcontainers/api_test.go, virtcontainers/implementation.go, virtcontainers/interfaces.go, virtcontainers/pkg/vcmock/mock.go, virtcontainers/pkg/vcmock/sandbox.go, virtcontainers/pkg/vcmock/types.go, virtcontainers/sandbox.go
When shimv2 was killed by accident, containerd would try to
launch a new shimv2 binarry to cleanup the container. In order
to avoid race condition, the cleanup should be done serialized
in a sandbox. Thus adding a new api to do this by locking the
sandbox.
Fixes:kata-containers#1832
=> api: add a CleanupContainer api for VC

containerd-shim-v2/service.go
If an exec is failed(such as executable file not found in $PATH), the `execs.id` will be empty. This leads to all the container processes being killed when calling `Kill` on such exec id.
Fixes: #2001
=> v2: Prevent killing all container processes when exec is failed

cli/kata-check_amd64.go, cli/kata-check_test.go
KVM modules are required when using QEMU or firecracker.
Fixes: #1985
=> kata-check: require kvm modules for amd64

containerd-shim-v2/service.go, pkg/katautils/create.go, versions.yaml, virtcontainers/api.go, virtcontainers/container.go, virtcontainers/kata_agent.go, virtcontainers/mount_test.go, virtcontainers/network.go, virtcontainers/qemu.go, virtcontainers/sandbox.go, virtcontainers/sandbox_test.go
179485f9 v2: Prevent killing all container processes when exec is failed
7e77b754 qemu: fix error message miss
05c8b02f virtcontainers: cleanup the container config once failed
a85252e8 virtcontainers: remove the redundant sandbox config store
5737f803 qemu: do not try to stop qemu multiple times
09036394 agent: add default timeout for grpc requests
6af47f62 network: always cold unplug network devices
7a690b0e container: do not pause a StateReady container
e1be3263 virtcontainers: fix hotplug pci devices execeed max capacity bug
f43e18be versions: kernel: update to 4.19.65
1cf69cd5 network: fix failed to remove network
83bb7b30 pkg/katautils: Do not set `init` in the kernel command line
4179bf7e ut: skip TestBindUnmountContainerRootfsENOENTNotError for non-root
50f48bb8 ut: skip …
=> Stable 1.8 backports2

Gopkg.lock, Gopkg.toml, vendor/github.com/intel/govmm/qemu/qemu.go, vendor/github.com/intel/govmm/qemu/qemu_arch_base.go, vendor/github.com/intel/govmm/qemu/qemus390x.go
s389x doesn't support dimm and we need to skip it.
Fixes: #2003
detail commit change:
9463486 s390x: dimm not supported
=> vendor: update govmm

virtcontainers/pkg/oci/utils.go, virtcontainers/pkg/oci/utils_test.go
Casting in golang doesn't return a pointer to the structure, instead a new
structure is instantiated. This patch is to update the old structure with
the new one in order to apply the changes.
fixes #2016
=> virtcontainers: fix kernel modules annotations

virtcontainers/container.go, virtcontainers/sandbox.go, virtcontainers/sandbox_test.go, virtcontainers/store/vc.go
The container store should be deleted when new/create is failed if the store is newly created.
Fixes: #2013
=> vc: Delete store when new/create container is failed

cli/main_test.go, containerd-shim-v2/utils_test.go, pkg/katautils/container_engine.go, pkg/katautils/utils_test.go
Refactor unit test so that podman can be used to run tests when docker
is not available.
Fixes: #2006
=> tests: allow running unit tests using podman

virtcontainers/utils/utils_linux.go, virtcontainers/utils/utils_linux_generic.go, virtcontainers/utils/utils_linux_ppc64le.go
Set the right VHOST_VSOCK_SET_GUEST_CID when
running on ppc64le arch
Fixes: #1988
=> vsock: set VHOST_VSOCK_SET_GUEST_CID for ppc64le

versions.yaml
Hi~ guys. I'm back. 😎
I found that the latest stable version for kubernetes, v1.15.3, has finally cherry-picked this significant     
commit [820a717](https://github.com/kubernetes/kubernetes/commit/820a717bce3ef92f9280a4870d449c1e903255f2), which means that crash of `kubeadm init` on AArch64 since kubernetes v1.14.0 has finally got fixed in stable branch, see detailed info [here](https://github.com/kata-containers/tests/issues/1726)
So I'd like to get a formal version update in Kata Conbtainers.
=> kubernetes: update kubernetes to v1.15.3 for AArch64

cli/create.go, cli/create_test.go, cli/delete_test.go, cli/exec.go, cli/exec_test.go, cli/main_test.go, cli/run_test.go, cli/start_test.go, containerd-shim-v2/container.go, containerd-shim-v2/create.go, containerd-shim-v2/create_test.go, containerd-shim-v2/delete_test.go, containerd-shim-v2/service.go, containerd-shim-v2/utils.go, containerd-shim-v2/utils_test.go, pkg/katautils/create.go, pkg/katautils/create_test.go, pkg/katautils/hook.go, pkg/katautils/hook_test.go, virtcontainers/pkg/oci/utils.go, virtcontainers/pkg/oci/utils_test.go, virtcontainers/types/sandbox.go
Fixes: #2023 
CompatOCISpec is used to gurantee backward compatbility for old runtime
specs, after we convert CompatOCISpec to standard specs.Spec, we should
use specs.Spec instead of CompatOCISpec, and CompatOCISpec should be
useless from then.
Spread usage of CompatOCISpec can make code structure confusing and making
the runtime spec usage non-standard. Besides, this can be the very first
step of removing CompatOCISpec from config's Annotations field.
Signed-off-by: Wei Zhang <weizhang555.zw@gmail.com>
=> CompatOCISpec: limit usage of CompatOCISpec

virtcontainers/acrn_arch_base.go
With MacVTap internetworking, Kata fails to launch containers
with ACRN hypervisor. This was due to missing MAC address as
part of virtio-net device when launching VM. This patch fixes
this issue by adding the MAC address.
Fixes: #2029
Signed-off-by: Vijay Dhanraj <vijay.dhanraj@intel.com>
=> hypervisor: Fix MacVTap internetworking support in ACRN

virtcontainers/qemu.go, virtcontainers/qemu_arch_base.go, virtcontainers/qemu_s390x.go
Reimplementation of appendVSock in order to assign the devno to the vsock device.
Fixes: #2033
=> s390x: add appendVSock with devno

virtcontainers/qemu_s390x.go
Add appendImage function to struct qemuS390x, so that a call of
appendImage results in a call to the appendBlockDevice function of
qemuS390x instead of qemuArchBase.
Fixes: #2043
Signed-off-by: Jan Schintag <jan.schintag@de.ibm.com>
=> s390x: Add appendImage function to qemu_s390x.go

virtcontainers/kata_agent.go
Sandbox has network but not dns. Set
dns in the sandbox.
Depends-on: github.com/kata-containers/agent#625
Fixes: #1603
=> virtcontainers: Set sandbox dns in sandbox request

versions.yaml
This adds QEMU and the kernel with virtiofs 3.0 at the versions.yaml
file.
Depends-on: github.com/kata-containers/packaging#710
Fixes #2051
=> version: Add QEMU and kernel with virtiofs 3.0

versions.yaml
This includes fix for CVE-2019-14835
Fixes: # 2062
=> kernel: update to v4.19.73

Gopkg.lock, Gopkg.toml, vendor/github.com/intel/govmm/qemu/qemu.go, virtcontainers/device/config/config.go, virtcontainers/qemu_arch_base.go, virtcontainers/qemu_s390x.go
This commit enables the `share-rw` flag for the image file in s390x.
This enables multiple instances of qemu to share the same image.
Fixes: #2049
Signed-off-by: Jan Schintag <jan.schintag@de.ibm.com>
=> s390x: Share image between qemu instances

Makefile, cli/config/configuration-qemu-virtiofs.toml.in
This will fix the qemu-virtiofs.toml to use the kernel with virtiofs.
Also removes the initrd image from the toml.
Depends-on: github.com/kata-containers/packaging#731
Fixes #2077
=> config: Fix the qemu-virtiofs.toml

virtcontainers/qemu.go
When 'debug' is enabled, qemu's debug info is output
into qemu's log file. When lauching qemu failed, it's
better to return those debug info for debugging.
Fixes:#2042
=> virtcontainers: fix the issue of missing qemu error logs

virtcontainers/qemu_s390x.go
Add the missing migration from kataVSOCK to types.VSock (see #2050) for s390x.
Fixes: #2086
Signed-off-by: Jan Schintag <jan.schintag@de.ibm.com>
=> s390x: Fix runtime build for s390x

virtcontainers/qemu_amd64.go, virtcontainers/qemu_amd64_test.go, virtcontainers/qemu_arm64.go, virtcontainers/qemu_arm64_test.go
Do not add the "nvdimm" machine option to QEMU when the config specifies
a initrd file.
For arm64, this allows using a vanilla QEMU, where "virt" machine does
not support the "nvdimm" option.
Fixed: #2088
=> QEMU: do not require nvdimm machine option with initrd

virtcontainers/fc.go, virtcontainers/hypervisor.go, virtcontainers/qemu.go
Unmount and unassign block device when it's required, that way the disk
can be unmounted and destroyed in the host.
fixes #1966
=> Fix CRIO + Firecracker

pkg/katautils/config.go, virtcontainers/api_test.go, virtcontainers/hypervisor.go, virtcontainers/pkg/annotations/annotations.go, virtcontainers/pkg/oci/utils.go, virtcontainers/pkg/oci/utils_test.go
annotations: Support annotations to customise kata config
Add support for annotations that allow us to custimise a subset
of the configurations provided in kata conf toml file.
This initial commit adds support for customising vcpus, default max
vcpus, memory and the kernel command line passed as Hypervisor
config.
Replaces #1695
Fixes #1655
=> Add annotations to provide custom configs

virtcontainers/fc.go
For security reasons, let's make sure 'others' don't have access to the
firecracker hybrid vsock
fixes #2101
=> virtcontainers: change firecracker socket permissions

cli/kata-check_amd64.go, virtcontainers/acrn.go, virtcontainers/acrn_test.go, virtcontainers/hypervisor.go, virtcontainers/store/filesystem_backend.go, virtcontainers/store/manager.go, virtcontainers/store/vc.go
This patch adds support for getting the kata UUID from
acrn hypervisor and using these UUID to create a VM.
Fixes: #1785
Signed-off-by: Vijay Dhanraj <vijay.dhanraj@intel.com>
=> Hypervisor: UUID fix for acrn hypevisor

Gopkg.lock, Gopkg.toml, vendor/github.com/kata-containers/agent/protocols/client/client.go, virtcontainers/fc.go, virtcontainers/hypervisor.go, virtcontainers/proxy.go
In firecracker, there is no socket connected to /dev/console, so let's
use a vsock port to get agent's logs
fixes #2103
=> virtcontainers: set agent's logs vsock port

virtcontainers/kata_agent.go, virtcontainers/qemu.go, virtcontainers/qemu_test.go
These patches are needed if Kata decides to update to a virtio-fs v0.3 kernel.  They are not compatible with virtio-fs v0.2, so only apply them if the guest kernel is updated.
Fixes: #1993
=> Virtio-fs v0.3 support

.ci/versions_checker.sh
When VERSION file is not updated, the script should not fail.
Fixes #1581
=> ci: travis: Fix check when VERSION has not changed

containerd-shim-v2/service.go
1. Send the event when the container is paused/resumed successfully
2. Return the error of the pause/resume function rather than `getContainerStatus`.
Fixes #2121
=> v2: Change the event and error behavior of pause/resume

virtcontainers/pkg/annotations/annotations.go
The domain name should be used as prefix for the annotations, for
kata containers the domain name is katacontainers.io, not kata-containers.io
fixes #2123
=> virtcontainers/annotations: use right domain name for kata annotations

virtcontainers/store/filesystem_backend.go, virtcontainers/store/vc.go
The uuid file shouldn't be created at `/var` if running rootless.
Modify `VMUUIDStoragePath` to get a path accessible for non-root users
if running rootless.
fixes #2133
=> virtcontainers/store: make VCStoreUUIDPath rootless

virtcontainers/container.go
Mount points, like `resolv.conf` and `hostname` are left in the
host when the cgroup creation fails.
Use `unmountHostMounts()` in the rollback function that is called
when container's creation fails.
fixes #2108
cc @crobinso
=> virtcontainers: unmount host mounts if container can't be created

cli/kata-overhead.go, cli/main.go, virtcontainers/api.go, virtcontainers/container.go, virtcontainers/implementation.go, virtcontainers/interfaces.go, virtcontainers/pkg/vcmock/mock.go, virtcontainers/pkg/vcmock/types.go, virtcontainers/sandbox.go, virtcontainers/sandbox_test.go
With the introduction of sandbox_cgroup_only configuration option for kata-runtime now is possible to calculate the overhead of a kata sandbox by calculating the differnce usage of the containers running in the guest and the resource of the Sandbox cgroup.
Consider add kata-runtime kata-overhead to provide overhead of kata for CPU and memory.
Having this will help users to calculate their own overhead uses-cases.
```
kata-runtime kata-overhead  <sandbox-id|container-id>
cpu_overhead=120
memory_overhead=1000
```
=> cli: add kata-overhead subcommand

virtcontainers/cgroups.go, virtcontainers/cgroups_test.go, virtcontainers/sandbox.go
When SandboxCgroupsOnly is set, we are expected to just inherit our parent's
cgroup settings and to move all Kata threads within that sandbox cgroup. The
initial implementation still adjusted the size of this cgroup. This commit
fixes this.
This commit makes a couple of functional changes, small refactors, and
adds clarifying comments for some functions.
Fixes: # < >
=> sandbox/cgroups: don't constrain if using SandboxCgroupsOnly

virtcontainers/agent.go, virtcontainers/api.go, virtcontainers/kata_agent.go, virtcontainers/noop_agent.go
When do the reloading sandbox in shimv2, it's needed to
rewatch the hypervisor's console when debug enabled.
Fixes:#2091
=> virtcontainers: fix the issue of missing watchConsole

versions.yaml
Update k8s supported version from 1.15.3 to 1.16.2
and cri-o from 1.15.0 to 1.16.0
Fixes: #2166.
=> versions: Update kubernetes and cri-o to 1.16

pkg/rootless/rootless.go, pkg/rootless/rootless_test.go
`rangeUID` should be parsed as ids[2] rather than ids[1]
Fixes: #2173
=> rootless: Fix rangeUID parsing

versions.yaml
These include features like privileged containers without host devices
and support for per runtime annotations.
=> version: Update containerd version to 1.3.0

virtcontainers/qemu.go
Solve possible race condition in qmpSetup()
Fixes: #2139
Signed-off-by: Yves Chan <shanks.cyp@gmail.com>
=> vc/qemu: add mutex to qmp monitor channel in qmpSetup()

pkg/katautils/create.go, pkg/katautils/create_test.go
FIPS are a set of security standards for encryption algororithms
in user and kernel space among others.
Have Kata support this by starting the VM for a container
in FIPS mode on detecting that the host is running in FIPS mode.
Depends-on: github.com/kata-containers/packaging#788
Fixes #2170
=> FIPS: Add support for starting VM in FIPS mode.

virtcontainers/container.go
We do not want to create cgroups in case of rootless.
Fix the logic to implement this.
Fixes #2177
=> rootless: Fix cgroup creation logic for rootless

virtcontainers/container.go
We do not want to create cgroups in case of rootless.
Fix the logic to implement this.
Fixes #2177
(cherry picked from commit f6ffb791e713c0c7d7617caeb6e72cf676a861c1)
=> rootless: Fix cgroup creation logic for rootless(Backport to 1.9)

pkg/rootless/rootless.go, pkg/rootless/rootless_test.go
`rangeUID` should be parsed as ids[2] rather than ids[1]
Fixes: #2173
(cherry picked from commit 3f1a39c442b7786b028b05c81c381acee4edb1a9)
=> rootless: Fix rangeUID parsing (Backport to 1.9)

cli/config/configuration-qemu-virtiofs.toml.in, cli/config/configuration-qemu.toml.in
I think we should consider disable vhost-net for QEMU configuration in 1.10, though I'd like to get feedback from users/community here.
In the meantime, let's clarify what this configuration does.
Fixes: ###
=> qemu-configs: update disable_vhost_net description

cli/config/configuration-fc.toml.in, pkg/katautils/config.go
vhost-net backend is not supported by the Firecracker VMM. It doesn't
make sense to have this in the configuration, and we should explicitly
disable it.
Fixes: #2192
=> fc: config: vhost-net not supported

Gopkg.lock, Gopkg.toml, virtcontainers/acrn.go, virtcontainers/acrn_test.go, virtcontainers/fc.go, virtcontainers/hypervisor.go, virtcontainers/mock_hypervisor.go, virtcontainers/mock_hypervisor_test.go, virtcontainers/qemu.go, virtcontainers/qemu_test.go, virtcontainers/sandbox.go, virtcontainers/vm.go
When hypervisor's debug option set, log out the firecracker's
console output which contains the kernel boot logs; thus it
would be easy for system panic debugging.
When agent debug was enabled by passing "agent.log=debug" to
kernel parameter, it will also log out the agent logs from
the console output.
Fixes: #2201
=> FC: log out the firecracker's console when debug enabled

virtcontainers/clh.go
This PR addresses this comment:
https://github.com/kata-containers/runtime/pull/2164/files#r346776205
/cc @jodh-intel
=> vc: Remove extra call to Kill

virtcontainers/clh.go
PR #2202 changed createSandbox() interface but didn't get a chance
to match with cloud hypervisor change.
Fixes: #2213
This just fixes build. Actual support for debug log on cloud hypervisor should be added later.
=> clh: fix build

virtcontainers/acrn.go, virtcontainers/fc.go
Fixes #2207
Addresses https://github.com/kata-containers/runtime/pull/2204#issuecomment-555409722
=> vc: Remove unnecessary call to kill

cli/main.go, virtcontainers/api.go, virtcontainers/container.go, virtcontainers/experimental/experimental.go, virtcontainers/persist.go, virtcontainers/persist/api/config.go, virtcontainers/persist/fs/fs.go, virtcontainers/sandbox.go
Store the configuration file in persist.go.
This is the last file we should support for "newstore" feature, after this, we can safely remove old persistence storage drivers.
=> Support "Configuration" in "newstore" feature

virtcontainers/sandbox.go
=> vc: Sandbox#Annotations should use annotationsLock read lock

cli/config/configuration-fc.toml.in
Comment out jailer path so that it is disabled by default.
Fixes #2228
=> config: Disable jailer by default for firecracker

virtcontainers/persist/fs/fs.go
=> vc: Persist file handle may leak in FS#FromDisk

virtcontainers/sandbox.go
=> vc: Restore sandbox state when there is error starting containers

virtcontainers/persist/fs/fs.go
=> vc: Persist file handle may leak in FS#ToDisk

containerd-shim-v2/service.go
Currently, There are too many logs from kata shim in containerd's log. We should handle it.
Fix #2209
=> Respect containerd's debug config

.gitignore
update .gitignore to include configuration-clh.toml to the list of
untracked files
fixes #2249
=> gitignore: include cloud hypervisor configuration toml

virtcontainers/fc.go
**Which feature do you think can be improved?**
Hi~ I've recently been working on enabling firecracker on kata containers.
If Firecracker exits abnormally after `InstantStart` request, the error output you could get is only timeout related, nothing useful.
```
docker: Error response from daemon: OCI runtime create failed: Failed to check if grpc server is working: context deadline exceeded: unknown.
```
Firecracker has its own logging scheme, involving two fifo files. For better debugging, we should
extract those error info and re-play them in kata-runtime log.
=> FC: extract error info from firecracker built-in log and metrics scheme

virtcontainers/api.go, virtcontainers/sandbox.go
Do not iterate over a map to find a container, use map built-in
method instead.
fixes #2254
=> virtcontainers: improve algorithm to find containers

virtcontainers/container.go
Currently kata-runtime saves the Container OCI Spec even when it's not needed
and a comment in `ContainerConfig struct` specifically indicates that
it won't be saved to disk.
Use '-' as json tag instead of '_' to indicates that `Spec` field shouldn't
be saved to disk.
fixes #2256
=> virtcontainers: honour ContainerConfig struct comment and don't save OCI spec

pkg/katautils/tracing.go
Force Jaeger to log when it reports traces to ensure the tracing test [1] works as expected.
Fixes: #2264.
[1] - https://github.com/kata-containers/tests/blob/master/tracing/tracing-test.sh
=> tracing: Unbreak tracing test

virtcontainers/api.go, virtcontainers/api_test.go, virtcontainers/cgroups_test.go, virtcontainers/container.go, virtcontainers/kata_agent.go, virtcontainers/kata_agent_test.go, virtcontainers/pkg/oci/utils.go, virtcontainers/pkg/oci/utils_test.go, virtcontainers/sandbox.go, virtcontainers/sandbox_test.go
GetOCISpec returns a patched version of the original OCI spec, it was modified
to support:
* capabilities
* Ephemeral storage
* k8s empty dir
In order to avoid consusions and make api clear, rename GetOCISpec
to GetPatchedOCISpec.
fixes #2252
=> virtcontainers: rename GetOCISpec to GetPatchedOCISpec

virtcontainers/sandbox.go
=> vc: Sandbox#getAndSetSandboxBlockIndex shouldn't alter BlockIndex in case of error

virtcontainers/sandbox.go
Don't hot add again non-running container resources to avoid having extra
and useless resources
fixes #2186
NOTE: this PR won't break backward compatibility
=> k8s: fix wrong number cpus after killing a container

virtcontainers/api.go, virtcontainers/api_test.go, virtcontainers/implementation.go, virtcontainers/interfaces.go, virtcontainers/pkg/vcmock/mock.go, virtcontainers/pkg/vcmock/mock_test.go, virtcontainers/pkg/vcmock/types.go, virtcontainers/sandbox.go
=> vc: Drop Sandbox#Pause and Sandbox#Resume

virtcontainers/container.go, virtcontainers/kata_agent.go
We can use map from Source to Mount as ignoredMounts representation.
Inner loop in kataAgent#removeIgnoredOCIMount is removed.
Fixes #2299
Signed-off-by: Ted Yu yuzhihong@gmail.com
=> vc: Use map to represent ignoredMounts

versions.yaml
=> kernel: update to 4.19.83

virtcontainers/api.go, virtcontainers/pkg/compatoci/utils.go
Add a standard `SetLogger()` call to allow the `compatoci` package to be provided a base logger which it can then customise.
Fixes: #2305.
=> compatoci: Add a SetLogger call

virtcontainers/network.go
Since the /dev/vhost-net device is owned by root, we cannot used
vhost-net networking in rootless mode. Instead of having to
do this manually in the toml, disable vhost-net when the runtime
detects it is running rootless.
Fixes #2321
=> rootless: Disable vhost-net for rootless

versions.yaml
To include the latest fix for CVE-2019-18960.
Fixes: #2334
=> versions: bump firecracker version

versions.yaml
To include latest fix for CVE-2019-18960.
Fixes: #2336
Signed-off-by: Peng Tao <bergwolf@hyper.sh>
=> versions: bump fc version to v0.18.1

virtcontainers/network.go
Since the /dev/vhost-net device is owned by root, we cannot used
vhost-net networking in rootless mode. Instead of having to
do this manually in the toml, disable vhost-net when the runtime
detects it is running rootless.
Fixes #2321
=> rootless: Disable vhost-net for rootless(backport)

cli/main.go, pkg/katautils/config-settings.go, pkg/katautils/config.go, pkg/katautils/config_test.go
If no virtioFsCache type set in configuration file, virtiofsd will
not start well as a daemon, which make container start fail if virtio-fs
as its shared file system.
Fixed: #2279
@jodh-intel @grahamwhaley
=> virtiofs: add default value for virtioFsCache type.

virtcontainers/fc.go, virtcontainers/types/fcConfig.go
New command-line parameter for firecracker v0.19.0, named `--config-file`, which represents the path to a file that contains a JSON which can be used for configuring and starting a microVM without sending any API requests.
If we are using this new flag, we could bypass the whole API ready state.
I have wrote a draft on how it may work, And I use the variable `enabledconfigOption` to distinguish two processes.
So wdyt, do we need to hold two different boot-up processes for users to choose, or just turn to use the new `--config-file` option?
=> FC: introduce `--config-file` to bypass API ready state

cli/factory.go, virtcontainers/agent.go, virtcontainers/kata_agent.go, virtcontainers/noop_agent.go, virtcontainers/qemu.go, virtcontainers/vm.go
For now, we will encounter nil pointer runtime panic when launching kata containers from cache factory.
```
kata-runtime[133160]: time="2019-11-25T15:57:05.799620876+08:00" level=error msg="fatal
error" arch=arm64 name=kata-runtime panic="runtime error: invalid memory address or nil pointer
dereference" pid=133160 source=runtime
```
After fixing this, we will still have missing bridge address error.
```
$ docker run --runtime kata-runtime busybox
docker: Error response from daemon: OCI runtime create failed: failed to get available address from bridges: unknown.
```
That's because that although we've already passed bridges info to clients from cache factory server, we've still missed the setting part when creating vm.
=> cache-factory: a few bug fix

containerd-shim-v2/delete.go, virtcontainers/container.go
When we kill vmm with SIGKILL after creating a new sandbox, there are two issues:
1. shimv2 process does not exit
2. data in container volume is removed unexpectedly
The PR fixes both of them.
=> shimv2: clean up properly if vmm quits unexpectedly

containerd-shim-v2/create.go, containerd-shim-v2/create_test.go, virtcontainers/pkg/annotations/annotations.go, virtcontainers/pkg/oci/utils.go
So that user can have per pod runtime config which is easier
to manage in some cases.
Fixes: #2332
=> shimv2: support runtime config path via annotation

Gopkg.lock, Gopkg.toml, vendor/github.com/kata-containers/agent/protocols/client/client.go
Update github.com/kata-containers/agent to
introduce fix of hybrid vsock.
Fixes: #2284
Signed-off-by: Hui Zhu <teawater@antfin.com>
=> vendor: Update github.com/kata-containers/agent

pkg/katautils/network.go, pkg/rootless/rootless.go
When kata-runtime was invoked as rootless by podman with
net=none, an empty net namespace path is provided.
kata-runtime was then trying to create a new network namespace
and bind-mounting it under /var/run/netns, resulting in a permission error.
Instead, with this commit, the runtime checks if it is
running rootless and instead creates network namespace bind mount
under rootless directory instead.
Fixes #2319
=> rootless: fix rootless for case net=none

versions.yaml
This updates the cloud hypervisor url.
Fixes #2365
=> versions: Update cloud hypervisor url

virtcontainers/clh.go, virtcontainers/clh_test.go, virtcontainers/hypervisor.go, virtcontainers/utils/utils.go, virtcontainers/virtcontainers_test.go, virtcontainers/virtiofsd.go, virtcontainers/virtiofsd_test.go
This add unit test in clh.go driver to achieve that two new interfaces are added to allow mock testing.
clhClient: An interface that define the methods described by the HTTP Cloud hypervisor client.
virtiofsd interface: An interface around virtiofsd.
Additionally `utils.StartCmd(cmd)` was added this is aim to use instead of `cmd.Start()`  this allow to modify it at unit testing and not run any command but just simulate is started.
Both virtiofsd and HTTP client are dependencies of cloud hypervisor that now are implemented as interfaces to have a loose depedency in them.
As a result this allow to write more extensive unit test in `clh.go`
=> clh: Increase unit test using mock testing

cli/main_test.go, virtcontainers/factory/direct/direct_test.go, virtcontainers/persist/fs/fs_test.go, virtcontainers/pkg/nsenter/nsenter_test.go, virtcontainers/store/filesystem_backend_test.go, virtcontainers/store/manager_test.go, virtcontainers/virtcontainers_test.go
The PR fixes several `make test` failures:
- `testing: can't write /tmp/go-build146132196/b001/testlog.txt: close /tmp/go-build146132196/b001/testlog.txt: file already closed`
- `mkdir /var/lib/vc/uuid: permission denied`
- `clh_test.go:191: cloudHypervisor.cleanupVM() expected error != open /run/vc/vm: permission denied`
- several other permission errors in different packages
=> ut: fix make test failures

versions.yaml
Fixes CVE-2019-12068
shortlog:
99c5874a9b Update version for 4.1.1 release
e092a17d38 mirror: Keep mirror_top_bs drained after dropping permissions
088f1e8fd9 block/create: Do not abort if a block driver is not available
145b562990 vhost: Fix memory region section comparison
42b6571357 memory: Provide an equality function for MemoryRegionSections
c0aca9352d memory: Align MemoryRegionSections fields
54c130493c tests: make filemonitor test more robust to event ordering
3d018ff3bd block: posix: Always allocate the first block
f0d3fa265d file-posix: Handle undetectable alignment
7db05c8a73 block/file-posix: Let post-EOF fallocate serialize
d9b88f7e0d block: Add bdrv_co_get_self_request()
590cff8230 block: Make wait/mark serialising requests public
2e2ad02f2c block/io: refactor padding …
=> versions: update qemu to 4.1.1

virtcontainers/acrn_arch_base_test.go, virtcontainers/kata_agent_test.go, virtcontainers/qemu_arch_base_test.go, virtcontainers/store/manager_test.go, virtcontainers/vm_test.go
I've found a few unit tests which were generating stale files under `/tmp`
**- Using `defer` in TestMain.**
os.Exit will skip all deferred instructions.
So we should reconstruct TestMain to leave all setup-related code in setup(), and all cleanup-related code in shutdown().
**- Missing deleting what `ioutil.TempDir()` creates**
Normally, ` ioutil.TempDir` will create a new temporary dir under `/tmp`.
**- Missing deleting what `ioutil.TempFile()` creates**
`ioutil.TempFile` creates a new temporary file in the directory `/tmp`.
It is the caller's responsibility to remove the file when no longer needed.
=> unit-test: cleaning up stale files under /tmp

virtcontainers/sandbox.go
There was a small typo, "sandox"
Signed-off-by: Christophe de Dinechin <dinechin@redhat.com>
=> Fix typo in 'sandbox'

cli/config/configuration-acrn.toml.in, cli/config/configuration-clh.toml.in, cli/config/configuration-fc.toml.in, cli/config/configuration-qemu-virtiofs.toml.in, cli/config/configuration-qemu.toml.in, virtcontainers/pkg/oci/utils.go, virtcontainers/sandbox.go
The sandbox cgroup will be constrained if there is no container
type annotation, otherwise kata will rely on container engine's cgroup
configuration
fixes #2408
=> virtcontainers: constrain docker container when sandbox_cgroup_only=true

Gopkg.lock, Gopkg.toml, vendor/github.com/kata-containers/agent/protocols/client/client.go
Update agent client to improve CI stability.
Changes:
660e61f Revert: client.go: HybridVSockDialer: Change Read EOT to recv peek
6cfb75d Revert: client.go: HybridVSockDialer: Check return size n of unix.Recvfrom
54eb918 Revert: client.go: HybridVSockDialer: Close dup fd after receive packet
2f49115 agent: Fix mem-hotplug on x86 when ARCH_MEMORY_PROBE is set
Fixes: #2397
=> vendor: update agent client

versions.yaml
in hopes the old failures were fixed, and to investigate them if not
if passes, this will fix: https://github.com/kata-containers/tests/issues/2271
Signed-off-by: Peter Hunt <pehunt@redhat.com>
=> versions: bump conmon version to v2.0.5

Gopkg.lock, pkg/rootless/rootless.go
Recently, ARM CI frequently failed on the following golint error:
http://jenkins.katacontainers.io/job/kata-containers-runtime-ARM-18.04-PR/1451/console
```
11:24:18 pkg/rootless/rootless.go:57:2: comment on exported var `IsRootless` should be of the form `IsRootless ...` (golint)
11:24:18 	//The function is declared this way for mocking in unit tests
11:24:18 	^
11:24:23 Build step 'Execute shell' marked build as failure
```
**Updates:**
New error output:
```
12:13:45 # Gopkg.lock is out of sync:
12:13:45 github.com/opencontainers/runc/libcontainer/system: imported or required, but missing from Gopkg.lock's input-imports
```
It looks like that in PR #2418, we imported `github.com/opencontainers/runc/libcontainer/system`, but forgot to `dep ensure` ?
=> AArch64: fix golint error on ARM CI.

virtcontainers/qemu_s390x.go
On s390x we need to set the devno that's why we need a custom
appendBlkDevice function.
Fixes: #2384
=> s390x: fix refactoring

virtcontainers/clh.go
The guest Linux kernel might try to access the serial port, and in case
the serial is "off", this might cause some slowness because the port is
not emulated at all. Problem is, when the port is not emulated, the
default value when reading the I/O port will be 0, which has a special
meaning in case of the serial port. It means there is some data ready
to be read, which the kernel might try to read for some time, causing
global system slowness.
That's why it's safer to use "null" by default as this means the serial
port will be emulated but anything written to it will be redirected to
/dev/null.
Fixes #2437 
=> virtcontainers: clh: Set the serial to NULL instead of OFF

Gopkg.lock, Gopkg.toml, vendor/github.com/kata-containers/agent/protocols/client/client.go, versions.yaml
The new release for Firecracker is `v0.20.0`.
There are a few related updates:
- Change logger options type from Value to Vec to prevent potential unwrap on None panics. (PR #2073)
- VSock Connection Handshake. (kata-containers/agent#706)
Fixes: #2378
=> FC: Update Firecracker to v0.20.0

.ci/install-yq.sh
To match the version used in the tests repo.
Related: https://github.com/kata-containers/tests/issues/2290
Fixes: #2447.
=> CI: update yq to 3.1.0

.ci/go-test.sh, .ci/setup.sh
Skip the setup and installation of virtcontainers as it is using docker,
when we try to setup podman CI.
Depends-on: github.com/kata-containers/tests#2299
Fixes #2451
=> ci: Do not setup virtcontainers while using podman

virtcontainers/kata_agent.go, virtcontainers/kata_agent_test.go
Till we implement support for selinux, disable selinux
by not passing selinux labels in the container spec.
Fixes #2442
=> selinux: Disable selinux

versions.yaml
=> kernel: Update kernel to latest stable 5.4.15

Makefile
This provides a flag "STRIP=yes" to strip the golang binary
After this patch, the binary size is reduced a lot:
19356680 containerd-shim-kata-v2*
25980728 containerd-shim-kata-v2.nostip*
4021784 kata-netmon*
5093992 kata-netmon.nostrip*
26339392 kata-runtime*
33097344 kata-runtime.nostrip*
Fixes: #2455
Signed-off-by: Jia He <justin.he@arm.com>
=> build: Add support to strip the binary

versions.yaml
Hi guys
I try to choose which distribution is the most suitable one for AArch64. And maybe the size of rootfs is the key point we should consider most and first. 
Comparing on the three common distribution: 
- Fedora
```
$ ~/go/src/github.com/kata-containers/osbuilder# du -sh fedora_rootfs/
283M    fedora_rootfs/
```
Also The late Fedora(`fedora 30`) has the following issue on AArch64: https://github.com/kata-containers/ci/issues/205, So we have to stick to the old version `fedora 29`.
- Centos
```
$ ~/go/src/github.com/kata-containers/osbuilder# du -sh centos_rootfs/                
394M    centos_rootfs/
```
- Ubuntu
```
$ ~/go/src/github.com/kata-containers/osbuilder# du -sh ubuntu_rootfs/                
118M    ubuntu_rootfs/
```
In conclusion, ubuntu is the best option on AArch64. …
=> AArch64: change image rootfs from fedora to ubuntu

cli/kata-check.go, cli/kata-check_test.go, cli/kata-env.go, cli/kata-env_test.go, cli/utils.go
**Which feature do you think can be improved?**
We may need multiple kata components to launch one kata container. The longest legacy one could have `kata-shim`, `kata-proxy`, `kata-runtime`, and `kata-agent.`
For users, especially for developers, we often encounter confused runtime error due to each kata component at different version.
E.g. Laterly, I've encountered following error in launching kata container with firecracker, and it's because of stale version of `kata-shim`, which is lower than `v1.9.0`.
```
$ docker run --runtime kata-runtime busybox
docker: Error response from daemon: cannot start a stopped process: unknown.
ERRO[0002] error waiting for container: context canceled
```
**How can it be improved?**
So, here, I want to introduce version consistency check in `kata-runtime …
=> kata-check: Add version consistency check

Makefile
Some flags defined by the host may not be compatible with golang,
not use LDFLAGS but use our own variable.
Fixes: #2478
=> makefile: do not use LDFLAGS for extra kata flags.

Makefile
KATA_LDFLAGS should be applied to all golang calls.
Fixes: #2478
=> makefile: Fix missing LDFLAGS references

virtcontainers/clh.go
cloud-hypervisor uses `hybrid vsocks`, it is not needed to find a
context ID.
Fixes: #2481
=> clh: Do not find vsock context ID

virtcontainers/container.go, virtcontainers/device/drivers/utils.go, virtcontainers/device/drivers/vfio.go, virtcontainers/device/manager/manager.go, virtcontainers/device/manager/utils.go, virtcontainers/sandbox_test.go
This is a solution to issue #2460 .
Since the pci rescan will conflict with shpchp / pciehp, we can attach the Nvidia GPU after creating the container, and then the pci rescan will not include the Nvidia GPU. 
shpchp / pciehp will handle hot plugging of Nvidia GPU correctly.
There may be better solutions, but this is a working solution.
=> Fix rescan PCI conflicts with shpchp / pciehp

cli/kata-env.go, cli/kata-env_test.go
virtiofsd should be added in kata-env as virtiofs enabled kata then
it will be easy to get the info of virtiofsd from kata-env.
Fixes: #2491
@Jimmy-Xu  @jodh-intel @grahamwhaley @bergwolf  @Pennyzct
=> cli: add virtioFsDaemon to kata-env

versions.yaml
Hi~ guys
I've found tons of leaking network namespace mount point on ARM CI, which comes from cri-o.
```
root@arm-testing-2:~# mount | grep "/run/netns/cni-" | wc -l
3084
```
`cri-o v1.16.x` forgets to un-mount them when they're in no use. But it got fixed in `cri-o v1.17.0`,
see [related code here](https://github.com/cri-o/cri-o/blob/release-1.17/internal/lib/sandbox/namespaces_linux.go#L183) for confirmation. ;)
So we need to do the version update for cri-o. And Since CRI-O and Kubernetes follow the same release cycle and deprecation policy, I will also update k8s as well. ;).
=> cri-o: fix netns mount point leaking from cri-o

virtcontainers/acrn_test.go, virtcontainers/api_test.go, virtcontainers/device/api/interface.go, virtcontainers/device/api/mockDeviceReceiver.go, virtcontainers/device/drivers/block.go, virtcontainers/persist.go, virtcontainers/persist/api/hypervisor.go, virtcontainers/persist_test.go, virtcontainers/sandbox.go, virtcontainers/sandbox_test.go, virtcontainers/types/sandbox.go
This allows to reuse detached block index and ensures that the index will not reach the limit of device(such as `maxSCSIDevices`) after restarting containers many times in one pod.
I'm not sure whether it is ok to reuse the index for all the block drivers and would this change break the persist feature. 
Fixes: #2007
=> vc: Use BlockIndexMap instead of BlockIndex

virtcontainers/clh.go, virtcontainers/persist/api/hypervisor.go
The 'apiSocket' member in the CloudHypervisorState struct needs to be kept
across different executions of kata-runtime with persist HypervisorState, so
that kata-runtime can talk with the same running cloud-hypervisor through
HTTP/REST API calls.
Fixes: kata-containers#2506
=> clh: add 'APIsocket' to persist HypervisorState

virtcontainers/clh.go, virtcontainers/clh_test.go
With the HTTP API 'vm.resize()', the CPU hotplug with CLH is much simpler
comparing with QEMU. This is because we don't need to distinguish adding from
removing CPUs.
Fixes: #2495
Note: hotplug with CLH requires a patch to the guest kernel (as noted from [CLH's docs](https://github.com/cloud-hypervisor/cloud-hypervisor/blob/master/docs/hotplug.md#kernel-support)), which is missing in kata's guest kernel for now. We will need to introduce [this patch](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/patch/drivers/acpi/Makefile?id=ac36d37e943635fc072e9d4f47e40a48fbcdb3f0) to our kata packaging first, before we can merge this PR.
=> clh: enable CPU hotplug

virtcontainers/container.go, virtcontainers/mount.go, virtcontainers/mount_test.go
Remove the rootfs bind dest and finally remove the created share directory when stopping the container.
Fixes #2516
=> vc: Remove container share dir when stopping

cli/main.go, pkg/katautils/logger.go
Our default logging level was Info, which is rather noisy. Reduce it to Warn, so we still see any critical
items, but don't get swamped with Info messages.
=> logging: reduce default log level to Warn from Info

virtcontainers/clh.go
set rootfstype=ext4 to make kernel not do print errros like:
```
Mount option "data=ordered" incompatible with ext2
```
Fixes: #2524
=> clh: set rootfstype

virtcontainers/kata_agent.go, virtcontainers/kata_agent_test.go, virtcontainers/pkg/annotations/annotations.go, virtcontainers/pkg/oci/utils.go, virtcontainers/pkg/oci/utils_test.go, virtcontainers/vm_test.go
This adds the `agent.container_pipe_size` annotation which allows
configuration of the size of the pipes for stdout/stderr for containers
inside the guest.
fixes #2467
Signed-off-by: Alex Price <aprice@atlassian.com>
=> vc: add agent.container_pipe_size annotation

README.md
The shimv2 runtime logs slightly differently - let's clarify
that in the existing OCI/CRI-O only runtime section.
Fixes: #2520
=> README: logging: add shimv2 information

virtcontainers/clh.go, virtcontainers/clh_test.go
Our CLH driver in kata defines its own constant variable 'maxClhVcpus'
which can conflict with the maximum number of vCPUs specified from the
kata configuration file 'clh.config.DefaultMaxVCPUs'. As the value from
kata configuration file is preferred anyway and the code on 'maxClhVcpus'
is not being used. We'd better remove it for better readability and
avoiding further confusions.
Fixes: #2528
=> clh: Remove dead-code on maxClhVcpus

virtcontainers/container.go, virtcontainers/container_test.go, virtcontainers/fc.go, virtcontainers/mount.go, virtcontainers/mount_test.go, virtcontainers/syscall_test.go
Hi~ guys
When running kata-containers with jailer in Ubuntu 18.04, I've encountered the following error, after
jailer chrooting `$jailerChrootBaseDir/firecracker/<sandbox_id>/root` and trying to execute `firecracker`:
```
$ /run/vc/firecracker/..../root/firecracker
-bash: /run/vc/firecracker/.../root/firecracker: Permission denied
```
That's because that in some distributions(`Ubuntu 18.04`/ `Ubuntu 16.04`), now, `/run` is mounted with `noexec` flag.
```
$ mount | grep "/run"
tmpfs on /run type tmpfs (rw,nosuid,noexec,relatime,size=6582528k,mode=755)
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"
```
BTW, we could use `mount -o remount,exec /run` to temporarily fix the error. 
But IMO, above method is too …
=> Jailer: checking whether chrootBasedir is mounted `noexec` 

arch/arm64-options.mk, versions.yaml, virtcontainers/fc.go, virtcontainers/fc_test.go, virtcontainers/pkg/firecracker/client/models/instance_action_info.go, virtcontainers/pkg/firecracker/client/models/logger.go, virtcontainers/pkg/firecracker/firecracker.yaml
Hi~~guys
Firecracker has released the new version, `v0.21.0`. 
In this new release, Firecracker deprecated KVM dirty page tracking, and removed `options` field from the logger configuration. This feature previously was only supported on `amd64`.
So, finally, `AArch64` could support all general feature defined in [firecracker.yaml](https://github.com/firecracker-microvm/firecracker/blob/master/src/api_server/swagger/firecracker.yaml).
**So I want to officially enable firecracker in kata-containers on AArch64**.🎊
In v0.21.0, Firecracker imported one new small `args_parser` scheme to do the command line arguments parsing. 
But it forgets to support `--version` flag. 
```
$ ./firecracker-v0.21.0-x86_64 --version
2020-02-26T03:15:13.135125190 …
```
=> AArch64: officially enable firecracker v0.21.0 on AArch64

containerd-shim-v2/container.go, containerd-shim-v2/container_test.go, containerd-shim-v2/create.go, containerd-shim-v2/delete.go, containerd-shim-v2/delete_test.go, containerd-shim-v2/exec_test.go, containerd-shim-v2/pause_test.go, containerd-shim-v2/service.go, containerd-shim-v2/start_test.go, containerd-shim-v2/wait.go
It is in fact a container specific info not sandbox level info.
We are assuming that all containers use the same snapshotter
but we should be able to handle different snapshotters even in
the same sandbox.
=> shimv2: move container rootfs mounted flag to container level

virtcontainers/kata_agent.go, virtcontainers/kata_agent_test.go, virtcontainers/sandbox_test.go
vfio devices hotplugged in the VM are expected to be handled by the kernel
driver in the guest, hence the char vfio devices shouldn't appear in the
container under /dev/vfio/.
fixes #2539
=> virtcontainers: Don't create vfio devices in the guest

versions.yaml
We currently use containerd v1.3.0, but this version has an
issue when running the containerd/cri tests with go 1.13.
This commit: 3a4acfbc99aa976849f51a8edd4af20ead51d8d7 from
branch release/1.3 contains the fix to be able to run the
tests with go 1.13.
Fixes: #2562.
=> versions: Update containerd commit

Gopkg.lock, Gopkg.toml, vendor/github.com/intel/govmm/qemu/qmp.go, virtcontainers/container.go, virtcontainers/device/config/config.go, virtcontainers/device/config/config_test.go, virtcontainers/device/config/pmem.go, virtcontainers/device/config/pmem_test.go, virtcontainers/device/drivers/block.go, virtcontainers/device/manager/manager.go, virtcontainers/kata_agent.go, virtcontainers/mount.go, virtcontainers/mount_test.go, virtcontainers/persist/api/device.go, virtcontainers/qemu.go, virtcontainers/utils/utils_linux.go, virtcontainers/utils/utils_linux_test.go
A persistent memory volume MUST meet the following conditions:
* A loop device must be mounted in the directory passed as volume
* The loop device must have a backing file
* The backing file must have the PFN signature at offset 4k [1][2]
The backing file is used as backend file for a NVDIMM device in the guest
fixes #2262
[1] - https://github.com/kata-containers/osbuilder/blob/master/image-builder
/nsdax.gpl.c
[2] - https://github.com/torvalds/linux/blob/master/drivers/nvdimm/pfn.h
cc @pohly
=> Support persistent memory volumes

virtcontainers/device/manager/utils.go, virtcontainers/device/manager/utils_test.go
Make sure the number of columns in the PCI resource file is greater
or equal to 2, since the first two columns are used to calculate
the PCI bar space.
Add unit test for `isLargeBarSpace()`.
fixes #2542
=> virtcontainers: check PCI resource format before using it

virtcontainers/clh.go
To have a consistent behavior of CPU hotplug with qemu in clh, we should
only report warning instead of errors when the requested vCPUs exceeds
the maximum number of vCPUs allowed.
Fixes: #2551
=> clh: Report warning when requested vCPUs exceeds maxVCPU allowed

Makefile
- Add support to change default hypervisor via env variable.
- Show in the summary the default hypervisor to be used.
```
export DEFAULT_HYPEVISOR=cloud-hypervisor
make
sudo -E make install
```
Fixes: #2565
=> Makefile: Allow change default hypervisor via env var

versions.yaml
We need this update for building Kubernetes and CRI-O with the latest go 1.13
version.
/cc @chavafg 
Releates to https://github.com/cri-o/cri-o/pull/3392
Fixes https://github.com/kata-containers/runtime/issues/2537
=> Update go to v1.13.8

virtcontainers/acrn_arch_base.go, virtcontainers/clh.go, virtcontainers/fc.go, virtcontainers/qemu_amd64.go, virtcontainers/qemu_arch_base.go, virtcontainers/types/capabilities.go, virtcontainers/types/capabilities_test.go
- Change capabilities to change `SetFsSharingUnsupported()`  to `SetFsSharingSupport()` it make more natural with the rest of methods that enable features. 
- Implement `capabilities()` for clh by setting  `FsSharingSupport` to true, other capabilities are not supported today.
=> clh:  Implment capabilities 

Gopkg.lock, Gopkg.toml, Makefile, hack/selinux_tag.sh, vendor/github.com/opencontainers/selinux/LICENSE, vendor/github.com/opencontainers/selinux/go-selinux/label/label.go, vendor/github.com/opencontainers/selinux/go-selinux/label/label_selinux.go, vendor/github.com/opencontainers/selinux/go-selinux/label/label_stub.go, vendor/github.com/opencontainers/selinux/go-selinux/selinux_linux.go, vendor/github.com/opencontainers/selinux/go-selinux/selinux_stub.go, vendor/github.com/opencontainers/selinux/go-selinux/xattrs.go, vendor/github.com/opencontainers/selinux/pkg/pwalk/pwalk.go, virtcontainers/clh.go, virtcontainers/fc.go, virtcontainers/hypervisor.go, virtcontainers/kata_agent.go, virtcontainers/qemu.go, virtcontainers/sandbox.go
We want to launch the KVM launcher tool (qemu?) with an SELinux label, similar
to what we do with libvirt.
Currently when I use kata with Podman, it complains if we specify a label that
kata does not support SELinux labels. What I would like to do is have kata just
use this label to apply to the KVM launcher. Then I will work to generate a new
policy type (container_kvm_t) that will allow the KVM Launcher tool to do its
thing, but prevent breakout.
Fixes: https://github.com/kata-containers/runtime/issues/2501
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>
=> Add SELinux support for running VM Confinement

virtcontainers/qemu.go
Instead, report an error and exit gracefully, as shown below:
```
dahmer fidencio # podman run -ti --runtime=/usr/bin/kata-runtime fedora sh
Error: stat /usr/libexec/virtiofsd: no such file or directory: OCI runtime command not found error
```
Fixes: #2582
=> qemu: Don't crash if virtiofsd path is non existent

virtcontainers/qemu_ppc64le.go
Since fs sharing is not assumed as supported by default, expose
explicitly that the qemu_ppc64le supports it.
Fixes: #2584
=> qemu_ppc64le: EXpose fs support explicitly

.travis.yml, versions.yaml
Update golang to fix `golangci-lint` errors on travis.
Depends-on: github.com/kata-containers/tests#2435
Fixes: #2592.
=> versions: Update go to 1.13.9

virtcontainers/qemu_ppc64le.go
Large decrementer was introduced in Power 9 cpus.
Switch it off "cap-large-decr=off" as not all KVM hosts
support it
Fixes: #2599
=> qemu-ppc64le: Switch off large decrementer capability

containerd-shim-v2/stream.go, containerd-shim-v2/stream_test.go
The container log fifo is opened as `O_WRONLY` now. When the read side of fifo is closed temporarily such as restarting contaienrd, write to `tty.Stdout` will get an EPIPE error and finally cause `io.CopyBuffer` return. Then `ioCopy` closes the tty io and exits. Thus after containerd restarted, the log fifo can't be reopened. The container will be blocked forever after stdout/stderr buffer is full.
Opening the log fifo with `RDWR` instead of `WRONLY` avoids the fifo returning EPIPE when the read side is closed, and keeps the fifo open until the reader reopening it.
Fixes: #2590
=> v2: Open log fifo with `RDWR` instead of `WRONLY`

virtcontainers/virtiofsd.go
Add option in qemu driver , this will allow lock operations.
Fixes: #2594
=> clh: virtiofs: Add no_posix_lock option

.gitignore, Makefile, pkg/katautils/config-settings.go.in
When building kata runtime packagers can simply do something like
`make CONFDIR=/usr/share/kata-containers/defaults` and it'll make
runtime understand that `/usr/share/defaults/kata-containers/` shouldn't
be used as `defaultRuntimeConfiguration` and, instead, runtime will use
whatever as passed to `make` during build time.
This is a quite common approach, mainly for distros, as there's no
perfect agreement on directory layout and whatnot.
Kwowing that, let's also make `containerd-shim-kata-v2`, which reads the
configurations from `pkg/katautils/config-settings.go`, to have a
similar behaviour as `runtime` and respect a "build-time" configured
`defaultRuntimeConfiguration` and `defaultSysConfRuntimeConfiguration`
paths.
Fixes: #2610
=> katautils: Use config paths set during the build

pkg/katautils/config.go, pkg/katautils/create_test.go
As per [1], the default scan mode of scsi is sync. Change it to none
can reduce the guest boot time:
=Before this patch=
[    0.090796]  vda: vda1
[    0.092119] scsi host0: Virtio SCSI HBA
[    0.148851] tun: Universal TUN/TAP device driver, 1.6
[    0.149023] rtc-pl031 9010000.pl031: rtc core: registered pl031 as rtc0
=After this patch=
[    0.077012]  vda: vda1
[    0.078353] scsi host0: Virtio SCSI HBA
[    0.080755] tun: Universal TUN/TAP device driver, 1.6
[    0.081884] rtc-pl031 9010000.pl031: rtc core: registered pl031 as rtc0
It reduces about 54ms on arm64 for virtio-scsi.
This patch changes the default kernel parameter:
1. If user specifies the scan mode, use that
2. If user doesn't specify it, and the block device is virtio-scsi, use
"async" by default
[1] …
=> config: Add scsi_mod.scan=none for virtio-scsi

.travis.yml, containerd-shim-v2/stream.go, containerd-shim-v2/stream_test.go, versions.yaml, virtcontainers/kata_agent.go, virtcontainers/kata_agent_test.go, virtcontainers/qemu.go, virtcontainers/sandbox.go, virtcontainers/sandbox_test.go
Commits backported:
v2: Open log fifo with `RDWR` instead of `WRONLY` … ffa090a
qemu: Don't crash if virtiofsd path is non existent … cbfb3a4
virtcontainers: Don't create vfio devices in the guest … 11838d0
=> stable-1.10 backports

containerd-shim-v2/stream.go, containerd-shim-v2/stream_test.go, virtcontainers/kata_agent.go, virtcontainers/kata_agent_test.go, virtcontainers/qemu.go, virtcontainers/sandbox_test.go
v2: Open log fifo with `RDWR` instead of `WRONLY` … 81d08f7
qemu: Don't crash if virtiofsd path is non existent … 24f660c
virtcontainers: Don't create vfio devices in the guest … eefccac
=> Stable-1.9 backports 

versions.yaml
Most of the description fields have capitalized text,
some of those that don't are then converted on this
change.
Fixed spelling of 'required'.
Signed-off-by: Wainer dos Santos Moschetta <wainersm@redhat.com>
=> versions: Misc changes to descriptions

virtcontainers/clh.go, virtcontainers/clh_test.go
Fixes #2311
If major version matches max supported major, we continue comparing the minor version.
The error along with the original check was actually negated.
Since supportedMajorVersion is 0, the condition was never hit. But the new test exposes the bug.
=> vc: Version support check is ineffective in createSandbox

virtcontainers/qemu_arm64.go
Hi guys
In PR https://github.com/kata-containers/packaging/pull/1006, I've backported Anshuman Khandual's patch series of Enabling memory hot remove on aarch64(https://patchwork.kernel.org/cover/11419305/) to `v5.4.x`.
This patch series has already been merged, and queued for 5.7.
And after backporting this series, we could finally enable nvdimm/dax on arm64.
See kernel dump info:
```
[    0.154853] EXT4-fs (pmem0p1): DAX enabled. Warning: EXPERIMENTAL, use at your own risk
[    0.155487] EXT4-fs (pmem0p1): mounted filesystem with ordered data mode. Opts: dax,data=ordered,errors=remount-ro
[    0.155714] VFS: Mounted root (ext4 filesystem) readonly on device 259:1
```
NVDIMM/DAX is truly working here~~
=> dax: enable dax on arm64

versions.yaml
Removed the `golangci-lint` and `gometalinter` entries from the versions database:
- The `golangci-lint` package is now tracked in the `tests` versions database:
https://github.com/kata-containers/tests/blob/master/versions.yaml
- The `gometalinter` package is no longer used.
See:
- https://github.com/kata-containers/tests/issues/1323
- https://github.com/kata-containers/tests/commit/d676140510f11dd795e3606341f512a75d8f0d75
Fixes: #2636.
=> versions: Remove golangci-lint and gometalinter entries

virtcontainers/api.go
Call the `store` packages `SetLogger()` function to ensure all its log records contain all required structured logging fields.
Fixes: #2644.
=> logging: Fix structured logging in store package

virtcontainers/api.go, virtcontainers/device/api/interface.go, virtcontainers/device/drivers/generic.go, virtcontainers/device/drivers/generic_test.go, virtcontainers/pkg/cgroups/manager.go, virtcontainers/pkg/cgroups/utils.go, virtcontainers/pkg/cgroups/utils_test.go, virtcontainers/pkg/oci/utils.go, virtcontainers/sandbox.go
kata relies on the cgroup created and configured by container engine,
but sometimes the sandbox cgroup is not configured (podman) or the
cgroup implementation is very restrictive (cgroups v2) that the
workload may not have access to any device.
Use the initial (sandbox) cgroup configuration to have a functional
cgroup where the hypervisor can be started, the container engine (e.g k8s)
it's free to modify it later.
fixes #2605
=> virtcontainers: apply constrains to the sandbox cgroup

virtcontainers/api.go, virtcontainers/device/config/pmem.go
Call the `device/config` package `SetLogger()` function to ensure all its log
records contain all required structured logging fields.
Fixes: #2643
=> pmem: Add a SetLogger call

versions.yaml, virtcontainers/clh.go, virtcontainers/pkg/cloud-hypervisor/client/README.md, virtcontainers/pkg/cloud-hypervisor/client/api/openapi.yaml, virtcontainers/pkg/cloud-hypervisor/client/api_default.go, virtcontainers/pkg/cloud-hypervisor/client/docs/DefaultApi.md, virtcontainers/pkg/cloud-hypervisor/client/docs/MemoryConfig.md, virtcontainers/pkg/cloud-hypervisor/client/docs/PmemConfig.md, virtcontainers/pkg/cloud-hypervisor/client/model_memory_config.go, virtcontainers/pkg/cloud-hypervisor/client/model_pmem_config.go, virtcontainers/pkg/cloud-hypervisor/cloud-hypervisor.yaml
Changes:
f5debc4 build(deps): bump libssh2-sys from 0.2.16 to 0.2.17
37dfb4c build(deps): bump hermit-abi from 0.1.11 to 0.1.12
e1a07ce vmm: vm: Unpark the threads before shutdown when the current state is paused
1df38da vmm, tests: Make specifying a size optional for virtio-pmem
7481e4d vmm: config: Validate that shared memory is enabled if using vhost-user
2ac6971 vmm: MemoryManager: Cleanup the usage of std::ffi/io/result
3f42f86 vmm: Add the 'shared' and 'hugepages' controls to MemoryConfig
d6aa717 build(deps): bump syn from 1.0.17 to 1.0.18
3eaeba4 vm-virtio: Fix FS_IO callback for virtio-fs
df14a68 build(deps): bump smallvec from 1.3.0 to 1.4.0
e685854 gh: Separate the build and release jobs
c790bba tests: Migrate from Ubuntu Eoan to Focal
e525af7 build(deps): bump ryu from 1.0.3 to …
=> versions: Move to latest cloud-hypervisor

virtcontainers/kata_agent.go, virtcontainers/kata_agent_test.go
Check if shm mount is backed by empty-dir memory based volume.
If so let the logic to handle epehemeral volumes take care of this
mount, so that shm mount within the container is backed by tmpfs mount
within the the container in the VM.
Fixes #2631
=> shm: handle shm mount backed by empty-dir memory volumes

versions.yaml, virtcontainers/clh.go, virtcontainers/clh_test.go, virtcontainers/pkg/cloud-hypervisor/client/README.md, virtcontainers/pkg/cloud-hypervisor/client/api/openapi.yaml, virtcontainers/pkg/cloud-hypervisor/client/api_default.go, virtcontainers/pkg/cloud-hypervisor/client/docs/DefaultApi.md, virtcontainers/pkg/cloud-hypervisor/client/docs/DiskConfig.md, virtcontainers/pkg/cloud-hypervisor/client/docs/FsConfig.md, virtcontainers/pkg/cloud-hypervisor/client/docs/NetConfig.md, virtcontainers/pkg/cloud-hypervisor/client/docs/PmemConfig.md, virtcontainers/pkg/cloud-hypervisor/client/docs/VmConfig.md, virtcontainers/pkg/cloud-hypervisor/client/docs/VsockConfig.md, virtcontainers/pkg/cloud-hypervisor/client/model_disk_config.go, virtcontainers/pkg/cloud-hypervisor/client/model_fs_config.go, virtcontainers/pkg/cloud-hypervisor/client/model_net_config.go, virtcontainers/pkg/cloud-hypervisor/client/model_pmem_config.go, virtcontainers/pkg/cloud-hypervisor/client/model_vm_config.go, virtcontainers/pkg/cloud-hypervisor/client/model_vsock_config.go, virtcontainers/pkg/cloud-hypervisor/cloud-hypervisor.yaml
Cloud-hypervisor [v0.7.0](https://github.com/cloud-hypervisor/cloud-hypervisor/releases/tag/v0.7.0) was released earlier today. We definitely want to stay updated with it. Also, it is nicer to use the v0.7.0 tag in our versions.yaml for our next Kata release.
This patch also updated the use of `VsockConfig` to `Vmconfig` for booting the hypervisor. It reflects CLH's [changes](https://github.com/cloud-hypervisor/cloud-hypervisor/commit/10348f73e45fcfbd70f818e9dec2dc6d952febfb) on Vsock HTTP API and support.
Fixes: kata-containers#2658
=> versions: Move to cloud-hypervisor v0.7.0

versions.yaml, virtcontainers/clh.go, virtcontainers/clh_test.go, virtcontainers/pkg/cloud-hypervisor/client/README.md, virtcontainers/pkg/cloud-hypervisor/client/api/openapi.yaml, virtcontainers/pkg/cloud-hypervisor/client/api_default.go, virtcontainers/pkg/cloud-hypervisor/client/docs/DefaultApi.md, virtcontainers/pkg/cloud-hypervisor/client/docs/DiskConfig.md, virtcontainers/pkg/cloud-hypervisor/client/docs/FsConfig.md, virtcontainers/pkg/cloud-hypervisor/client/docs/MemoryConfig.md, virtcontainers/pkg/cloud-hypervisor/client/docs/NetConfig.md, virtcontainers/pkg/cloud-hypervisor/client/docs/PmemConfig.md, virtcontainers/pkg/cloud-hypervisor/client/docs/VmConfig.md, virtcontainers/pkg/cloud-hypervisor/client/docs/VsockConfig.md, virtcontainers/pkg/cloud-hypervisor/client/model_disk_config.go, virtcontainers/pkg/cloud-hypervisor/client/model_fs_config.go, virtcontainers/pkg/cloud-hypervisor/client/model_memory_config.go, virtcontainers/pkg/cloud-hypervisor/client/model_net_config.go, virtcontainers/pkg/cloud-hypervisor/client/model_pmem_config.go, virtcontainers/pkg/cloud-hypervisor/client/model_vm_config.go, virtcontainers/pkg/cloud-hypervisor/client/model_vsock_config.go, virtcontainers/pkg/cloud-hypervisor/cloud-hypervisor.yaml
Changes:
2d251652 clh: vsock: Supply the right VsockConfig to Vmconfig
fcc9e93b versions: Move to cloud-hypervisor v0.7.0
34be9e0c clh: memory: remove pmem size argument
9798e8a5 versions: Move to latest cloud-hypervisor
=> clh: backport: Move to v0.7.0

cli/kata-check_test.go, cli/utils.go
For stable versions the format used `x.y.z`.
kata-env was failing trying to make a new release from 1.11.0-rc to
1.11.0
This fix kata-env for releases 1.11+ where this regression was
introduced.
Fixes: #2674
=> utils: Fix case version check for stable releases

virtcontainers/qemu.go
If we take one of the error paths from setupVirtiofsd() after
opening the fd variable, the fd.Close() function is not called.
Fixes: #2683
Signed-off-by: Christophe de Dinechin <dinechin@redhat.com>
=> qemu: Don't leak file descriptors in case of error

virtcontainers/clh.go, virtcontainers/utils/utils.go, virtcontainers/virtiofsd.go, virtcontainers/virtiofsd_test.go
Send virtiofsd logs to syslog in the same way that qemu implementation
does. This requires not to wait for messages from virtiofsd stdout. This
takes the qemu implementation approach. Give the socket fd to virtiofsd.
Use systemd-cat to collect hypervisor output. The `systemd-cat` program
will open a journal fd and call `cat(1)` to redirect all the output to
the fd. This requires an extra binary to read from hypervisor stdout
(that has combined stdin, stderr and serial terminal). But because it is
cat the overhead is minimal and only is started on Kata debug mode.
Fixes: #2439
=> clh: Improve logging for cloud hypervisor

Gopkg.lock, Gopkg.toml, vendor/github.com/intel/govmm/qemu/qemu.go
Enable virtio-fs support for ppc64le
shortlog:
b2aa022 Enable Numa support for Power (ppc64le) architecture
29529a5 Add rt clock definition for rtc clock in qemu
0e98b61 qemu: Add max_ports option to virtio-serial device
Fixes #2056 
=> vendor: Update govmm to enable virtio-fs support for ppc64le

cli/config/configuration-clh.toml.in, virtcontainers/clh.go, virtcontainers/clh_test.go
This patch enables the disk (block) device hotplug in Kata with cloud-hypervisor (CLH). With this patch, the container image can be shared from host with guest as a block device when the docker is configured to use `devicemapper` as its the storage driver. Also, this patch sets the default block device driver to `virtio-blk` in the hypervisor configuration (toml) file, as it is required by the disk (block) device model from cloud-hypervisor.
Fixes: #2570
=> clh: Enable disk block device hotplug support

.ci/go-test.sh, .ci/setup.sh
This PR skips the installation of virtcontainers in order to enable
the podman clh CI job.
Fixes #2704
=> ci: Do not install virtcontainers with podman clh

arch/ppc64le-options.mk
The bug got introduced in kata-containers/runtime@9e4b610
Fixes #2707 
=> qemu: Remove PMU feature for Power (ppc64le) platform

arch/ppc64le-options.mk, virtcontainers/qemu_ppc64le.go
Hard-coded Qemu machine options create challenges when running Kata
with latest Qemu (v5.0) or with latest processor version.
This patch makes it configurable by leveraging the existing machine_accelerators
option in configuration.toml.
This patch fixes #2657 for ppc64le
=> qemu: Remove hard-coding of Qemu machine options for ppc64le

virtcontainers/agent.go, virtcontainers/api_test.go, virtcontainers/clh.go, virtcontainers/container.go, virtcontainers/kata_agent.go, virtcontainers/kata_agent_test.go, virtcontainers/mount.go, virtcontainers/mount_test.go, virtcontainers/noop_agent.go, virtcontainers/noop_agent_test.go, virtcontainers/qemu.go, virtcontainers/qemu_test.go, virtcontainers/virtcontainers_test.go, virtcontainers/vm.go
We need to make sure containers cannot modify host path unless it is explicitly shared to it. Right now we expose an additional top level shared directory to the guest and allow it to be modified. This is less ideal and can be enhanced by following method:
1. create two directories for each sandbox:
-. /run/kata-containers/shared/sandboxes/$sbx_id/mounts/, a directory to hold all host/guest shared mounts
-. /run/kata-containers/shared/sandboxes/$sbx_id/shared/, a host/guest shared directory (9pfs/virtiofs source dir)
2. /run/kata-containers/shared/sandboxes/$sbx_id/mounts/ is bind mounted readonly to /run/kata-containers/shared/sandboxes/$sbx_id/shared/, so guest cannot modify it
3. host-guest shared files/directories are mounted one-level under …
=> vc: make host shared path readonly

.github/auto-comment.yml
To remind PR contributors that we have moved development to the 2.0-dev
branch and what to do if the change is really required for the 1.x
releases.
Fixes: #2730
Signed-off-by: Peng Tao <bergwolf@hyper.sh>
=> github: add auto comment bot

arch/ppc64le-options.mk, virtcontainers/qemu_ppc64le.go
The default ppc64le Qemu binary path was specific for Ubuntu.
This patch fixes the default binary path for both Fedora and Ubuntu
Fixes: #2738
=> qemu: Fix Qemu binary path for Power across distros

containerd-shim-v2/service.go
In service#StartShim, there is no applicable error variable which is checked by deferred func because the err variable is redefined:
```
if err := cdshim.WritePidFile("shim.pid", cmd.Process.Pid); err != nil {
```
This PR fixes #2727.
=> shimv2: check correct error variable for deferred func in service#StartShim

virtcontainers/qemu.go
Add default value for Clock, otherwise rtc parameter will be dropped
by Valid function.
Also there are 3 type value for Clock in qemu, "host/rt/vm".
Signed-off-by: Shuicheng Lin <shuicheng.lin@intel.com>
=> Fix rtc parameter is not set to qemu

virtcontainers/acrn.go, virtcontainers/sandbox.go
In Acrn#appendImage(), we should check the error return value from GetAndSetSandboxBlockIndex().
This PR also names the error return for getAndSetSandboxBlockIndex so that the deferred func checks the right variable.
Fixes #2726
=> virtcontainers: drop deferred func for GetAndSetSandboxBlockIndex()

Makefile, cli/config/configuration-clh.toml.in, pkg/katautils/config.go
Today some options for virtiofsd could improve compatibility
for example xattrs for dnf or cache=auto for file consistency
for changes in the host. Allow users can enabled as requiered.
Fixes: #2735
=> clh: Allow add virtiofs args and cache options from config

virtcontainers/container.go, virtcontainers/container_test.go, virtcontainers/fc.go, virtcontainers/mount.go, virtcontainers/mount_test.go, virtcontainers/syscall_test.go
This includes 
00da1270 unit-test: refine related unit tests
9d3022a8 mount: modify func bindMount
231bbe2c vc: validate container path when cleaning up
11f4560b vc: do not follow symlink when umounting contanier host path
=> Backport bug fixes to 1.10

virtcontainers/clh.go, virtcontainers/kata_agent.go, virtcontainers/kata_agent_test.go
This patch allows agent to use the `VirtPath` field of block device for creating containers, beacuse the `PCIAddr` field may not be available (e.g. when using cloud-hypervisor).
Fixes: #2720
=> clh: Support to add block device and volumes from host to container

cli/kata-env.go, cli/kata-env_ppc64le_test.go
kata-env output always shows "VMContainerCapable=false" on Power.
This patch fixes the same.
Fixes: #2740
=> cli: Fix kata-env output on Power

Makefile
Today for virtiofsd kata sets by default `cache=always`. This option is
useful for performance but if the shared files are modified from the
host changes are not updated in the guest as virtiofsd uses cached value
all time.
This patch changes to  `cache=auto` to fix consistency issues. The option
can still be set to always if it is wanted by the user.
Fixes: #2748
=> virtiofsd: Use cache auto

Gopkg.lock, Gopkg.toml, cli/config/configuration-fc.toml.in, cli/config/configuration-qemu-virtiofs.toml.in, cli/config/configuration-qemu.toml.in, pkg/katautils/config-settings.go.in, pkg/katautils/config.go, vendor/github.com/intel/govmm/qemu/qemu.go, virtcontainers/hypervisor.go, virtcontainers/pkg/annotations/annotations.go, virtcontainers/pkg/oci/utils.go, virtcontainers/pkg/oci/utils_test.go, virtcontainers/qemu.go, virtcontainers/qemu_amd64.go, virtcontainers/qemu_arch_base.go, virtcontainers/qemu_arch_base_test.go, virtcontainers/qemu_arm64.go, virtcontainers/qemu_ppc64le.go, virtcontainers/qemu_s390x.go
Add vIOMMU support to q35 machines
- Use vIOMMU support added to govmm ([link](https://github.com/intel/govmm/commit/7efaf0b1cde3883a3f38e656c2223f38b9086469))
- Add a configuration.toml switch and a Pod annotation
- If enabled:
- Add "kernel_irqchip=split" to machine options.
- Add iommu device: "--device intel-iommu,intremap=on,device-iotlb=on,caching-mode=on"
- Add iommu params to kernel command line
Fixes #2694 
Signed-off-by: Adrian Moreno <amorenoz@redhat.com>
=> Add vIOMMU support to qemu q35

virtcontainers/qemu_arm64.go
This is breakage was introduced by the following commit[0].
[0]: https://github.com/kata-containers/runtime/commit/66b54f88c5f4023bbd69c02d0b3274e8567e8b35
Fixes: #2753
=> Fix ARM build failure

virtcontainers/sandbox.go
In newSandbox(), the deferred func checks err variable which is different from the one declared within the useOldStore(ctx) case.
This PR makes the deferred func check the correct error variable.
=> Check the correct error variable for sandbox creation

versions.yaml, virtcontainers/clh.go, virtcontainers/clh_test.go, virtcontainers/pkg/cloud-hypervisor/client/api/openapi.yaml, virtcontainers/pkg/cloud-hypervisor/client/docs/DiskConfig.md, virtcontainers/pkg/cloud-hypervisor/client/docs/FsConfig.md, virtcontainers/pkg/cloud-hypervisor/client/docs/VsockConfig.md, virtcontainers/pkg/cloud-hypervisor/client/model_disk_config.go, virtcontainers/pkg/cloud-hypervisor/client/model_fs_config.go, virtcontainers/pkg/cloud-hypervisor/client/model_vsock_config.go, virtcontainers/pkg/cloud-hypervisor/cloud-hypervisor.yaml
This patch updated the version of cloud-hypervisor to its most recently release [v0.8.0](https://github.com/cloud-hypervisor/cloud-hypervisor/releases/tag/v0.8.0). Also, there are few changes to the clh driver to accommodate the changes from clh's HTTP API.
Major new functionalities added in clh v0.8.0 include Experimental
Snapshot and Restore Support, Experimental ARM64 Support, 5-level guest
paging support, etc. Also, there are quite some bug fixings and CLI/API
changes for cleanup. More details can be found in the release note:
https://github.com/cloud-hypervisor/cloud-hypervisor/releases/tag/v0.8.0.
Fixes: #2771
=> versions: Move to cloud-hypervisor v0.8.0

virtcontainers/qemu_amd64.go, virtcontainers/qemu_amd64_test.go
When an x86 sandbox has a vIOMMU (needed for VFIO), it needs the
'kernel_irqchip=split' option or it can't start.  fdcd1f3a2 attempts to set
that, but ends up just writing it to a temporary (looks like Go for range
loops pass by value).
Fixes: fdcd1f3a2 "qemu: enable iommu on q35"
Signed-off-by: David Gibson <david@gibson.dropbear.id.au>
=> qemu: Fix kernel_irqchip=split option for IOMMU enabled sandbox

Makefile
If not used, SELinux support will never be enabled.
It's important to mention that this issue has been already been fixed on
kata-containers/kata-containers, unintentionally, as part of
https://github.com/kata-containers/kata-containers/commit/e90c5d45b3ceef
Fixes: #2776
=> shimv2: Use BUILDTAGS when building shimv2

virtcontainers/api.go, virtcontainers/pkg/cgroups/manager.go
Call the `pkg/cgroups` package `SetLogger()` function to ensure all its log
records contain all required structured logging fields.
Fixes: #2782
=> virtcontainers: Fix structured logging in cgroups package

Makefile
If not used, SELinux support will never be enabled.
It's important to mention that this issue has been already been fixed on
kata-containers/kata-containers, unintentionally, as part of
https://github.com/kata-containers/kata-containers/commit/e90c5d45b3ceef
Fixes: #2776
(cherry picked from commit c51baf8df595bb19b84366860d07bd89841320c5)
=> [backport stable-1.11] shimv2: Use BUILDTAGS when building shimv2

arch/ppc64le-options.mk, cli/kata-env.go, cli/kata-env_ppc64le_test.go, virtcontainers/qemu_ppc64le.go
This PR backports the following Power arch fixes to stable-1.11 branch
- https://github.com/kata-containers/runtime/commit/2c3b3440b98b6254f4dd9504c19da04141eade0d qemu: Fix Qemu binary path for Power across distros
- https://github.com/kata-containers/runtime/commit/cecd7f7f4818a6c8e0981feb18c473c0d8dea101 cli: Fix kata-env output on Power
- https://github.com/kata-containers/runtime/commit/3eee00eca5ffec9129d11e7132d8669f7eeee336 qemu: Remove hard-coding of Qemu machine options for ppc64le
=> Backport Power arch fixes to 1.11

cli/kata-env_test.go, containerd-shim-v2/create_test.go, pkg/katatestutils/utils.go, pkg/katautils/config_test.go, virtcontainers/qemu.go
The commits backported are bringing fixes for:
- #2686 - katatestutils should use config.virtioFSDaemon
- #2682 - Runtime crash when virtiofsd is not executable
=> [backport | stable-1.11] virtiofs fixes

containerd-shim-v2/service.go, virtcontainers/acrn.go, virtcontainers/sandbox.go
The commits backported are bringing fixes for:
- #2727 - Ineffective error variable for deferred func in service#StartShim 
- #2726 - the error return from GetAndSetSandboxBlockIndex() should be checked
- #2759 - Ineffective error variable check for sandbox creation
=> [backport | stable-1.11] Backport Ted Yu fixes

virtcontainers/api.go, virtcontainers/bridgedmacvlan_endpoint.go, virtcontainers/device/config/config.go, virtcontainers/device/drivers/generic.go, virtcontainers/device/drivers/vfio.go, virtcontainers/endpoint.go, virtcontainers/ipvlan_endpoint.go, virtcontainers/macvtap_endpoint.go, virtcontainers/network.go, virtcontainers/persist/api/device.go, virtcontainers/physical_endpoint.go, virtcontainers/qemu.go, virtcontainers/sandbox.go, virtcontainers/tap_endpoint.go, virtcontainers/tuntap_endpoint.go, virtcontainers/veth_endpoint.go, virtcontainers/vhostuser_endpoint.go, virtcontainers/vhostuser_endpoint_test.go
Create the cgroup manager once the network has been created, this way the
list of device will include the network VFIO devices attached to the sandbox,
when the physical enpoint is the network driver.
fixes #2774
@yadzhang please take a look
=> virtcontainer/cgroup: create cgroup manager after creating the network

virtcontainers/clh.go
Along with the release of cloud-hypervisor v0.8.0, this option has been
deprecated. clh now enforces to use the alternative controls,
e.g. "shared" and "hugepages", which can infer the backing file
paths. Also, we don't use "hugepages" in kata, so we are fine now as the
"shared" control  is already enabled.
Fixes: #2803
=> clh: Remove the use of deprecated '--memory file=' parameter

versions.yaml
New features that can improve/impact in kata containers:
x86:
VMX features can be enabled/disabled via the "-cpu" flag.
When nested virtualization is enabled with an option like
"-cpu Haswell,+vmx", the set of VMX features will also be constrained to
what was available on the corresponding CPU model.
New "microvm" machine type that has virtio-mmio instead of PCI, and no ACPI
support (so no hotplug too). The new machine type is meant as a baseline
for performance optimizations of QEMU, firmware and guests. While inspired
by Firecracker it is not entirely compatible with it (for example it does
not have Firecracker's userspace IP stack and MicroVM Metadata Service).
Reduce memory footprint when booting uncompressed kernels.
ARM:
We now correctly support more than 256 CPUs when using KVM
The …
=> versions: update QEMU to 5.0.0

containerd-shim-v2/create.go, containerd-shim-v2/utils.go
Removing code that existed as a workaround for a bug in
how shared process namespaces were handled in the agent.
That has been long fixed in the agent.
With this, sharedPidNs will now work with shimv2.
Fixes #2788
=> shimv2 : Remove workaround for sharedPidNs

virtcontainers/device/manager/utils.go, virtcontainers/device/manager/utils_test.go
When checking if a device is an emulated vhost-user-blk or
vhost-user-scsi one, we should not only check for their major number but
also their device node type. They must be block devices.
Fixes: #2822
Signed-off-by: Samuel Ortiz <sameo@linux.intel.com>
=> virtcontainers: vhost-user-blk/scsi are block device nodes

virtcontainers/sandbox.go
A container that is created and added to a sandbox can still fail
the final creation steps. In this case, the container must be stopped
and have its resources cleaned up to prevent leaking sandbox mounts.
Fixes #2816
Signed-off-by: Evan Foster <efoster@adobe.com>
=> sandbox: Stop and clean up containers that fail to create

virtcontainers/types/bridges_test.go
Add function that creates new bridges to increase unit test coverage
for virtcontainers/types/bridges.
Fixes #2827
=> virtcontainers: Add to bridges unit test

versions.yaml
Versions is pointing to virtiofs kernel branch,
recently it changed and CI is broken.
Lets use a new tag for kata.
The tag now include the kernel version so will
be shown on release notes.
Depends-on: github.com/kata-containers/packaging#1098
Fixes: #2842
=> versions: Use new kata tag for virtiofs kernel

virtcontainers/pkg/cgroups/manager.go, virtcontainers/pkg/cgroups/manager_test.go, virtcontainers/pkg/cgroups/utils.go, virtcontainers/pkg/cgroups/utils_test.go, virtcontainers/sandbox.go
Systemd cgroups aren't supported today in Kata. This is a first pass at properly creating applicable subsystem croups when using a systemd CPU manager.
=> Fixup systemd cgroup handling

virtcontainers/types/capabilities_test.go
Add function that tests multiqueue functions in types/capabilities.go.
Fixes #2844
=> virtcontainers: Add function to capabilities test

virtcontainers/qemu_arch_base.go, virtcontainers/qemu_arm64.go
backport this from kata-containers.
As the current qemu of arm64 is so old, the new multidev parameter
in 9pfsdev is not supported on arm64, so disabled it temporarily.
Fixes:#2868
@devimc @jodh-intel
=> qemu: remove multidev in qemu/fsdev parameter on arm64

Gopkg.lock, Gopkg.toml, vendor/github.com/intel/govmm/qemu/qemu.go, virtcontainers/qemu.go, virtcontainers/qemu_test.go
The Kata architecture does not support rebooting VMs (the lifecycle being start/exec/kill) and if a VM is killed (e.g. using sysrq-trigger), the VM does not exit fully and other layers do not notice the state change.
The QEMU instance needs to be told to exit and not reboot which can be done by passing the --no-reboot command line option when creating the VM.
Fix for  #2866
=> qemu: Set govmmQemu NoReboot Knob

versions.yaml
Upgrade Alpine version from unsupported 3.7 to supported 3.12
Fixes #2873
Signed-off-by: Jan Schintag <jan.schintag@de.ibm.com>
=> initrd: Increase Alpine Version to 3.12

virtcontainers/types/container_test.go
Add unit tests for types/container.go. Tests were adapted from
sandbox_test.go since ContainerState is a sandbox state structure and
the transition tests are the same.
Fixes #2856
=> virtcontainers: Add unit test for types/container.go

virtcontainers/utils/utils_test.go
Expand unit tests for virtcontainers/utils/utils.go to include testing
CleanupFds, CPU calculations, ID string creation, and memory alignment
functions.
Fixes #2877
=> virtcontainers: Add to utils unit tests

Gopkg.lock, Gopkg.toml, cli/config/configuration-qemu-virtiofs.toml.in, cli/config/configuration-qemu.toml.in, pkg/katautils/config-settings.go.in, pkg/katautils/config.go, vendor/github.com/intel/govmm/qemu/qemu.go, virtcontainers/hypervisor.go, virtcontainers/pkg/annotations/annotations.go, virtcontainers/pkg/oci/utils.go, virtcontainers/pkg/oci/utils_test.go, virtcontainers/qemu.go
qemu: Add iommu annotations for qemu for s390x ccw, so that the supported devices can make use of that.
for virtcontainers/hypervisor
add iommu_platform=on option for virtio devices
Fixes https://github.com/kata-containers/runtime/issues/2830
Signed-off-by: Qi Feng Huo <huoqif@cn.ibm.com>
=> qemu: add annotations for iommu_platform for s390x virtio devices

virtcontainers/clh.go, virtcontainers/clh_test.go
This patch enables kata+clh to unplug block devices, which is required
to pass cri-o integration tests.
Fixes: #2832
=> clh: Add support to unplug block devices

containerd-shim-v2/container.go, containerd-shim-v2/exec.go, containerd-shim-v2/service.go, containerd-shim-v2/start.go, containerd-shim-v2/stream.go
It should wait until the stdin io copy
termianted to close the process's io stream,
otherwise, it would miss forwarding some contents
to process stdin.
Fixes: #2884
Signed-off-by: fupan.lfp <fupan.lfp@antgroup.com>
=> shimv2: fix the issue of close IO stream (backport from 2.0)

virtcontainers/sandbox.go
sandbox: Stop and clean up containers that fail to create
A container that is created and added to a sandbox can still fail
the final creation steps. In this case, the container must be stopped
and have its resources cleaned up to prevent leaking sandbox mounts.
Fixes #2816
Signed-off-by: Evan Foster <efoster@adobe.com>
(cherry picked from commit 337f2e0c7ba5f8dff5ac46e568886a42ca56d683)
=> [backport | stable-1.11] sandbox: Stop and clean up containers that fail to create

virtcontainers/clh.go
The function for getting version info was failing on a system
without any indication of the error. Add some error handling
around this function.
Fixes: github.com/kata-containers/kata-containers#463
=> clh: Add some error handling for clh

virtcontainers/device/config/config.go, virtcontainers/device/drivers/utils.go
Currently, isPCIeDevice() attempts to determine if a (host) device is
PCI-Express capable by looking up its link speed via the PCI slots
information in sysfs.  This is a) complicated and b) wrong.  PCI-e devices
don't have to have slots information, so this frequently fails.
Instead determine if devices are PCI-e by checking for the presence of
PCIe extended configuration space by looking at the size of the "config"
file in sysfs.
Fixes: #2678
Signed-off-by: David Gibson <david@gibson.dropbear.id.au>
=> Correct isPCIeDevice logic

Makefile, cli/containerd-shim-kata-v2/main.go
All components should support a `--version` option to allow clear identification of the version of the component being used.
Note that the build changes are required to allow the shim binary to access the golang code generated by the build (such as the `version` variable).
This is a backport of https://github.com/kata-containers/kata-containers/pull/308.
Fixes: #2886.
=> shimv2: Add a "--version" cli option

virtcontainers/clh.go
We kept observing instabilities from CLH CI jobs periodically. To
separate the random failures caused by `seccomp` from other failures,
this patch disables the 'seccomp' option from clh in kata for now. We
will bring this option back after completing the 'seccomp' filter lists
based on Kata's CI workload.
Fixes: #2899
=> clh: Disable the 'seccomp' option temporarily

versions.yaml
Versions is pointing to virtiofs kernel branch,
recently it changed and CI is broken.
Lets use a new tag for kata.
The tag now include the kernel version so will
be shown on release notes.
Depends-on: github.com/kata-containers/packaging#1139
Fixes: #2842
=> backport: versions: Use new kata tag for virtiofs kernel

virtcontainers/sandbox.go
When a one-shot pod dies in CRI-O, the shimv2 process isn't killed until the pod is actually deleted, even though the VM is shut down. In this case, the shim appears to busyloop when attempting to talk to the (now dead) agent via VSOCK. To address this, we disconnect from the agent after the VM is shut down.
This is especially catastrophic for one-shot pods that may persist for hours or days, but it also applies to any shimv2 pod where Kata is configured to use VSOCK for communication.
Backport of https://github.com/kata-containers/kata-containers/pull/556 to kata-containers/runtime 1.11 branch.
Fixes #2719
Signed-off-by: Evan Foster <efoster@adobe.com>
(cherry picked from commit 227cba6b10a8dcbda6a0e2f82710a7c0711dd8f9)
=> [backport | stable-1.11] sandbox: Disconnect from agent after VM shutdown

virtcontainers/sandbox.go
When a one-shot pod dies in CRI-O, the shimv2 process isn't killed until the pod is actually deleted, even though the VM is shut down. In this case, the shim appears to busyloop when attempting to talk to the (now dead) agent via VSOCK. To address this, we disconnect from the agent after the VM is shut down.
This is especially catastrophic for one-shot pods that may persist for hours or days, but it also applies to any shimv2 pod where Kata is configured to use VSOCK for communication.
Backport of https://github.com/kata-containers/kata-containers/pull/556 to kata-containers/runtime master branch.
Fixes #2719
Signed-off-by: Evan Foster <efoster@adobe.com>
=> [backport | master] sandbox: Disconnect from agent after VM shutdown

virtcontainers/utils/compare_test.go
Add unit test for virtcontainers/utils/compare.go to increase overall
coverage.
Fixes #2928
=> virtcontainers: Add unit test for utils/compare.go

Makefile, cli/containerd-shim-kata-v2/main.go
This is a backport of https://github.com/kata-containers/runtime/pull/2887 to the stable-1.11 branch.
=> [stable-1.11] shimv2: Add a "--version" cli option

virtcontainers/device/config/config.go, virtcontainers/device/drivers/utils.go
Currently, isPCIeDevice() attempts to determine if a (host) device is
PCI-Express capable by looking up its link speed via the PCI slots
information in sysfs.  This is a) complicated and b) wrong.  PCI-e devices
don't have to have slots information, so this frequently fails.
Instead determine if devices are PCI-e by checking for the presence of
PCIe extended configuration space by looking at the size of the "config"
file in sysfs.
Fixes: #2678
Signed-off-by: David Gibson <david@gibson.dropbear.id.au>
(cherry picked from commit 6bf93b23159e3f8eab62e9c2fc26ed9946a818e9)
=> drivers: Correct isPCIeDevice logic

virtcontainers/sandbox.go
fixes: #2882
reason: If error happens after container create and before sandbox
updateResouce in the `CreateContainer()`, then delete sandbox
forcefully will return error because s.config.Containers config not
flushed into persist store.
Signed-off-by: jiangpengfei <jiangpengfei9@huawei.com>
=> virtcontainers: fix delete sandbox failed problem

.ci/openshift-ci/build.sh, .ci/openshift-ci/images/Dockerfile, .ci/openshift-ci/images/entrypoint.sh
Enable openshift-ci on runtime repository.
Fixes: github.com/kata-containers/tests#2527
Depends-on: github.com/kata-containers/tests#2802
Signed-off-by: Wainer dos Santos Moschetta <wainersm@redhat.com>
=> ci/openshift-ci: Enable openshift-ci

virtcontainers/pkg/cgroups/manager.go, virtcontainers/sandbox.go, virtcontainers/sandbox_test.go
*   CPUSet cgroup allows for pinning the memory associated with a cpuset to
a given numa node. Similar to cpuset.cpus, we should take cpuset.mems
into account for the sandbox-cgroup that Kata creates.
*  If quota is not being enforced on any containers but CPUsets are
specified, take the number of CPU sets into account when sizing the
virtual machine.
=> cpuset: fixes to address VM sizing and constraining based on cpuset.mems

data/kata-collect-data.sh.in
In show_container_mgr_details(), it used "cat /etc/crio/crio.conf"
instead of "crio config".
Fixes: #2964
Signed-off-by: Qian Cai <cai@redhat.com>
=> scripts: Don't use hard-coded crio config

Makefile, cli/config-generated.go.in, cli/kata-check.go, cli/release.go, cli/release_test.go
Update `kata-check` to see if there is a newer version available for download. Useful for users installing static packages (without a package manager).
Fixes: #2975.
=> kata-check: check for newer release

virtcontainers/container.go
Kata doesn't map any numa topologies in the guest. Let's make sure we
clear the Cpuset fields before passing container updates to the
guest. Without this, we could encounter a runtime failure:
```
process_linux.go:297: applying cgroup configuration for process caused
"failed to write 0,1 to cpuset.mems: writea 0,1 to cpuset.mems: write
0,1 to cpuset.mems: write /sys/fs/cgroup/cpuset .... /cpuset.mems:
numerical result out of range"": unknown
```
Note, in the future we may want to have a vCPU to guest CPU mapping and
still include the cpuset.Cpus. Until we have this support, clear this as
well.
Fixes: #2176
Depends-on: github.com/kata-containers/tests#2846
=> cpuset: don't set cpuset.mems in the guest

versions.yaml
This adds the 'newest-version' property which determines the OpenShift
version used to run the e2e tests.
Fixes: github.com/kata-containers/tests#2860
Signed-off-by: Wainer dos Santos Moschetta <wainersm@redhat.com>
=> versions: Add newest-version for OpenShift

Makefile
virtiofs DAX support is not stable today, there are
a few corner cases to make it default.
Fixes: #2999
=> virtiofs: Disable DAX

versions.yaml
Now, the qemu version used in arm is so old. As some new features have merged
in current qemu, so it's time to upgrade it.
Fixes: #2989
Signed-off-by: Edmond AK Dantes <edmond.dantes.ak47@outlook.com>
@jon @liwei
=> version: upgrade qemu version to v5.1.0 for arm64

virtcontainers/virtiofsd_test.go
Fix typo in virtiofsd_test.go
Fixes: #2948
Signed-off-by: zhanghj <zhanghj.lc@inspur.com>
=> virtiofsd: fix typo in test code

containerd-shim-v2/service.go
Sometimes shim process cannot be shutdown because of container list
is not empty. This container list is written in shim service, while
creating container. We find that if containerd cancel its Create
Container Request due to timeout, but runtime didn't handle it properly
and continue creating action, then this container cannot be deleted at
all. So we should make sure the ctx passed to Create Service rpc call
is effective.
Fixes: #2992
=> shimv2: handle ctx passed by containerd

pkg/katautils/config.go, virtcontainers/hypervisor.go, virtcontainers/pkg/oci/utils.go, virtcontainers/pkg/oci/utils_test.go
Currently, we enforce a lower limit of 256MB for the defaultMemorySize.
In general case with QEMU, this isn't a major problem, since we'll just
eat the extra page table overhead, and only consume pages when needed.
The memcgroup in the guest should make sure it only utilizes requested
amount, not what is actually available.
However, this becomes very problematic when you use preallocated memory.
In the k8s case, the VMM will get OOM killed very quickly since the host's
memory cgroup (created by kubelet) will limit the entire sandbox to the
requests + pod overhead (on the order of 140 MB). We should allow the administrator
of kata to set a better default value, which should be much closer aligned
with what's used for PodOverhead (in the kube case).
Let's remove the artifical limit in kata, …
=> hypervisor: don't enforce a minimum memory setting

virtcontainers/sandbox.go, virtcontainers/sandbox_test.go
Fixes: #2921
runtime call fetchSandbox-->loadSandboxConfigFromOldStore-->store.NewVCSandboxStore--> ... f.initialize -->  os.MkdirAll(f.path, DirMode) 
and at last create /var/lib/vc/sbs/${sid}, but don't delete it before delete sandbox.
=> runtime: Fix /var/lib/vc/sbs/${sid} dir residual

virtcontainers/qemu.go, virtcontainers/qemu_arm64_test.go
The device pcie-pci-bridge in qemu will create a pci bus not pcie one.
It should be corrected for QEMUVIRT.
After correct this, vfio pci device can be hotplugged on arm64.
Fixes: #3016
@bergwolf @jodh-intel @devimc
=> arm64: correct bridge type for QEMUVIRT machine

.gitignore
This link is generated during build, but not ignored by .gitignore.
Signed-off-by: David Gibson <david@gibson.dropbear.id.au>
=> gitignore: Ignore cli/containerd-shim-kata-v2/config-generated.go

virtcontainers/container.go, virtcontainers/kata_agent.go, virtcontainers/mount.go, virtcontainers/mount_test.go
backport for https://github.com/kata-containers/runtime/pull/2915
buildContainerRootfs don't call bindMountContainerRootfs if container's rootfs use devicemapper
device in https://github.com/kata-containers/runtime/blob/master/virtcontainers/kata_agent.go#L1300,
so bindUnmountContainerRootfs should not be called if container's rootfs use devicemapper device
in https://github.com/kata-containers/runtime/blob/master/virtcontainers/container.go#L1123
Fixes: #2914
=> runtime: Don' call bindUnmountContainerRootfs for devicemapper device

virtcontainers/clh.go, virtcontainers/clh_test.go
In cloud-hypervisor, it provides a single unified way of unplugging
devices, e.g. the `/vm.RemoveDevice` HTTP API. Taking advantage of this
API, we can simplify our implementation of `hotplugRemoveDevice` in
`clh.go`, where we can consolidate similar code paths for different
device unplug (e.g. no need to implement `hotplugRemoveBlockDevice` and
`hotplugRemoveVfioDevice` separately). We will only need to retrieve the
right `deviceID` based on the type of devices, and use the single
unified HTTP API for device unplug.
Fixes: kata-containers#3001
=> clh: Consolidate the code path for device unplug

cli/delete.go, cli/kill.go
If sandbox/container's dir is not exist, the kill/delete will always fail,and this make kubelet/container delete it repeatedly
but fail always. In some kind of abnormal situation(e.g. kill -9 $pidofqemu),kata-runtime may kill/delete sandbox first, this make container'dir not exist, so kata-runtime should skip this error.
Fixes: #2959.
=> runtime: Ignore ENOENT in kill/delete

versions.yaml, virtcontainers/pkg/cloud-hypervisor/client/README.md, virtcontainers/pkg/cloud-hypervisor/client/api/openapi.yaml, virtcontainers/pkg/cloud-hypervisor/client/docs/BalloonConfig.md, virtcontainers/pkg/cloud-hypervisor/client/docs/CpusConfig.md, virtcontainers/pkg/cloud-hypervisor/client/docs/MemoryConfig.md, virtcontainers/pkg/cloud-hypervisor/client/docs/VmConfig.md, virtcontainers/pkg/cloud-hypervisor/client/docs/VmInfo.md, virtcontainers/pkg/cloud-hypervisor/client/model_balloon_config.go, virtcontainers/pkg/cloud-hypervisor/client/model_cpus_config.go, virtcontainers/pkg/cloud-hypervisor/client/model_memory_config.go, virtcontainers/pkg/cloud-hypervisor/client/model_vm_config.go, virtcontainers/pkg/cloud-hypervisor/client/model_vm_resize.go, virtcontainers/pkg/cloud-hypervisor/cloud-hypervisor.yaml
The release v0.11.0 of cloud-hypervisor features the following changes:
1 ) Improved Linux Boot Time, 2) `SIGTERM/SIGINT` Interrupt Signal,
Handling 3) Default Log Level Changed, 4) `io_uring` support by default
for `virtio-block` (on host kernel version 5.8+), 5) Windows Guest
Support, 6) New `--balloon` Parameter Added, 7) Experimental
`virtio-watchdog` Support, 8) Bug fixes.
Fixes: #3044
=> versions: Update cloud-hypervisor to release v0.11.0

virtcontainers/container.go, virtcontainers/kata_agent.go, virtcontainers/mount.go, virtcontainers/pkg/oci/utils.go, virtcontainers/sandbox_test.go
So that even if the guest is compromised, we still ensure that readonly volumes cannot be modified.
backport kata-containers/kata-containers#1062
=> readonly volume should be bind mounted readonly on the host

arch/arm64-options.mk
As cloud-hypervisor has been supported on arm64, let its configuration
build.
Fixes: #3027
@lifupan  @jodh-intel
=> clh: let clh config build for arm64

virtcontainers/sandbox.go
It does not affect the function,  but I think is better to add s.newStore.Destroy if globalSandboxList.addSandbox failed.
Fixes: #2919
=> Call s.newStore.Destroy if globalSandboxList.addSandbox failed

virtcontainers/sandbox.go
It does not affect the function,  but I think is better to add s.newStore.Destroy if globalSandboxList.addSandbox failed.
Fixes: #2919
this pr is a backport for https://github.com/kata-containers/runtime/pull/2920
=> runtime: Call s.newStore.Destroy if globalSandboxList.addSandbox

virtcontainers/container.go, virtcontainers/kata_agent.go, virtcontainers/mount.go, virtcontainers/pkg/oci/utils.go, virtcontainers/sandbox_test.go
3f0e61c runtime: mount shared mountpoint readonly
228e6eb runtime: readonly mounts should be readonly bindmount on the host
=> Backports: Read-only mount fixes for 1.11

virtcontainers/container.go, virtcontainers/kata_agent.go, virtcontainers/mount.go, virtcontainers/pkg/oci/utils.go, virtcontainers/sandbox_test.go
Backport to stable-1.12:
```
runtime: readonly mounts should be readonly bindmount on the host
runtime: mount shared mountpoint readonly
```
=> mount fixes for stable-1.12

versions.yaml, virtcontainers/pkg/cloud-hypervisor/client/README.md, virtcontainers/pkg/cloud-hypervisor/client/api/openapi.yaml, virtcontainers/pkg/cloud-hypervisor/client/docs/BalloonConfig.md, virtcontainers/pkg/cloud-hypervisor/client/docs/CpusConfig.md, virtcontainers/pkg/cloud-hypervisor/client/docs/MemoryConfig.md, virtcontainers/pkg/cloud-hypervisor/client/docs/VmConfig.md, virtcontainers/pkg/cloud-hypervisor/client/docs/VmInfo.md, virtcontainers/pkg/cloud-hypervisor/client/model_balloon_config.go, virtcontainers/pkg/cloud-hypervisor/client/model_cpus_config.go, virtcontainers/pkg/cloud-hypervisor/client/model_memory_config.go, virtcontainers/pkg/cloud-hypervisor/client/model_vm_config.go, virtcontainers/pkg/cloud-hypervisor/client/model_vm_resize.go, virtcontainers/pkg/cloud-hypervisor/cloud-hypervisor.yaml
The release v0.11.0 of cloud-hypervisor features the following changes:
1) Improved Linux Boot Time, 2) `SIGTERM/SIGINT` Interrupt Signal,
Handling 3) Default Log Level Changed, 4) `io_uring` support by default
for `virtio-block` (on host kernel version 5.8+), 5) Windows Guest
Support, 6) New `--balloon` Parameter Added, 7) Experimental
`virtio-watchdog` Support, 8) Bug fixes.
Fixes: #3044
(cherry picked from commit bc1d8833813c80da86449656134165d6d6511f72)
=> 1.12 backport: versions: Update cloud-hypervisor to release v0.11.0

cli/release.go, cli/release_test.go
Fix `kata-runtime kata-check`'s network version check which was failing
when the user was running a release candidate build and the latest
release was a major one, two examples of the error being:
- `BUG: unhandled scenario: current version: 1.12.0-rc0, latest version: 1.12.0`
- `BUG: unhandled scenario: current version: 2.0.0-rc0, latest version: 2.0.0`
Fixes: #3069.
=> release: Fix release candidate to major version upgrade check

versions.yaml, virtcontainers/clh.go, virtcontainers/pkg/cloud-hypervisor/client/api/openapi.yaml, virtcontainers/pkg/cloud-hypervisor/client/docs/FsConfig.md, virtcontainers/pkg/cloud-hypervisor/client/model_fs_config.go, virtcontainers/pkg/cloud-hypervisor/cloud-hypervisor.yaml
Guest consumes 120Mb more of memory when DAX is enabled and the default
FS cache size (8G) is used. Disable dax when it is not required
reducing guest's memory footprint.
Without this patch:
```
7fdea4000000-7fdee4000000 rw-s 18850589 /memfd:ch_ram (deleted)
Size:            1048576 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Rss:              187876 kB
```
With this patch:
```
7fa970000000-7fa9b0000000 rw-s 612001  /memfd:ch_ram (deleted)
Size:            1048576 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Rss:               57308 kB
Pss:               56722 kB
```
fixes #3072
=> [backport] runtime: clh: disable virtiofs DAX when FS cache size is 0

containerd-shim-v2/wait.go, virtcontainers/monitor.go
In some cases, for example agent crashed and not marked dead yet, the GetOOMEvent
will return errors like `connection reset by peer` or `ttrpc: closed`. Do a sleep
with 1 second (agent check interval) and let agent health check to do the check.
Fixes: #3064
Signed-off-by: bin liu <bin@hyper.sh>
=> runtime: sleep 1 second after GetOOMEvent failed

virtcontainers/shim.go
The https://go-review.googlesource.com/c/go/+/231638/ commit on Golang
introduced a failure on Kata Containers when the runtime is built with
golang 15.2+.
Fixes: #2982
=> virtcontainers: Don't set CTTY

versions.yaml
make proto in agent test on arm64 will fail when using docker 18.06
and using docker 19.03 can avoid that failure. So a new entry of
docker version for agent on arm64 is added.
Signed-off-by: Jianyong wu <jianyong.wu@arm.com>
Fixes: #3056
@jodh-intel @devimc
=> version: add new docker version entry for agent test on arm

versions.yaml
Updated the newest-version of openshift to 4.6.
Fixes: github.com/kata-containers/tests#3062
Signed-off-by: Wainer dos Santos Moschetta <wainersm@redhat.com>
=> versions: Bump the newest-version of OpenShift

containerd-shim-v2/service.go
Added tracing with tracer being created in Create, which should ideally
happen in New. Currently getting no trace or span output when the tracer
is created in New or StartShim, or Create before create() is called.
Also no log output from these functions.
To do:
- Determine which context is more appropriate to associate with spans
(ctx passed in or ctx saved in service struct - currently implemented
using service ctx)
- Find out what in create() allows tracing to work and implement it in
New if possible
=> shimv2: Add tracing

Makefile
The default hypervisor variable will no longer be printed from
the Makefile.
Fixes: #2785
Signed-off-by: Benjamin Porter <bporter816@gmail.com>
=> build: Remove default hypervisor message from build

virtcontainers/qemu.go
On pod delete, we were looking to read files that we had just deleted. In particular,
stopSandbox for QEMU was called (we cleanup up vmpath), and then QEMU's
save function was called, which immediately checks for the PID file.
Let's only update the persist store for QEMU if QEMU is actually
running. This'll avoid Error messages being displayed when we are
stopping and deleting a sandbox:
```
level=error msg="Could not read qemu pid file"
```
I reviewed CLH, and it looks like it is already taking appropriate
action, so no changes needed.
Ideally we won't spend much time saving state to persist.json unless
there's an actual error during stop/delete/shutdown path, as the persist will
also be removed after the pod is removed. We may want to optimize this,
as currently we are doing a persist …
=> qemu: no state to save if QEMU isn't running

.github/workflows/snap-release.yaml
Use Github actions to build and release the snap package automatically
when a new tag is pushed.
fixes #3098
=> [backport] snap: add GH actions jobs to release the snap package

virtcontainers/qemu_amd64.go, virtcontainers/qemu_arm64.go, virtcontainers/qemu_ppc64le.go, virtcontainers/qemu_s390x.go
Fixes: #3112
I use kata-runtime event to stat kata container, but  I find the RssAnon of kata-runtime is growing all the time
```
-bash-4.2# kata-runtime events --interval 0.1s 58f11a09c74dce4ac64f32192e36565c5b2da106bc6fedb3647f7f84d2014c41
-bash-4.2# cat /proc/`ps -aux|grep "0.1s"|grep -v grep|awk '{print $2}'`/status|grep RssAnon;date
RssAnon:           52512 kB
Tue Jan  5 17:15:34 CST 2021
-bash-4.2# cat /proc/`ps -aux|grep "0.1s"|grep -v grep|awk '{print $2}'`/status|grep RssAnon;date
RssAnon:           52520 kB
Tue Jan  5 17:15:42 CST 2021
-bash-4.2# cat /proc/`ps -aux|grep "0.1s"|grep -v grep|awk '{print $2}'`/status|grep RssAnon;date
RssAnon:           73776 kB
Tue Jan  5 17:33:32 CST 2021
-bash-4.2# cat /proc/`ps -aux|grep …
```
=> virtcontainers: Fix the memory leak caused by supportedQemuMachines

cli/config/configuration-qemu.toml.in
pflash annotation is placed under factory which should be
hypervisor.
Fixes: #3120
Signed-off-by: <jianyong.wu@arm.com>
@jodh-intel @GabyCT
=> cli/config: move the pflash annotation to hypervisor part

virtcontainers/kata_agent.go
Today we only clear out the cpuset details when doing an update call on
existing container/pods. This works in the case of Kubernetes, but not
in the case where we are explicitly setting the cpuset details at boot
time. For example, if you are running a single container via docker ala:
docker run --cpuset-cpus 0-3 -it alpine sh
What would happen is the cpuset info would be passed in with the
container spec for create container request to the agent. At that point
in time, there'd only be the defualt number of CPUs available in the
guest (1), so you'd be left with cpusets set to 0. Next, we'd hotplug
the vCPUs, providing 0-4 CPUs in the guest, but the cpuset would never
be updated, leaving the application tied to CPU 0.
Ouch.
Until the day we support cpusets in the guest, let's make sure …
=> cpuset: when creating container, don't pass cpuset details

virtcontainers/shim.go
The https://go-review.googlesource.com/c/go/+/231638/ commit on Golang
introduced a failure on Kata Containers when the runtime is built with
golang 15.2+.
Fixes: #2982
(cherry picked from commit c56af73d3d142125e0712028be0b9e179e0ff957)
=> [stable-1.11] virtcontainers: Don't set Ctty

virtcontainers/shim.go
The https://go-review.googlesource.com/c/go/+/231638/ commit on Golang
introduced a failure on Kata Containers when the runtime is built with
golang 15.2+.
Fixes: #2982
(cherry picked from commit c56af73d3d142125e0712028be0b9e179e0ff957)
=> [stable-1.12] virtcontainers: Don't set Ctty

versions.yaml
Cloud-hypervisor now has a stable release v0.14.1 in addition to the
v0.14.0 release last week. Let's keep updated with it, given it contains
several bug fixes.
Details: https://github.com/cloud-hypervisor/cloud-hypervisor/releases/tag/v0.14.1
Fixes: #3151
=> versions: Upgrade to cloud-hypervisor release v0.14.1

.ci/install-yq.sh
Since the resolution of https://github.com/mikefarah/yq/issues/502, the `yq` binary is no longer broken on s390x. This is an upgrade to the latest v3 version of yq (v4 has new syntax). This is a backport of https://github.com/kata-containers/kata-containers/pull/1261.
Fixes: #3134
Depends-on: https://github.com/kata-containers/tests/pull/3158
=> [backport] ci: Upgrade to yq 3.4.1

cli/exec.go
When user runs "kata-runtime exec test something" and then the help information prompted,
the "EXAMPLE" field of the help information missed "exec", see:
`# kata-runtime <container-id> ps`
Obviously it missed the word "exec" following the "kata-runtime".
Fixes: #3154
Signed-Off-By: Liang Zhou <zhoul110@chinatelecom.cn>
=> cli: Fix the incorrect info of command "kata-runtime exec"

versions.yaml, virtcontainers/pkg/cloud-hypervisor/client/api/openapi.yaml, virtcontainers/pkg/cloud-hypervisor/client/docs/NetConfig.md, virtcontainers/pkg/cloud-hypervisor/client/model_net_config.go, virtcontainers/pkg/cloud-hypervisor/cloud-hypervisor.yaml
Quotes from the cloud-hypervisor release v15.0:
This release is the first in a new version numbering scheme to represent that
we believe Cloud Hypervisor is maturing and entering a period of stability.
With this new release we are beginning our new stability guarantees.
Other highlights from the latest release include: 1) Network device rate
limiting; 2) Support for runtime control of `virtio-net` guest offload;
3) `--api-socket` supports file descriptor parameter; 4) Bug fixes on
`virtio-pmem`, PCI BARs alignment, `virtio-net`, etc.; 5) Deprecation of
the "LinuxBoot" protocol for ELF and bzImage in the coming release.
Details can be found: https://github.com/cloud-hypervisor/cloud-hypervisor/releases/tag/v15.0
Note: The client code of cloud-hypervisor's OpenAPI is automatically
generated …
=> versions: Upgrade to cloud-hypervisor v15.0

virtcontainers/qemu.go
When connecting to the qemu socket fails with a connection refused error
assume that qemu died and handle that as if the Sandbox was already
stopped. So that deleteSandbox() can still succeed.
This is needed when working with newer docker releases (19.03). As the
containerd included in there does no longer use the "<runtime> kill"
command before deleting the Sandboxes.
(https://github.com/containerd/containerd/commit/b5ccc66c2c814cfc21d58678c854272427814b59#diff-6a93af2fa6a81ffa3592c6ba4c7f628976e9ac0363a9532589b0fc96f3059ad1)
Fixes: #2611, #2314 
Signed-off-by: Ralf Haferkamp <rhafer@suse.com>
=> qemu: fix stopSandbox() to work with newer docker

virtcontainers/acrn.go, virtcontainers/clh.go, virtcontainers/device/api/interface.go, virtcontainers/device/api/mockDeviceReceiver.go, virtcontainers/device/drivers/block.go, virtcontainers/fc.go, virtcontainers/hypervisor.go, virtcontainers/mock_hypervisor.go, virtcontainers/pkg/firecracker/client/models/boot_source.go, virtcontainers/pkg/firecracker/firecracker.yaml, virtcontainers/qemu.go, virtcontainers/sandbox.go
Add the ability to boot a firecracker VM using an initrd instead of a
block device.
Fixes: #2093
=> virtcontainers: add firecracker initrd support

containerd-shim-v2/delete.go, containerd-shim-v2/start.go
backporting https://github.com/kata-containers/kata-containers/pull/1253
Fixes: #3126
=> log a warning and continue on post-stop hook failure

virtcontainers/device/manager/manager_test.go
Create "class" and "config" file in temporary device BDF dir,
and remove dir created by ioutil.TempDir() when test finished.
Backport  from  kata 2.0 https://github.com/kata-containers/kata-containers/pull/747
Fixes: #2967
Signed-off-by: zhanghj <zhanghj.lc@inspur.com>
=> [backport | master] devices: fix go test warning in manager_test.go

data/kata-collect-data.sh.in
Backported from https://github.com/kata-containers/kata-containers/pull/718
Fixes: #2951
Here anyway we have some older version of the script... should we backport some more commits to make the output as nice as the one in the v2 repo?
=> runtime: add podman to data collection script

cli/spec.go
When use "kata-runtime spec" to generate config.json, 
the default hostname is "runc", which is not correct. 
The proper one should be "kata", instead of "runc".
Fixes: #3157
Signed-off-by: Liang Zhou <zhoul110@chinatelecom.cn>
=> cli: Fix the incorrect default hostname "runc"

cli/config/configuration-qemu-virtiofs.toml.in, cli/config/configuration-qemu.toml.in
The documentation now has notes describing the behavior of qemu.log.
Fixes: #2650 
Signed-off-by: Marcus Mao <marcus_mao@yahoo.com>
=> docs: update documentation to reflect qemu.log behavior
